### ISSUE TITLE
"Custom Paths and Folders" docs say vm_dir can be relative, not working

### ISSUE THREAD

**Issue by JDGrimes** [Varying-Vagrant-Vagrants/VVV#1162]
## Expected Behavior

According to the [Custom Paths and Folders](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/custom-paths-and-folders/) docs, the `vm_dir` can be relative. So my expectation was that this configuration would work:

```yml
  wordpress-tests:
    vm_dir: www/wordpress-tests/htdocs
    local_dir: www/wordpress-tests/htdocs
    hosts:
      - tests.wordpress-develop.dev
```

## Current Behavior

However, when using the above configuration in my `vvv-custom.yml` file, I get an error when running `vagrant provision` from the local VVV directory.

```
$ vagrant provision


  __     ___     ___     __  ____    
  \ \   / \ \   / \ \   / / |___ \   
   \ \ / / \ \ / / \ \ / /    __) |  
    \ V /   \ V /   \ V /    / __/   
     \_/     \_/     \_/    |_____|  

  Varying Vagrant Vagrants 2.0.0

  Docs:       https://varyingvagrantvagrants.org/
  Contribute: https://github.com/varying-vagrant-vagrants/vvv



There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The shared folder guest path must be absolute: www/wordpress-tests/htdocs

```

I had to change the configuration to this for it to work, using an absolute path for `vm_dir`:

```yml
  wordpress-tests:
    vm_dir: /srv/www/wordpress-tests/htdocs
    local_dir: www/wordpress-tests/htdocs
    hosts:
      - tests.wordpress-develop.dev
```

## Possible Solution

Perhaps this is an issue with the docs, or maybe I'm doing something wrong or have found a bug. I'm really not sure.

## Steps to Reproduce (for bugs)

1. Add the configuration for a custom site to `vvv-custom.yml`, as above.
2. Run `vagrant provision`
3. You should get the error that an absolute path is required.
