### ISSUE TITLE
Provision 'custom-dashboard' via 'vvv-custom.yml'

### ISSUE THREAD

**Issue by cfoellmann** [Varying-Vagrant-Vagrants/VVV#1174]
We recommend *Custom Dashboards* in the docs https://varyingvagrantvagrants.org/docs/en-US/#custom-dashboards

Let's make it easy to provision them via the `vvv-custom.yml`

```yml
# Custom Dashboard
dashboard:
  repo: https://github.com/topdown/VVV-Dashboard
```

PR for the WIP will follow
