### ISSUE TITLE
Easiest way to add SSL support

### ISSUE THREAD

**Issue by krismorf** [Varying-Vagrant-Vagrants/VVV#1177]
This is my `vvv-custom.yml` to add support for `https`

```
---
sites:
  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - site1.wordpress-develop.dev
      - site2.wordpress-develop.dev

utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind

```

After doing a `vagrant provision` you need to extract the certificate from your browser (drag + drop to desktop) and install it. 

This works because in `provision.sh:399` it creates a certificate with the default site names as common names: `/CN=*.wordpress-develop.dev/CN=*.wordpress.dev/CN=*.vvv.dev`

The only downside I can think of right now is that vagrant triggers backup the whole site as 1 database and not per subdomain.
