### ISSUE TITLE
Deprecate vvv-wordpress-default

### ISSUE THREAD

**Issue by LoreleiAurora** [Varying-Vagrant-Vagrants/VVV#1227]
We should deprecate vvv-wordpress-default as the exact same config can be achieved with the custom-site template using this config
```
wordpress_default:
  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template
  hosts:
    - local.wordpress.dev
```
