### ISSUE TITLE
wordpress-develop not installed

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#1255]
## Expected Behavior
Add on vvv-custom.yml:
```
wordpress-develop:
        repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
        nginx_upstream: php71
        hosts:
            - src.wordpress-develop.dev
            - build.wordpress-develop.dev
```
Get www/wordpress-develop

## Current Behavior
No folder :-/

Actually is an old installation of VVV moved during the years and now use VVV 2.0. After this problems I am migrating all the old website on the new VVV standard way but wordpress-develop seems ignored on my vvv-custom.yml file.

## Your Environment
* VVV version: last commit
* Vagrant version: 1.9.1
* VM Provider name: virtualbox
* VM Provider version:
* Operating System and version:linux
