### ISSUE TITLE
Method for storing git credentials

### ISSUE THREAD

**Issue by paulschreiber** [Varying-Vagrant-Vagrants/VVV#1304]
In `vvv-custom.yml`, I have a site defined like so:

```
---
sites:
  stuff:
    repo: https://stuff.com/stuff.git
    hosts:
      - stuff.local
```

When I try to provision (`vagrant up --provision`), checking out fails like so:
```
fatal: could not read Username for 'https://stuff.com': No such device or address
```

I can work around this by supplying the credentials:
```
---
sites:
  stuff:
    repo: https://paul:mypassword@stuff.com/stuff.git
    hosts:
      - stuff.local
```

Storing credentials in plaintext is something I'd like to avoid. What's the recommended method for handling credentials?
