### ISSUE TITLE
Custom-site-template subdomain ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by tini2n** [Varying-Vagrant-Vagrants/VVV#1395]
## My Environment
* VVV version: 2.1.0
* VVV Git Branch: master
* Vagrant version: 2.0.1
* VM Provider name: VirtualBox
* VM Provider version: 5.1.6
* Operating System and version: MacOS Sierra 10.12.6

### vvv-custom.yml
```
wp:
  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  hosts:
   - wp.test
  custom:
    wp_type: subdomain

utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind
```

When I goes to `wp.test` everything fine, site is working. I created new subdomain site `*.wp.test` in network and it's cause error `ERR_NAME_NOT_RESOLVED` when I goes there. Maybe I need to edit `vvv-nginx.conf` of this site?
