### ISSUE TITLE
Bug: vvv-custom.yml site->repo field does not update after first provision

### ISSUE THREAD

**Issue by scarstens** [Varying-Vagrant-Vagrants/VVV#1422]
## Expected Behavior
I'm expecting that if I provision a site (site1.test) with a repo defined as github.com/site1rev1 and I change the repo to github.com/site1rev2, that a new provision of that site would use the new repo information from the YML config.

## Current Behavior
The provisioning process seems to cache some of the details about the YML configuration, specifically the repo string. The only way I've found to cause an update is to completely delete the site provision and start over.

## Possible Solution
Always pull in a fresh copy of the YML configuration when a provision is called for like
```
vagrant halt ; vagrant up --provision-with site-site1.test
```

## Steps to Reproduce (for bugs)
1. create a new site in the vvv-custom.yml file like:
```
site1.test:
  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  hosts:
    - site1.test
```
2. provision the site:
```
vagrant halt; vagrant up --provision-with site-site1.test ;
```
3. Change the repo param to something new in teh vvv-custom.yml
```
site1.test:
  repo: https://github.com/WordPress-Phoenix/vvv2-provision-boilerplate
  hosts:
    - site1.test
```
4. re-provision the site
```
vagrant halt; vagrant up --provision-with site-site1.test ;
```
5. Note that it didn't actually pull from the new repository location.

## Context
I have had to create a process where a github access token is passed through the REPO url. We often regenerate these temporary tokens, but updating the REPO parameter does not work during a provision and it prevents any future provisions from running properly.

## Your Environment
* VVV version: 2.2.0 beta
* VVV Git Branch: develop
* Vagrant version: 2.0.2
* VM Provider name: VirtualBox
* VM Provider version: 5.1.30
* Operating System and version: Mac OSX 10.13.3
