### ISSUE TITLE
sites redirecting to each other?

### ISSUE THREAD

**Issue by AlfredJKwack** [Varying-Vagrant-Vagrants/VVV#1435]
Hello,

I have 2 sites configured in my `vvv-custom.yml` as shown below all on a fresh vvv and vagrant install. I have properly provisioned them. When I open _abelgianabroad.test_ in a browser it redirects and responds on _atableavecmaya.test_. 

What am I doing wrong here, or what's going on?

## vvv-custom.yml
```
sites:
  abelgianabroad:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template
    description: "A Belgian Abroad"
    skip_provisioning: false
    hosts:
      - abelgianabroad.test
    custom:
      wp_type: single
  atableavecmaya:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template
    description: "A Table Avec Maya"
    skip_provisioning: false
    hosts:
      - atableavecmaya.test
    custom:
      wp_type: single
```

## Browser logs
Request Headers
```
GET / HTTP/1.1
Host: abelgianabroad.test
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,fr;q=0.8,nl;q=0.7
DNT: 1
```
Response Headers
```
HTTP/1.1 302 Found
Server: nginx
Date: Thu, 22 Feb 2018 22:05:13 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Location: http://atableavecmaya.test/
```
## hosts file
```
vagrant@vvv:/srv$ cat /etc/hosts
127.0.0.1	vvv	vvv
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
vagrant@vvv:/srv$ cat /etc/hosts
127.0.0.1	vvv	vvv
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
127.0.0.1 abelgianabroad.test # vvv-auto
127.0.0.1 atableavecmaya.test # vvv-auto
127.0.0.1 abelgianabroad.test # vvv-auto
```
## Nginx configuration
```
vagrant@vvv:/srv$ la /etc/nginx/custom-sites/
default.conf
local-nginx-example.conf-sample
vvv-auto-abelgianabroad-provision-9de3591ac1b238a42235eba7c3b30c09.conf
vvv-auto-atableavecmaya-provision-69021575a57cc81fa9cbdd702c8741e9.conf
```
```
vagrant@vvv:/srv$ cat /etc/nginx/custom-sites/vvv-auto-abelgianabroad-provision-9de3591ac1b238a42235eba7c3b30c09.conf 
server {
    listen       80;
    listen       443 ssl;
    server_name  abelgianabroad.test;
    root         /srv/www/abelgianabroad/public_html;

    error_log    /srv/www/abelgianabroad/log/error.log;
    access_log   /srv/www/abelgianabroad/log/access.log;

    set          $upstream php;

    include      /etc/nginx/nginx-wp-common.conf;
}
```

## Environment
* VVV version: v2.1.0
* VVV Git Branch: master
* Vagrant version: 2.0.2
* VM Provider name: VirtualBox
* VM Provider version:5.2.6
* Operating System and version: MacOS 10.13.3
* Browser(s): Chrome v64 & Safari v11.0.3
