### ISSUE TITLE
Location of the site inside the vagrant is empty

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/VVV#1463]
I have created a site that is outside the normal vagrant folders (`~vagrant-local/www/my-blog`)

```yaml
my-blog:
    vm_dir: /srv/www/my-blog
    local_dir: ~/dev/my-blog/blog
    hosts:
      - blog.my-blog.io.test
```

As you can see the installed site is in my `~/dev` folder. When I go to vagrant with `vagrant ssh` I can go to `/srv/www/my-blog`, but this folder is empty.

So does that mean that I cannot access it from within the vagrant? I need this so that I can run `wp-cli` scripts.

## Your Environment

* VVV version: 2.1.0
* VVV Git Branch: master
* Vagrant version: 2.0.3
* VM Provider name: VirtualBox
* VM Provider version: 5.2.8
* Operating System and version: macOS 10.13.4
