### ISSUE TITLE
All Domains Point to One URL

### ISSUE THREAD

**Issue by benleeth** [Varying-Vagrant-Vagrants/VVV#1465]
I have my vvv-custom.yml set up as such:

```
---

sites:

  imagineindiana:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    nginx_upstream: php70
    hosts:
      - imagineindiana.test

  jordanstandard:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    nginx_upstream: php70
    hosts:
      - jordanstandard.test

  puffpost:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    nginx_upstream: php70
    hosts:
      - puffpost.test

  ssc:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    nginx_upstream: php70
    hosts:
      - ssc.test

utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind
    - php56
    - php70
    - php71
```

However, any time I put in the url (ssc.test, puffpost.test, etc), they all end up going to jordanstandard.test. I can't figure out why this is. Can someone help me?

## Environment
* VVV version: 2.1.0
* VVV Git Branch: master
* Vagrant version: 2.0.3
* VM Provider name: virtualBox
* VM Provider version: 5.2.10 r122088
* Operating System and version: OS X 10.13.4
