### ISSUE TITLE
New VM provisioned, site added from external folder doesn't load

### ISSUE THREAD

**Issue by paulcanning** [Varying-Vagrant-Vagrants/VVV#1466]
I have added a new site to vvv-custom.yml and after running vagrant up, not only does vvv.test not load properly (I have to browse to 192.168.50.4), my new site does not load at all (I get the VVV page).

The two WP installs load fine.

vvv-custom.yml

```
sites:
  # The wordpress-default configuration provides a default installation of the
  # latest version of WordPress.
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
    hosts:
      - local.wordpress.test

  # The wordpress-develop configuration is useful for contributing to WordPress.
  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
    hosts:
      - src.wordpress-develop.test
      - build.wordpress-develop.test

  my-site:
    vm_dir: /srv/www/my-site
    local_dir: /Users/my.name/PHP/my-site
    hosts:
      - my-site.test
```
