### ISSUE TITLE
PHPMyAdmin - 403 Forbidden

### ISSUE THREAD

**Issue by andreagrillo** [Varying-Vagrant-Vagrants/VVV#1547]
Easy bug, I have added a new site and after vagrant reload --provision I can't access to PHPMyAdmin, I receive a 403 Forbidden error page. Only This. 

All other modules working fine, sites working fine....no other issue. 

Any Idea ? 
Thanks for your time

AG

**Comment by tomjn** [comment]
As an aside, you can use any MySQL client in place of PHPMyAdmin

**Comment by andreagrillo** [comment]
Hi there, 

after `git pull` I tried to make a `vagrant up --provision` but I receive this error:

`This Vagrant environment has specified that it requires the Vagrant
version to satisfy the following version requirements:

  >= 2.1.0

You are running Vagrant 2.0.4, which does not satisfy
these requirements. Please change your Vagrant version or update
the Vagrantfile to allow this Vagrant version. However, be warned
that if the Vagrantfile has specified another version, it probably has
good reason to do so, and changing that may cause the environment to
not function properly.
`

but you tell me to don't use vvv with Vagrant version 2.1.0, right ?

**Comment by tomjn** [comment]
With the v2.2.1 release, we fixed the vagrant trigger issue and Vagrant 2.1 is needed now, so upgrade and uninstall vagrant triggers

**Comment by andreagrillo** [comment]
ok, Done! Working fine now, but PHPMyAdmin doesn't works...403 Forbidden, too. 

Do you have other idea ?

**Comment by tomjn** [comment]
Does completely deleting PHPMyAdmin and reprovisioning correct the issue?

**Comment by andreagrillo** [comment]
no, I have deleted  PHPMyAdmin, update vagrant and vvv to latest one and make a provisioning. Nothing, doesn't works.

**Comment by ACatThatPrograms** [comment]
Looking into this as well, as I am experiencing the same issue. 

I think something with provisioning going awry.

Here is the snippet where I think something is going wrong:

```
    default: Installing/Updating PHPMyAdmin
    default: rm:
    default: cannot remove ‘/srv/www/default/database-admin/vendor/codacy/coverage/.git/objects/pack/pack-3818f69fa7bd64ef22c94c0bf630c18333cd5da9.idx’
    default: : Operation not permitted
    default: rm:
    default: cannot remove ‘/srv/www/default/database-admin/vendor/codacy/coverage/.git/objects/pack/pack-3818f69fa7bd64ef22c94c0bf630c18333cd5da9.pack’
    default: : Operation not permitted
    default: Do not run Composer as root/super user! See https://getcomposer.org/root for details
    default: Installing phpmyadmin/phpmyadmin (4.8.1)
    default:
    default:   [InvalidArgumentException]
    default:   Project directory ./ is not empty.

```
I have to take a break, as I need to dig through the provision code and or my box to see why it isn't emptying before trying to install.

Also, if you ssh into the box, you'll notice /srv/www/default/database-admin has no index.php file or anything to load via nginx, so I don't believe it's a permission error.
