### ISSUE TITLE
xdebug not formatting var_dump() output

### ISSUE THREAD

**Issue by marcelo2605** [Varying-Vagrant-Vagrants/VVV#1563]
After update to version 2.2.1, xdebug is not formatting debug output on screen. Before this update, I just run `xdebug_on` on SSH.

## Your Environment

* VVV version: 2.2.1
* VVV Git Branch: master
* Vagrant version: 2.1.1
* VM Provider name: VirtualBox
* VM Provider version: 5.2.4 r119785 (Qt5.6.2)
* Operating System and version: Windows 10

**Comment by tomjn** [comment]
Is `xdebug` turned on? It gets turned off during provisioning, otherwise provisions would take a veeerry long time

**Comment by tomjn** [comment]
Additionally, can you try with `develop` just to confirm it's not already been fixed by something else?

**Comment by marcelo2605** [comment]
Hi @tomjn 

Here is my terminal output:

> vagrant@vvv:~$ xdebug_on
> php7.0-fpm stop/waiting
> php7.0-fpm start/running, process 11241

But xdebug not appear in vvv.test/phpinfo

I need to run `vagrant reload --provision` after run this?

**Comment by tomjn** [comment]
Reprovisioning shouldn't be necessary, in fact reprovisioning would call `xdebug_off`

However, I do see that it triggered `php7.0-fpm`, but the default is actually PHP 7.2.

So I suspect that it's working, but you're using a different PHP version

**Comment by tomjn** [comment]
Can you update to the latest `develop` branch, reprovision, and try again? Additionally what's in your `vvv-custom.yml`?

**Comment by marcelo2605** [comment]
OK, I will do this later and reply back.

Here is my vvv-custom.yml:

```
---

# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

#
# IMPORTANT, if you change this file, you have to reprovision,  no exceptions
# vagrant reload --provision
#

# These are your websites, and their names map on to the folders they're
# located in. See the docs for how to define these, and what all the keys
# and options are
sites:

  isk:
    hosts:
      - isk.test
      
  # The wordpress-default configuration provides a default installation of the
  # latest version of WordPress.
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
    hosts:
      - local.wordpress.test

  # The wordpress-develop configuration is useful for contributing to WordPress.
  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
    hosts:
      - src.wordpress-develop.test
      - build.wordpress-develop.test

  # The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://my-example-site.dev.
  # Remember, whitespace is significant! Tabs and spaces mean different things

  #example-site:
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    - my-example-site.test

  # The following commented out site configuration will create a environment useful
  # for contributions to the WordPress meta team:
  
  #wordpress-meta-environment:
  #  repo: https://github.com/WordPress/meta-environment.git


# Utilities are system level items rather than sites, that install tools or packages
# the core utilities install tools such as phpmyadmin
utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind

```
