### ISSUE TITLE
site config defaults

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1572]
Some users still rely on the deprecated `vvv-hosts` file for convenience, because they prefer a cleaner config file, or because it's an excessive list, or other reasons.

But, this is a symptom of a deeper need, predefined configs.

So Instead, I offer a suggestion:

`provision/vvv-site.yml`:

```yaml
hosts:
  - 1.test
  - 2.test
  - 3.test
  - 4.test
  - 5.test
```

`vvv-custom.yml`:

```yaml
  mysite:
    repo: .... etc
```

The Provisioner can then take the `vvv-site.yml` data as the initial values, then apply the options from `vvv-custom.yml` over the top as overrides to come to a final setup.

In the above example, a site might only need `mysite: https://github.com.... etc` to arrive at a default setup. Then the user could set up a second site like this:

```yaml
  preprodmysite:
    repo: ....
    branch: preprod
```

Or:

```yaml
  preprodmysite:
    repo: ....
    branch: preprod
    hosts:
      - preprod.mysite.test
```

the mysite repo might then have something like this:

```yaml
hosts:
  - mysite.test
```

Or other values that the `vvv-init.sh` provisioner needs that could be overriden, such as changing to a multisite, etc
