### ISSUE TITLE
Sites with skip provisioning set to true have their hosts provisioned

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1663]
If I set a site to `skip_provisioning: true`, nothing about that sites provisioners should run

## Expected Behavior

This sites hosts should not be provisioned by the hosts updater:

```yaml
  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
    skip_provisioning: true
    hosts:
      - src.wordpress-develop.test
      - build.wordpress-develop.test
```

## Current Behavior

The 2 hosts shown above get added to the hosts file despite skip provisioning being true.

This is also a potential slow down as VVV searches subfolders for `vvv-hosts` files

## Possible Solution

Check if skip provisioning is true when scanning for hosts

## Steps to Reproduce (for bugs)

1. Add a site to `vvv-custom.yml`
2. Set `skip_provisioning: true` for that site
3. Reprovision

## Your Environment

* VVV version: `2.3.1`
* VVV Git Branch: `develop`
* Vagrant version: `2.2.0`
* VM Provider name: `VirtualBox`
* VM Provider version: `5.2.18`
* Operating System and version: MacOS Mojave
