### ISSUE TITLE
Fails to start with vagrant 2.2.2

### ISSUE THREAD

**Issue by pdewouters** [Varying-Vagrant-Vagrants/VVV#1689]
## Expected Behavior

`vagrant up --provision` should start up the box
## Current Behavior
the command fails, unable to use the box. reverting to `2.2.1` the error persists

```➜  vagrant-local git:(master) vagrant up --provision
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v2.4.0-git::master

Platform:   darwin13.4.0 shell:/bin/zsh
Vagrant:    2.2.1
VirtualBox: 5.2.22r126460

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.test
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.local
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.localhost
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 local.wordpress.test
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 local.wordpress.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 src.wordpress-develop.test
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 build.wordpress-develop.test
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 src.wordpress-develop.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 build.wordpress-develop.dev
==> default: Running provisioner: fix-no-tty (shell)...
    default: Running: inline script
==> default: Running provisioner: default (shell)...
    default: Running: /var/folders/xb/0v2yqy6970bcw6fgwb1yhq7c0000gn/T/vagrant-shell20181219-54248-c3fp3c.sh
    default: Succesful Network connection to ppa.launchpad.net detected...
    default: Bash profile setup and directories.
    default: cp:
    default: cannot stat ‘/srv/config/update-motd.d/00-vvv-bash-splash’
    default: : No such file or directory
    default: chmod:
    default: cannot access ‘/etc/update-motd.d/00-vvv-bash-splash’
    default: : No such file or directory
    default: cp:
    default: cannot stat ‘/srv/config/bash_profile’
    default: : No such file or directory
    default: cp:
    default: cannot stat ‘/srv/config/bash_aliases’
    default: : No such file or directory
    default: cp:
    default: cannot stat ‘/srv/config/vimrc’
    default: : No such file or directory
    default: cp:
    default: cannot stat ‘/srv/config/subversion-servers’
    default: : No such file or directory
    default: cp:
    default: cannot stat ‘/srv/config/subversion-config’
    default: : No such file or directory
    default:  * Copied /srv/config/bash_profile                      to /home/vagrant/.bash_profile
    default:  * Copied /srv/config/bash_aliases                      to /home/vagrant/.bash_aliases
    default:  * Copied /srv/config/vimrc                             to /home/vagrant/.vimrc
    default:  * Copied /srv/config/subversion-servers                to /home/vagrant/.subversion/servers
    default:  * Copied /srv/config/subversion-config                 to /home/vagrant/.subversion/config
    default: Succesful Network connection to ppa.launchpad.net detected...
    default:
    default: Main packages check and install.
    default: Adding ppa:git-core/ppa repository
    default: Linked custom apt sources
    default: Applying the PackageCloud signing key...
    default: gpg:
    default: can't open `/vagrant/config/apt-keys/git-lfs.key': No such file or directory
    default: Running apt-get update...
    default: Hit http://ppa.launchpad.net trusty InRelease
    default: Ign http://archive.ubuntu.com trusty InRelease
    default: Hit http://security.ubuntu.com trusty-security InRelease
    default: Hit http://ppa.launchpad.net trusty InRelease
    default: Hit http://archive.ubuntu.com trusty-updates InRelease
    default: Hit http://security.ubuntu.com trusty-security/main Sources
    default: Hit http://archive.ubuntu.com trusty-backports InRelease
    default: Hit http://ppa.launchpad.net trusty/main amd64 Packages
    default: Hit http://security.ubuntu.com trusty-security/universe Sources
    default: Hit http://archive.ubuntu.com trusty Release.gpg
    default: Hit http://security.ubuntu.com trusty-security/main amd64 Packages
    default: Hit http://archive.ubuntu.com trusty-updates/main Sources
    default: Hit http://ppa.launchpad.net trusty/main Translation-en
    default: Hit http://archive.ubuntu.com trusty-updates/restricted Sources
    default: Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
    default: Hit http://ppa.launchpad.net trusty/main amd64 Packages
    default: Hit http://archive.ubuntu.com trusty-updates/universe Sources
    default: Hit http://security.ubuntu.com trusty-security/main Translation-en
    default: Hit http://archive.ubuntu.com trusty-updates/multiverse Sources
    default: Hit http://security.ubuntu.com trusty-security/universe Translation-en
    default: Hit http://ppa.launchpad.net trusty/main Translation-en
    default: Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
    default: Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages
    default: Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
    default: Hit http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages
    default: Hit http://archive.ubuntu.com trusty-updates/main Translation-en
    default: Hit http://archive.ubuntu.com trusty-updates/multiverse Translation-en
    default: Hit http://archive.ubuntu.com trusty-updates/restricted Translation-en
    default: Hit http://archive.ubuntu.com trusty-updates/universe Translation-en
    default: Hit http://archive.ubuntu.com trusty Release
    default: Hit http://archive.ubuntu.com trusty-backports/main Sources
    default: Hit http://archive.ubuntu.com trusty-backports/restricted Sources
    default: Hit http://archive.ubuntu.com trusty-backports/universe Sources
    default: Hit http://archive.ubuntu.com trusty-backports/multiverse Sources
    default: Hit http://archive.ubuntu.com trusty-backports/main amd64 Packages
    default: Hit http://archive.ubuntu.com trusty-backports/restricted amd64 Packages
    default: Hit http://archive.ubuntu.com trusty-backports/universe amd64 Packages
    default: Hit http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages
    default: Hit http://archive.ubuntu.com trusty-backports/main Translation-en
    default: Hit http://archive.ubuntu.com trusty-backports/multiverse Translation-en
    default: Hit http://archive.ubuntu.com trusty-backports/restricted Translation-en
    default: Hit http://archive.ubuntu.com trusty-backports/universe Translation-en
    default: Hit http://archive.ubuntu.com trusty/main Sources
    default: Hit http://archive.ubuntu.com trusty/restricted Sources
    default: Hit http://archive.ubuntu.com trusty/universe Sources
    default: Hit http://archive.ubuntu.com trusty/multiverse Sources
    default: Hit http://archive.ubuntu.com trusty/main amd64 Packages
    default: Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
    default: Hit http://archive.ubuntu.com trusty/universe amd64 Packages
    default: Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages
    default: Hit http://archive.ubuntu.com trusty/main Translation-en
    default: Hit http://archive.ubuntu.com trusty/multiverse Translation-en
    default: Hit http://archive.ubuntu.com trusty/restricted Translation-en
    default: Hit http://archive.ubuntu.com trusty/universe Translation-en
    default: Ign http://archive.ubuntu.com trusty/main Translation-en_US
    default: Ign http://archive.ubuntu.com trusty/multiverse Translation-en_US
    default: Ign http://archive.ubuntu.com trusty/restricted Translation-en_US
    default: Ign http://archive.ubuntu.com trusty/universe Translation-en_US
    default: Reading package lists...
    default: Installing apt-get packages...
    default: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: E
    default: :
    default: Unable to locate package git-lfs
    default: Main packages check and install failed, halting provision
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

## Steps to Reproduce (for bugs)

1. install vagrant 2.2.2
2. run `vagrant up --provision`
3. note the error messages

## Your Environment

* VVV version: 2.4.0
* VVV Git Branch: master/develop
* Vagrant version: 2.2.2 then downgraded to 2.2.1 but didn't fix issue
* VM Provider name: virtualbox
* VM Provider version: 5.2.22
* Operating System and version: mac os mojave

**Comment by tomjn** [comment]
Specifically, it appears the shared folders didn't mount into the VM

**Comment by pdewouters** [comment]
hey @tomjn  `vagrant/config` doesn't exist no

**Comment by tomjn** [comment]
Then shared folders is broken for some reason, are the VB Guest Additions up to date? Does this happen on a fresh VVV ( use a different folder to do this )?

**Comment by tomjn** [comment]
hmm, after the vagrant hosts updater section, it usually mounts the shared folders, but that section is missing in your output. E.g. here is a snippet from a `vagrant up` I did just now:

```
==> default: [vagrant-hostsupdater]   192.168.50.4  local.wordpress.local  # VAGRANT: d8475ddbd85f331ab03aba6c37a84ba7 (default) / b83f9559-e606-42dd-8db9-50154fe23f17
==> default: [vagrant-hostsupdater]   192.168.50.4  local.wordpress.dev  # VAGRANT: d8475ddbd85f331ab03aba6c37a84ba7 (default) / b83f9559-e606-42dd-8db9-50154fe23f17
==> default: [vagrant-hostsupdater]   192.168.50.4  hashes.test  # VAGRANT: d8475ddbd85f331ab03aba6c37a84ba7 (default) / b83f9559-e606-42dd-8db9-50154fe23f17
==> default: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /var/log => /Users/tarendai/dev/www/vvv/log
    default: /srv/www => /Users/tarendai/dev/www/vvv/www
    default: /vagrant => /Users/tarendai/dev/www/vvv
    default: /srv/config => /Users/tarendai/dev/www/vvv/config
    default: /srv/database => /Users/tarendai/dev/www/vvv/database
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: shell...
    default: Running: inline script
    default:  * Stopping MariaDB database server mysqld
    default:    ...done.
```

**Comment by tomjn** [comment]
@pdewouters have you turned off local SMB support in MacOS on your account?

In https://www.vagrantup.com/docs/synced-folders/smb.html it says it's needed for it to work

> To use the SMB synced folder type on a macOS host, file sharing must be enabled for the local account. Enable SMB file sharing by following the instructions below:
> 
> - Open "System Preferences"
> - Click "Sharing"
> - Check the "On" checkbox next to "File Sharing"
> - Click "Options"
> - Check "Share files and folders using SMB"
> - Check the "On" checkbox next to your username within "Windows File Sharing"
> - Click "Done"

**Comment by pdewouters** [comment]
@tomjn a new install works fine

**Comment by pdewouters** [comment]
```    default: nginx: [emerg] open() "/srv/www/wordpress-default/log/error.log" failed (2: No such file or directory)
    default: nginx: configuration file /etc/nginx/nginx.conf test failed
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.```

Should `vagrant up`  fail because of a missing error log? I think I deleted it because it was huge

**Comment by tomjn** [comment]
I wouldn't expect it to, but you might need to `vagrant up --provision` to recreate it, even if it's just an empty file, `touch` should do the job

**Comment by tomjn** [comment]
If a new install works fine, then a `vagrant destroy` and recreating it would probably fix this. The only thing to keep in mind is that the DB is stored inside the VM. You might want to check the backups VVV creates, or take your own copies via `vagrant ssh` and rsync. Although, I'd prefer to identify the cause of the problem

As an aside, do you have the vagrant bindfs plugin installed? If so, try this branch https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1686 to see if it makes much of a change, it's unlikely to, but on the offchance

**Comment by pdewouters** [comment]
`vagrant up --provision` now gives 

```
 default: Running: /var/folders/xb/0v2yqy6970bcw6fgwb1yhq7c0000gn/T/vagrant-shell20181219-68187-tv5rmo.sh
    default: /tmp/vagrant-shell: line 10: provision-network-functions.sh: No such file or directory
    default: /tmp/vagrant-shell: line 688: network_check: command not found
    default: Bash profile setup and directories.
    default: cp:
    default: cannot stat ‘/srv/config/update-motd.d/00-vvv-bash-splash’
    default: : No such file or directory
    default: chmod:
    default: cannot access ‘/etc/update-motd.d/00-vvv-bash-splash’
    default: : No such file or directory
    default: cp:
    default: cannot stat ‘/srv/config/bash_profile’
    default: : No such file or directory
    default: cp:
    default: cannot stat ‘/srv/config/bash_aliases’
    default: : No such file or directory
    default: cp:
    default: cannot stat ‘/srv/config/vimrc’
    default: : No such file or directory
    default: cp:
    default: cannot stat ‘/srv/config/subversion-servers’
    default: : No such file or directory
    default: cp:
    default: cannot stat ‘/srv/config/subversion-config’
    default: : No such file or directory
    default:  * Copied /srv/config/bash_profile                      to /home/vagrant/.bash_profile
    default:  * Copied /srv/config/bash_aliases                      to /home/vagrant/.bash_aliases
    default:  * Copied /srv/config/vimrc                             to /home/vagrant/.vimrc
    default:  * Copied /srv/config/subversion-servers                to /home/vagrant/.subversion/servers
    default:  * Copied /srv/config/subversion-config                 to /home/vagrant/.subversion/config
    default: /tmp/vagrant-shell: line 694: network_check: command not found
    default:
    default: Main packages check and install.
    default: Adding ppa:git-core/ppa repository
    default: Linked custom apt sources
    default: Applying the PackageCloud signing key...
    default: gpg:
    default: can't open `/vagrant/config/apt-keys/git-lfs.key': No such file or directory
    default: Running apt-get update...
    default: Hit http://ppa.launchpad.net trusty InRelease
    default: Ign http://archive.ubuntu.com trusty InRelease
    default: Hit http://security.ubuntu.com trusty-security InRelease
    default: Hit http://archive.ubuntu.com trusty-updates InRelease
    default: Hit http://ppa.launchpad.net trusty InRelease
    default: Hit http://archive.ubuntu.com trusty-backports InRelease
    default: Hit http://security.ubuntu.com trusty-security/main Sources
    default: Hit http://archive.ubuntu.com trusty Release.gpg
    default: Hit http://ppa.launchpad.net trusty/main amd64 Packages
    default: Hit http://archive.ubuntu.com trusty-updates/main Sources
    default: Hit http://security.ubuntu.com trusty-security/universe Sources
    default: Hit http://archive.ubuntu.com trusty-updates/restricted Sources
    default: Hit http://security.ubuntu.com trusty-security/main amd64 Packages
    default: Hit http://ppa.launchpad.net trusty/main Translation-en
    default: Hit http://archive.ubuntu.com trusty-updates/universe Sources
    default: Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
    default: Hit http://archive.ubuntu.com trusty-updates/multiverse Sources
    default: Hit http://ppa.launchpad.net trusty/main amd64 Packages
    default: Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
    default: Hit http://security.ubuntu.com trusty-security/main Translation-en
    default: Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages
    default: Hit http://security.ubuntu.com trusty-security/universe Translation-en
    default: Hit http://ppa.launchpad.net trusty/main Translation-en
    default: Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
    default: Hit http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages
    default: Hit http://archive.ubuntu.com trusty-updates/main Translation-en
    default: Hit http://archive.ubuntu.com trusty-updates/multiverse Translation-en
    default: Hit http://archive.ubuntu.com trusty-updates/restricted Translation-en
    default: Hit http://archive.ubuntu.com trusty-updates/universe Translation-en
    default: Hit http://archive.ubuntu.com trusty Release
    default: Hit http://archive.ubuntu.com trusty-backports/main Sources
    default: Hit http://archive.ubuntu.com trusty-backports/restricted Sources
    default: Hit http://archive.ubuntu.com trusty-backports/universe Sources
    default: Hit http://archive.ubuntu.com trusty-backports/multiverse Sources
    default: Hit http://archive.ubuntu.com trusty-backports/main amd64 Packages
    default: Hit http://archive.ubuntu.com trusty-backports/restricted amd64 Packages
    default: Hit http://archive.ubuntu.com trusty-backports/universe amd64 Packages
    default: Hit http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages
    default: Hit http://archive.ubuntu.com trusty-backports/main Translation-en
    default: Hit http://archive.ubuntu.com trusty-backports/multiverse Translation-en
    default: Hit http://archive.ubuntu.com trusty-backports/restricted Translation-en
    default: Hit http://archive.ubuntu.com trusty-backports/universe Translation-en
    default: Hit http://archive.ubuntu.com trusty/main Sources
    default: Hit http://archive.ubuntu.com trusty/restricted Sources
    default: Hit http://archive.ubuntu.com trusty/universe Sources
    default: Hit http://archive.ubuntu.com trusty/multiverse Sources
    default: Hit http://archive.ubuntu.com trusty/main amd64 Packages
    default: Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
    default: Hit http://archive.ubuntu.com trusty/universe amd64 Packages
    default: Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages
    default: Hit http://archive.ubuntu.com trusty/main Translation-en
    default: Hit http://archive.ubuntu.com trusty/multiverse Translation-en
    default: Hit http://archive.ubuntu.com trusty/restricted Translation-en
    default: Hit http://archive.ubuntu.com trusty/universe Translation-en
    default: Ign http://archive.ubuntu.com trusty/main Translation-en_US
    default: Ign http://archive.ubuntu.com trusty/multiverse Translation-en_US
    default: Ign http://archive.ubuntu.com trusty/restricted Translation-en_US
    default: Ign http://archive.ubuntu.com trusty/universe Translation-en_US
    default: Reading package lists...
    default: Installing apt-get packages...
    default: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: E
    default: :
    default: Unable to locate package git-lfs
    default: Main packages check and install failed, halting provision
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
