### ISSUE TITLE
New Install Not Working on Multiple Machines - PHP 7.2 Issue

### ISSUE THREAD

**Issue by EricRihlmann** [Varying-Vagrant-Vagrants/VVV#1772]
## Expected Behavior
For `vagrant up` to work on a new installation.

## Current Behavior
Receive the following error messages about PHP 7.2 packages not being available.

```
    default: E: Package 'php7.2-fpm' has no installation candidate
    default: E: Package 'php7.2-cli' has no installation candidate
    default: E: Unable to locate package php7.2-common
    default: E: Couldn't find any package by regex 'php7.2-common'
    default: E: Package 'php7.2-dev' has no installation candidate
    default: E: Package 'php-imagick' has no installation candidate
    default: E: Package 'php-memcache' has no installation candidate
    default: E: Package 'php-memcached' has no installation candidate
    default: E: Package 'php-ssh2' has no installation candidate
    default: E: Package 'php-xdebug' has no installation candidate
    default: E: Package 'php7.2-bcmath' has no installation candidate
    default: E: Package 'php7.2-curl' has no installation candidate
    default: E: Package 'php7.2-gd' has no installation candidate
    default: E:
    default: Package 'php7.2-mbstring' has no installation candidate
    default: E: Package 'php7.2-mysql' has no installation candidate
    default: E: Package 'php7.2-imap' has no installation candidate
    default: E: Package 'php7.2-json' has no installation candidate
    default: E: Package 'php7.2-soap' has no installation candidate
    default: E: Package 'php7.2-xml' has no installation candidate
    default: E: Package 'php7.2-zip' has no installation candidate
    default: Main packages check and install failed, halting provision
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

## Possible Solution
Upgrade to PHP 7.3 by default?

## Steps to Reproduce (for bugs)
1. `git clone https://github.com/Varying-Vagrant-Vagrants/VVV.git`
2. `vagrant up`

## Your Environment
* VVV version: 2.6.0
* VVV Git Branch: DEVELOP
* Vagrant version: 2.2.2
* VM Provider name:  VirtualBox
* VM Provider version: 5.2.26
* Operating System and version: MacOS 10.13.6

**Comment by Mte90** [comment]
it is probably because of https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1769
you should use the `develop` version until we don't release the 2.7 version that fix this.

**Comment by benedicksahagun** [comment]
I just tried on my Mac. Even with the latest commit on `develop` branch, it shows 
```
default: Package php7.2-soap is not available, but is referred to by another package.
    default: This may mean that the package is missing, has been obsoleted, or
    default: is only available from another source
    default: Package php-imagick is not available, but is referred to by another package.
    default: This may mean that the package is missing, has been obsoleted, or
    default: is only available from another source
    default: Package php-memcache is not available, but is referred to by another package.
    default: This may mean that the package is missing, has been obsoleted, or
    default: is only available from another source
    default: Package php-memcached is not available, but is referred to by another package.
    default: This may mean that the package is missing, has been obsoleted, or
    default: is only available from another source
    default: Package php-ssh2 is not available, but is referred to by another package.
    default: This may mean that the package is missing, has been obsoleted, or
    default: is only available from another source
    ... ... .... shortened .... ... ...
    default: E
    default: : 
    default: Package 'php7.2-fpm' has no installation candidate
    default: E
    default: : 
    default: Package 'php7.2-cli' has no installation candidate
    default: E: Unable to locate package php7.2-common
    default: E: Couldn't find any package by regex 'php7.2-common'
    default: E: Package 'php7.2-dev' has no installation candidate
    default: E: Package 'php-imagick' has no installation candidate
    default: E: Package 'php-memcache' has no installation candidate
    default: E: Package 'php-memcached' has no installation candidate
    default: E: Package 'php-ssh2' has no installation candidate
    default: E: Package 'php-xdebug' has no installation candidate
    default: E: Package 'php7.2-bcmath' has no installation candidate
    default: E: Package 'php7.2-curl' has no installation candidate
    default: E: Package 'php7.2-gd' has no installation candidate
    default: E: Package 'php7.2-mbstring' has no installation candidate
    default: E: Package 'php7.2-mysql' has no installation candidate
    default: E: Package 'php7.2-imap' has no installation candidate
    default: E: Package 'php7.2-json' has no installation candidate
    default: E: Package 'php7.2-soap' has no installation candidate
    default: E: Package 'php7.2-xml' has no installation candidate
    default: E: Package 'php7.2-zip' has no installation candidate
    default: Main packages check and install failed, halting provision
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by tomjn** [comment]
halt the machine, destroy it, and recreate, let us know how that goes

**Comment by tomjn** [comment]
It seems some of the packages may not have been mirrored, working on it

**Comment by benedicksahagun** [comment]
Thanks @tomjn I can confirm that issue is still present even after recreating the machine.

**Comment by tomjn** [comment]
So I don't think we're going to be able to put up the missing packages, we're working on getting `develop` updated to Ubuntu 18.04 LTS Bionic. This does mean that if you've turned off database backups there will be data loss as a `vagrant destroy` will be needed

**Comment by EricRihlmann** [comment]
Here is the error message I'm getting with the latest merge #1771. This is another clean install.

```
default: E
    default: :
    default: Package 'php7.2-fpm' has no installation candidate
    default: E
    default: :
    default: Package 'php7.2-cli' has no installation candidate
    default: E
    default: :
    default: Unable to locate package php7.2-common
    default: E
    default: :
    default: Couldn't find any package by regex 'php7.2-common'
    default: E
    default: :
    default: Package 'php7.2-dev' has no installation candidate
    default: E: Package 'php-imagick' has no installation candidate
    default: E: Package 'php-memcache' has no installation candidate
    default: E: Package 'php-memcached' has no installation candidate
    default:
    default: E: Package 'php-ssh2' has no installation candidate
    default: E: Package 'php-xdebug' has no installation candidate
    default: E: Package 'php7.2-bcmath' has no installation candidate
    default: E: Package 'php7.2-curl' has no installation candidate
    default: E
    default: : Package 'php7.2-gd' has no installation candidate
    default: E: Package 'php7.2-mbstring' has no installation candidate
    default: E
    default: : Package 'php7.2-mysql' has no installation candidate
    default: E: Package 'php7.2-imap' has no installation candidate
    default: E: Package 'php7.2-json' has no installation candidate
    default: E: Package 'php7.2-soap' has no installation candidate
    default: E: Package 'php7.2-xml' has no installation candidate
    default: E: Package 'php7.2-zip' has no installation candidate
    default: Main packages check and install failed, halting provision
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
