### ISSUE TITLE
Error when adding new site: nginx: [emerg] cannot load certificate

### ISSUE THREAD

**Issue by Jotuell** [Varying-Vagrant-Vagrants/VVV#1787]
## Expected Behavior

It should clone the custom-site-template repo at the specified folder and add a new site, serving it at the given host.

## Current Behavior

The repo is cloned but the provision fails after restarting nginx with the following error:
```
default: nginx: [emerg] cannot load certificate "/vagrant/certificates/web_grics/dev.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/vagrant/certificates/web_grics/dev.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
default: nginx: configuration file /etc/nginx/nginx.conf test failed
```
I have checked the 'certificates' directory and no folder for the new site is ever created.

## Steps to Reproduce (for bugs)

1. cd into vagrant folder
2. run vagrant up
3. add new site to vvv-custom.yml file
```yml
  site_name:
    description: "Lorem ipsum dolor sit amet"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    vm_dir: /srv/www/site-name
    skip_provisioning: false
    local_dir: /home/lluis/projects/site-name
    nginx_upstream: php70
    hosts:
      - sitename.test
```
4. run vagrant reload --provision

Info:
* [Vagrant log](https://gist.github.com/Jotuell/5196b8720bb5f774cea54b8de9033c10)
* [vvv-custom.yml](https://gist.github.com/Jotuell/89d9653245f7e72ed8a2a12e1770c148)

## Your Environment

* VVV version: 2.6.0
* VVV Git Branch: master
* Vagrant version: 2.2.4
* VM Provider name: VirtualBox
* VM Provider version: 5.2.18
* Operating System and version: Linux 4.18.0-18-generic 19~18.04.1-Ubuntu SMP x86_64 GNU/Linux
