### ISSUE TITLE
Error when installing Composer dependencies

### ISSUE THREAD

**Issue by desrosj** [Varying-Vagrant-Vagrants/VVV#1799]
When provisioning a brand new environment, `composer install` fails with the following error:

```default: Install/Update WordPress-Coding-Standards, sniffs for PHP_CodeSniffer, see https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
    default: Do not run Composer as root/super user! See https://getcomposer.org/root for details
    default: Loading composer repositories with package information
Reading composer.json of automattic/vipwpcs (0.1.0)   
Reading composer.json of automattic/vipwpcs (0.2.0)
Reading composer.json of automattic/vipwpcs (0.2.1)
Reading composer.json of automattic/vipwpcs (0.2.2)
Reading composer.json of automattic/vipwpcs (0.2.3)
    default: 
    default: Reading composer.json of automattic/vipwpcs (0.2.4)
Reading composer.json of automattic/vipwpcs (0.2.5)
Reading composer.json of automattic/vipwpcs (0.3.0)
Reading composer.json of automattic/vipwpcs (0.3.1)
Reading composer.json of automattic/vipwpcs (0.4.0)
Reading composer.json of automattic/vipwpcs (1.0.0)
Reading composer.json of automattic/vipwpcs (add-js-restricted-functions.php)
Reading composer.json of automattic/vipwpcs (add/wpcs-2-compatibility)       
Reading composer.json of automattic/vipwpcs (develop)                 
Reading composer.json of automattic/vipwpcs (docs)   
Reading composer.json of automattic/vipwpcs (feature/short-echo-tags)
Reading composer.json of automattic/vipwpcs (master)                 
    default: 
                                                    
    default: Updating dependencies (including require-dev)
    default: Package operations: 8 installs, 0 updates, 0 removals
    default:   - Installing composer/installers (v1.6.0): 
    default: Downloading
    default:  (100%)
    default: Plugin installation failed, rolling back
    default:   - Removing composer/installers (v1.6.0)
    default:                                                                                   
    default:   [RuntimeException]                                                              
    default:   Could not delete /srv/provision/phpcs/vendor/composer/installers/src/Composer:  
    default:                                                                                   
    default: update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
    default: /tmp/vagrant-shell: line 742: phpcs: command not found
    default: /tmp/vagrant-shell: line 743: phpcs: command not found
    default: /tmp/vagrant-shell: line 744: phpcs: command not found```

**Comment by desrosj** [comment]
Forgot to include, I am running MacOS (10.12.6) using the `develop` branch.

**Comment by Mte90** [comment]
With a new develop environment? or with a new VVV install?

**Comment by Mte90** [comment]
Nevermind I saw that error too on my log, during a provision before start to do the provision of the various sites:
```
default: Loading composer repositories with package information
Reading composer.json of automattic/vipwpcs (0.1.0)   
Reading composer.json of automattic/vipwpcs (0.2.0)
Reading composer.json of automattic/vipwpcs (0.2.1)
Reading composer.json of automattic/vipwpcs (0.2.2)
    default: 
    default: Reading composer.json of automattic/vipwpcs (0.2.3)
    default: 
    default: Reading composer.json of automattic/vipwpcs (0.2.4)
    default: 
    default: Reading composer.json of automattic/vipwpcs (0.2.5)
    default: 
    default: Reading composer.json of automattic/vipwpcs (0.3.0)
Reading composer.json of automattic/vipwpcs (0.3.1)
Reading composer.json of automattic/vipwpcs (0.4.0)
    default: Reading composer.json of automattic/vipwpcs (1.0.0)
Reading composer.json of automattic/vipwpcs (add-js-restricted-functions.php)
    default: 
    default: Reading composer.json of automattic/vipwpcs (add/wpcs-2-compatibility)
    default:        
    default: 
    default:                                                                          
    default: Updating dependencies (including require-dev)
    default: Nothing to install or update
```
