### ISSUE TITLE
npm install fails when creating custom development template site

### ISSUE THREAD

**Issue by desrosj** [Varying-Vagrant-Vagrants/VVV#1801]
When provisioning a new site using [custom-site-template-development](https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop), I have been able to reliably reproduce this an issue where the site shows a 403 forbidden error from NGINX after provisioning completes.

This seems to be caused by the `build` folder being empty (except an empty `wp-content/mu-plugins` folder). `npm install` returns the following error:

```26489 verbose stack Error: ENOENT: no such file or directory, open '/srv/www/trunk/public_html/node_modules/anymatch/node_modules/expand-brackets/node_modules/kind-of/package.json.3433542754'
26490 verbose cwd /srv/www/trunk/public_html 
26491 verbose Linux 4.15.0-45-generic
26492 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
26493 verbose node v11.15.0
26494 verbose npm  v6.9.0
26495 error path /srv/www/trunk/public_html/node_modules/anymatch/node_modules/expand-brackets/node_modules/kind-of/package.json.3433542754
26496 error code ENOENT
26497 error errno -2
26498 error syscall open
26499 error enoent ENOENT: no such file or directory, open '/srv/www/trunk/public_html/node_modules/anymatch/node_modules/expand-brackets/node_modules/kind-of/package.json.3433542754'
26500 error enoent This is related to npm not being able to find a file.
26501 verbose exit [ -2, true ]
```

Running `npm install` and `grunt build` in the site's folder in terminal outside of the VM fixes the issue.

Running MacOS (10.12.6) using the `develop` branch.

**Comment by Mte90** [comment]
I am trying to debug this, in my case I am getting:
```
   default: npm
    default:  
    default: ERR!
    default:  
    default: path
    default:  /srv/www/wordpress-develop-test/public_html/node_modules/anymatch/node_modules/isobject/package.json.429744796
    default: npm
    default:  
    default: ERR!
    default:  
    default: code
    default:  ENOENT
    default: npm
    default:  
    default: ERR!
    default:  
    default: errno
    default:  -2
    default: npm
    default:  
    default: ERR!
    default:  
    default: syscall
    default:  open
    default: npm
    default:  
    default: ERR!
    default:  
    default: enoent
    default:  ENOENT: no such file or directory, open '/srv/www/wordpress-develop-test/public_html/node_modules/anymatch/node_modules/isobject/package.json.429744796'
    default: npm
    default:  
    default: ERR!
    default:  
    default: enoent
    default:  This is related to npm not being able to find a file.
    default: npm
    default:  
    default: ERR!
    default:  
    default: enoent

```
I think that the problem is at https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop/blob/master/provision/vvv-init.sh#L25 where we are not silencing the errors like when is on updating a previous repo.

**Comment by Mte90** [comment]
Trying the command inside the VM:
![immagine](https://user-images.githubusercontent.com/403283/57768520-15c42600-770c-11e9-8d88-47b4ee5c77e4.png)

**Comment by Mte90** [comment]
The same error is happening in previous install of develop template.
Now I am checking if it is an issue of wordpress trunk and not of VVV.

**Comment by Mte90** [comment]
It isn't a problem of WP but something that happen in VVV.
Seems like that during the install of that package npm change the folder reference for the modules.

**Comment by Mte90** [comment]
And there is a fix :-) https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop/pull/9

**Comment by tomjn** [comment]
@desrosj can you confirm this fixed the problem?

**Comment by desrosj** [comment]
This produces a new error for me:

```
default: npm
    default:  
    default: WARN
    default:  
    default: saveError
    default:  ENOENT: no such file or directory, open '/srv/www/five-oh/public_html/node_modules/package.json'
    default: npm
    default:  
    default: notice
    default:  created a lockfile as package-lock.json. You should commit this file.
    default: npm
    default:  
    default: WARN
    default:  
    default: enoent
    default:  ENOENT: no such file or directory, open '/srv/www/five-oh/public_html/node_modules/package.json'
    default: npm
    default:  
    default: WARN
    default:  node_modules No description
    default: npm
    default:  
    default: WARN
    default:  node_modules No repository field.
    default: npm
    default:  
    default: WARN
    default:  node_modules No README data
    default: npm
    default:  
    default: WARN
    default:  node_modules No license field.
```

Note: I was provisioning a single site using `vagrant provision --provision-with=`, not a new install. But I don't think that should matter.

**Comment by Mte90** [comment]
Seems another install instead of trunk, or it is a develop template too?

**Comment by kraftbj** [comment]
I'm getting
```
  default: Checked out revision 45371.
    default: npm
    default:  WARN saveError ENOENT: no such file or directory, open '/srv/www/wordpress-trunk/public_html/node_modules/package.json'
    default: npm 
    default: notice created a lockfile as package-lock.json. You should commit this file.
    default: npm WARN
    default:  enoent ENOENT: no such file or directory, open '/srv/www/wordpress-trunk/public_html/node_modules/package.json'
    default: npm
    default:  WARN node_modules No description
    default: npm WARN node_modules No repository field.
    default: npm WARN node_modules No README data
    default: npm WARN node_modules No license field.
    default: up to date in 0.478s
    default: found 0 vulnerabilities
    default: Configuring WordPress trunk...
    default: Initializing grunt... This may take a few moments.
    default: grunt-cli: The grunt command line interface (v1.3.2)
    default: Fatal error: Unable to find local grunt.
    default: 
    default: If you're seeing this message, grunt hasn't been installed locally to
    default: your project. For more information about installing and configuring grunt,
    default: please see the Getting Started guide:
    default: 
    default: https://gruntjs.com/getting-started
    default: Grunt initialized.
```
when trying to provision trunk in VVV 3.0.

I think the `--prefix` is looking for a package.json in the node_modules folder, which doesn't exist. Looks like we need to update the npm install command based on this SO answer https://stackoverflow.com/a/43704283

`npm install --prefix ./install/here ./` ?

**Comment by Mte90** [comment]
prefix parameter is to specify the node_modules folders where it is.
The npm command on provisioning is downloaded at last version.

So on my testing specifying the path on provisioning fixed the problem because if you run the command from ssh there are no problems.

**Comment by desrosj** [comment]
Switched to `master` and started fresh after 3.0 came out. and I am also now seeing what @kraftbj is seeing. 

```
default: Checked out revision 45383.
    default: npm
    default:  
    default: WARN
    default:  
    default: saveError
    default:  ENOENT: no such file or directory, open '/srv/www/trunk/public_html/node_modules/package.json'
    default: npm notice created a lockfile as package-lock.json. You should commit this file.
    default: npm WARN 
    default: enoent ENOENT: no such file or directory, open '/srv/www/trunk/public_html/node_modules/package.json'
    default: npm WARN node_modules No description
    default: npm
    default:  
    default: WARN
    default:  node_modules No repository field.
    default: npm 
    default: WARN
    default:  node_modules No README data
    default: npm
    default:  
    default: WARN
    default:  node_modules No license field.
    default: up to date in 0.383s
    default: found 0 vulnerabilities
    default: Configuring WordPress trunk...
    default: Installing WordPress trunk...
    default: Initializing grunt... This may take a few moments.
```
