### ISSUE TITLE
Vagrant up installation problem: The SSH command responded with a non-zero exit status

### ISSUE THREAD

**Issue by carlotrimarchi** [Varying-Vagrant-Vagrants/VVV#1862]
I'm trying to install VVV on a MacOs Sierra 10.12.6

When running the `vagrant up` command I get a list a error messages, the first being:

```
    default: Setting up libssl1.1:amd64 (1.1.1-1ubuntu2.1~18.04.2) ...
    default: Checking for services that may need to be restarted...
    default: done.
    default: Checking for services that may need to be restarted...
    default: done.
    default: Checking init scripts...
    default: No apport report written because the error message indicates its a followup error from a previous failure.
    default: dpkg: error processing package libssl1.1:amd64 (--configure):
    default:  installed libssl1.1:amd64 package post-installation script subprocess returned error exit status 10
    default: dpkg: dependency problems prevent configuration of libaprutil1:amd64:
    default:  libaprutil1:amd64 depends on libssl1.1 (>= 1.1.0); however:
    default:   Package libssl1.1:amd64 is not configured yet.
    default:
    default: dpkg: error processing package libaprutil1:amd64 (--configure):
    default:  dependency problems - leaving unconfigured
```
Then at the end:

```
    default: Processing was halted because there were too many errors.
    default: E
    default: :
    default: Sub-process /usr/bin/dpkg returned an error code (1)
    default: Main packages check and install failed, halting provision

The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
After this, accessing http://vvv.test and all the other urls work, but I simply get the nginx welcome page.

It might be worth mentioning that I have another vagrant session successfully running a `homestead` image.

## Your Environment

* VVV version: 3.0.0
* VVV Git Branch: master
* Vagrant version: 2.2.4
* VM Provider name: VirtualBox
* VM Provider version: 6.0
* Operating System and version: MacOs Sierra 10.12.6
