### ISSUE TITLE
Grunt related errors when provisioning

### ISSUE THREAD

**Issue by kmgalanakis** [Varying-Vagrant-Vagrants/VVV#1885]
When running `vagrant up --provision` on `develop`, I get errors related to `grunt`

```
default: Installing Grunt CLI
    default: npm
    default:  
    default: WARN
    default:  
    default: checkPermissions
    default:  Missing write access to /usr/lib/node_modules
    default: npm
    default:  
    default: ERR!
    default:  
    default: path
    default:  /usr/lib/node_modules
    default: npm
    default:  
    default: ERR!
    default:  
    default: code
    default:  EACCES
    default: npm
    default:  
    default: ERR!
    default:  
    default: errno
    default:  -13
    default: npm
    default:  
    default: ERR!
    default:  
    default: syscall
    default:  access
    default: npm
    default:  
    default: ERR!
    default:  Error: EACCES: permission denied, access '/usr/lib/node_modules'
    default: npm
    default:  
    default: ERR!
    default:   { [Error: EACCES: permission denied, access '/usr/lib/node_modules']
    default: npm
    default:  
    default: ERR!
    default:    stack:
    default: npm
    default:  
    default: ERR!
    default:     'Error: EACCES: permission denied, access \'/usr/lib/node_modules\'',
    default: npm
    default:  
    default: ERR!
    default:    errno: -13,
    default: npm
    default:  
    default: ERR!
    default:    code: 'EACCES',
    default: npm
    default:  
    default: ERR!
    default:    syscall: 'access',
    default: npm
    default:  
    default: ERR!
    default:    path: '/usr/lib/node_modules' }
    default: npm
    default:  ERR!
    default:  
    default: npm
    default:  
    default: ERR!
    default:  The operation was rejected by your operating system.
    default: npm
    default:  
    default: ERR!
    default:  It is likely you do not have the permissions to access this file as the current user
    default: npm
    default:  
    default: ERR!
    default:  
    default: npm
    default:  
    default: ERR!
    default:  If you believe this might be a permissions issue, please double-check the
    default: npm
    default:  
    default: ERR!
    default:  permissions of the file and its containing directories, or try running
    default: npm
    default:  
    default: ERR!
    default:  the command again as root/Administrator (though this is not recommended).
    default: npm
    default:  
    default: ERR!
    default:  A complete log of this run can be found in:
    default: npm
    default:  
    default: ERR!
    default:      /home/vagrant/.npm/_logs/2019-06-27T19_00_45_604Z-debug.log
    default: npm
    default:  WARN checkPermissions Missing write access to /usr/lib/node_modules
    default: npm
    default:  WARN grunt-sass@3.0.2 requires a peer of grunt@>=1 but none is installed. You must install peer dependencies yourself.
    default: npm
    default:  ERR! path /usr/lib/node_modules
    default: npm ERR! code
    default:  EACCES
    default: npm ERR! errno -13
    default: npm ERR! syscall access
    default: npm
    default:  ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
    default: npm ERR!  { [Error: EACCES: permission denied, access '/usr/lib/node_modules']
    default: npm ERR!   stack:
    default: npm ERR!    'Error: EACCES: permission denied, access \'/usr/lib/node_modules\'',
    default: npm ERR!   errno: -13,
    default: npm ERR!   code: 'EACCES',
    default: npm ERR!   syscall: 'access',
    default: npm ERR!   path: '/usr/lib/node_modules' }
    default: npm ERR! 
    default: npm ERR!
    default:  The operation was rejected by your operating system.
    default: npm ERR! It is likely you do not have the permissions to access this file as the current user
    default: npm ERR! 
    default: npm ERR! If you believe this might be a permissions issue, please double-check the
    default: npm
    default:  ERR! permissions of the file and its containing directories, or try running
    default: npm ERR! the command again as root/Administrator (though this is not recommended).
    default: 
    default: npm
    default:  ERR! A complete log of this run can be found in:
    default: npm ERR!     /home/vagrant/.npm/_logs/2019-06-27T19_00_46_533Z-debug.log
    default: npm
    default:  
    default: WARN 
    default: checkPermissions Missing write access to /usr/lib/node_modules
    default: npm
    default:  WARN grunt-cssjanus@0.5.0 requires a peer of grunt@>=1.0.4 but none is installed. You must install peer dependencies yourself.
    default: npm
    default:  ERR! path /usr/lib/node_modules
    default: npm ERR! code
    default:  EACCES
    default: npm ERR! errno -13
    default: npm ERR! syscall
    default:  access
    default: npm
    default:  ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
    default: npm ERR!  { [Error: EACCES: permission denied, access '/usr/lib/node_modules']
    default: npm 
    default: ERR!   stack:
    default: npm ERR!    'Error: EACCES: permission denied, access \'/usr/lib/node_modules\'',
    default: npm ERR!   errno: -13,
    default: npm ERR!   code: 'EACCES',
    default: npm
    default:  ERR!   syscall: 'access',
    default: npm ERR!   path: '/usr/lib/node_modules' }
    default: npm 
    default: ERR! 
    default: npm ERR! The operation was rejected by your operating system.
    default: npm ERR! It is likely you do not have the permissions to access this file as the current user
    default: npm ERR! 
    default: npm ERR! If you believe this might be a permissions issue, please double-check the
    default: npm ERR! permissions of the file and its containing directories, or try running
    default: npm ERR! the command again as root/Administrator (though this is not recommended).
    default: npm ERR! A complete log of this run can be found in:
    default: npm ERR!     /home/vagrant/.npm/_logs/2019-06-27T19_00_47_510Z-debug.log
    default: npm
    default:  
    default: WARN
    default:  
    default: checkPermissions
    default:  Missing write access to /usr/lib/node_modules
    default: npm
    default:  
    default: ERR!
    default:  
    default: path
    default:  /usr/lib/node_modules
    default: npm
    default:  
    default: ERR!
    default:  
    default: code
    default:  EACCES
    default: npm
    default:  ERR! errno -13
    default: npm ERR! syscall
    default:  access
    default: npm
    default:  ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
    default: npm ERR!  { [Error: EACCES: permission denied, access '/usr/lib/node_modules']
    default: npm ERR!   stack:
    default: npm ERR!    'Error: EACCES: permission denied, access \'/usr/lib/node_modules\'',
    default: npm ERR!   errno: -13,
    default: npm ERR!   code: 'EACCES',
    default: npm ERR!   syscall: 'access',
    default: npm ERR!   path: '/usr/lib/node_modules' }
    default: npm ERR! 
    default: npm ERR! The operation was rejected by your operating system.
    default: npm ERR! It is likely you do not have the permissions to access this file as the current user
    default: npm ERR! 
    default: npm ERR! If you believe this might be a permissions issue, please double-check the
    default: npm ERR! permissions of the file and its containing directories, or try running
    default: npm ERR! the command again as root/Administrator (though this is not recommended).
    default: npm ERR! A complete log of this run can be found in:
    default: npm
    default:  ERR!     /home/vagrant/.npm/_logs/2019-06-27T19_00_50_527Z-debug.log
```

Most probably this is related to https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1876
