### ISSUE TITLE
MariaDB error after upgrade box

### ISSUE THREAD

**Issue by mbootsman** [Varying-Vagrant-Vagrants/VVV#1907]
Hi I have updated my box from ubuntu 14 -> ubuntu 18 with these commands:
`vagrant destroy`
`vagrant up --provision`

When the machine launches, I get this error message:
`default: Post Vagrant up script`
    `default: Restarting Nginx and MySQL`
    `default: Job for mariadb.service failed because the control process exited with error code.`
   ` default: See "systemctl status mariadb.service" and "journalctl -xe" for details.`

When executing `systemctl status mariadb.service` in `vagrant ssh` I get:
```
$ systemctl status mariadb.service
● mariadb.service - MariaDB 10.3.16 database server
   Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/mariadb.service.d
           └─migrated-from-my.cnf-settings.conf
   Active: failed (Result: exit-code) since Wed 2019-07-17 11:45:30 UTC; 3min 34s ago
     Docs: man:mysqld(8)
           https://mariadb.com/kb/en/library/systemd/
  Process: 4453 ExecStart=/usr/sbin/mysqld $MYSQLD_OPTS $_WSREP_NEW_CLUSTER $_WSREP_START_POSITION (code=exited, status=1/FAILURE)
  Process: 4306 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`/usr/bin/galera_recovery`; [ $? -eq 0 ]   && systemctl set-environment _WSREP_START_POSITION=$VAR || exit 1 
  Process: 4304 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
  Process: 4293 ExecStartPre=/usr/bin/install -m 755 -o mysql -g root -d /var/run/mysqld (code=exited, status=0/SUCCESS)
 Main PID: 4453 (code=exited, status=1/FAILURE)
```
What do I need to do to get the DB up again?

**Comment by tomjn** [comment]
Disable the shared database folder, you can find the relevant flag in
vvv-config.yml just copy it to vvv-custom.yml and reprovision

**Comment by mbootsman** [comment]
Tom, thanks for your fast reply.
This is my vvv-config.yml
```
---


# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

#
# IMPORTANT, if you change this file, you have to reprovision,  no exceptions
# Do this by running either this command:
# vagrant reload --provision
# 
# Or, if your machine is already turned on:
# vagrant provision
#

# These are your websites, and their names map on to the folders they're
# located in. See the docs for how to define these, and what all the keys
# and options are
sites:

  # latest version of WordPress, can be used for client work and testing
  wordpress-one:
    skip_provisioning: false
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - one.wordpress.test

  wordpress-two:
    skip_provisioning: false
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - two.wordpress.test

  #mysite:
  #  description: "My website"
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    - mysite.com

  # The wordpress-develop configuration is useful for contributing to WordPress Core.
  # It uses the built WP to serve the site
  wordpress-trunk:
    skip_provisioning: true # provisioning this one takes longer, so it's disabled by default
    description: "An svn based WP Core trunk dev setup, useful for contributor days, Trac tickets, patches"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - trunk.wordpress.test

  # The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://my-example-site.test.
  # Remember, whitespace is significant! Tabs and spaces mean different things
  #example-site:
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    - my-example-site.test

  # The following commented out site configuration will create a environment useful
  # for contributions to the WordPress meta team, .e.g WordCamps, .org, etc:
  wordpress-meta-environment:
    skip_provisioning: true # disabled by default, this takes a long time to provision
    repo: https://github.com/WordPress/meta-environment.git


# Utilities are system level items rather than sites, that install tools or packages
# the core utilities install tools such as phpmyadmin
utilities:
  core: # The core VVV utility
    - memcached-admin # Object cache management
    - opcache-status # opcache management
    - phpmyadmin # Web based database client
    - webgrind # PHP Debugging
    - tls-ca # SSL/TLS certificates
    - mongodb # needed for Tideways/XHGui
    - tideways # PHP profiling tool, also installs xhgui
    #- php56
    #- php70
    #- php71
    #- php72
    #- php73

# vm_config controls how Vagrant provisions the virtual machine, and can be used to
# increase the memory given to VVV and the number of CPU cores. 
# It can also be used to override the default provider being used within Vagrant.

vm_config:
  # For WP core development we recommend at least 2GB ( 2048 ),
  # If you have 4GB of RAM, lower this to 768MB or you may encounter issues
  memory: 2048
  # CPU cores:
  cores: 2

  # this tells VVV to use the prebuilt box copied from the USB drive at contributor days
  # once set to false, do not change back to true, and reprovision
  # wordcamp_contributor_day_box: false

  # Due to a limitation within Vagrant, the specified provider is only respected on a clean `vagrant up`
  # as Vagrant currently restricts you to one provider per machine
  # https://www.vagrantup.com/docs/providers/basic_usage.html#vagrant-up
  # provider: vmware_workstation

# General VVV options
general:
  # Backup the databases to the database/backups subfolder on halt/suspend/destroy, set to false to disable
  db_backup: true
  # Import the databases if they're missing from backups
  db_restore: true
```

What do I need to change?

**Comment by tomjn** [comment]
Is that your `vvv-config.yml` or your `vvv-custom.yml`? The default `vvv-config.yml` should look like this:

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/vvv-config.yml

and has this:

```yml
  # set to true to use a synced shared folder for MariaDB database storage 
  db_share_type: false
```

**Comment by mbootsman** [comment]
Hmm. I switched to the `develop` branch.
did a `git fetch --all`, ` git reset --hard origin/develop` and tried `vagrant up --provision`

I get this error message in de startup log (the last lines)

```
default:  Main PID: 6324 (code=exited, status=1/FAILURE)
    default:    Status: "MariaDB server is down"
    default: Jul 17 18:09:50 vvv mysqld[6324]: 2019-07-17 18:09:50 0 [ERROR] InnoDB: The innodb_system data file 'ibdata1' must be writable
    default: Jul 17 18:09:50 vvv mysqld[6324]: 2019-07-17 18:09:50 0 [ERROR] InnoDB: The innodb_system data file 'ibdata1' must be writable
    default: Jul 17 18:09:50 vvv mysqld[6324]: 2019-07-17 18:09:50 0 [ERROR] Plugin 'InnoDB' init function returned error.
    default: Jul 17 18:09:50 vvv mysqld[6324]: 2019-07-17 18:09:50 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
    default: Jul 17 18:09:50 vvv mysqld[6324]: 2019-07-17 18:09:50 0 [Note] Plugin 'FEEDBACK' is disabled.
    default: Jul 17 18:09:50 vvv mysqld[6324]: 2019-07-17 18:09:50 0 [ERROR] Unknown/unsupported storage engine: InnoDB
    default: Jul 17 18:09:50 vvv mysqld[6324]: 2019-07-17 18:09:50 0 [ERROR] Aborting
    default: Jul 17 18:09:50 vvv systemd[1]: mariadb.service: Main process exited, code=exited, status=1/FAILURE
    default: Jul 17 18:09:50 vvv systemd[1]: mariadb.service: Failed with result 'exit-code'.
    default: Jul 17 18:09:50 vvv systemd[1]: Failed to start MariaDB 10.3.16 database server.
    default: dpkg: error processing package mariadb-server-10.3 (--configure):
    default:  installed mariadb-server-10.3 package post-installation script subprocess returned error exit status 1
    default: dpkg: dependency problems prevent configuration of mariadb-server:
    default: 
    default:  mariadb-server depends on mariadb-server-10.3 (>= 1:10.3.16+maria~bionic); however:
    default:   Package mariadb-server-10.3 is not configured yet.
    default: 
    default: dpkg: error processing package mariadb-server (--configure):
    default:  dependency problems - leaving unconfigured
    default: No apport report written because the error message indicates its a followup error from a previous failure.
    default: Errors were encountered while processing:
    default:  mariadb-server-10.3
    default:  mariadb-server
    default: E
    default: : 
    default: Sub-process /usr/bin/dpkg returned an error code (1)
    default: Installing apt-get packages returned a failure code, cleaning up apt caches then exiting
    default: Main packages check and install failed, halting provision
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.


```
