### ISSUE TITLE
vvv.test/phpinfo shows wrong PHP version?

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/VVV#1908]
I've set up the PHP version in the utilities to PHP 7.3

```yaml
utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind
    - trusted-hosts
    - tls-ca
    - php73
```

And I reprovisioned the vvv, and ssh-ed into it. When I typed `php -v` I got the correct version:

```bash
PHP 7.3.7-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Jul 10 2019 06:54:46) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.7-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.1, Copyright (c) 2002-2019, by Derick Rethans
```

When I go to either `https://vvv.test/phpinfo/` or either when I create a .php file with `phpinfo()` in the project and go to it, I get PHP 7.2 as a result

<img width="966" alt="phpinfo-vvv" src="https://user-images.githubusercontent.com/8638515/61527439-b8569900-aa1c-11e9-81e6-5acebfa7b257.png">

Also, the site health in WordPress says it's running on PHP 7.2 🤷‍♂ 

## Your Environment

* VVV version: 3.1.0
* VVV Git Branch: develop
* Vagrant version: 2.2.4
* VM Provider name: VirtualBox
* VM Provider version: 6.0.8r130520
* Operating System and version: MacOS Mojave 10.14.5
