### ISSUE TITLE
VirtualBox error - Stderr: VBoxManage.exe: error: The configuration constructor in main failed due to a COM error.

### ISSUE THREAD

**Issue by abrightclearweb** [Varying-Vagrant-Vagrants/VVV#1938]
## What was The Command Used To Provision?
`
vagrant up --provision`

I followed the Thoroughly Updating VVV instructions here: `https://varyingvagrantvagrants.org/docs/en-US/installation/keeping-up-to-date/`

## What Kind of VVV Provision Was This?

This was an attempt to upgrade to a new version of VVV

## Logs/What Broke?

```
C:\Users\Asus\vagrant-local>vagrant up --provision
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.1.1
-git::master

Platform:   platform-mingw32 windows HasWinAdminPriv vagrant-hostsupdater NoColour shared_db_folder_disabled
Vagrant:    v2.2.5,     VirtualBox: v6.0.10r132072
VVV Path:   "C:/Users/Asus/vagrant-local"

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "20a5c4cf-b1c5-47ae-a0a7-4801cf73a90b", "--type", "headless"]

Stderr: VBoxManage.exe: error: The configuration constructor in main failed due to a COM error. Check the release log of the VM for further details. (VERR_MAIN_CONFIG_CONSTRUCTOR_COM_ERROR)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
```

If I try to start the VM in VirtualBox, I get this: 
```
The virtual machine 'vagrant-local_1b36869d1c2' has terminated unexpectedly during startup with exit code 1 (0x1). More details may be available in 'C:\Users\Asus\VirtualBox VMs\vagrant-local_1b36869d1c2\Logs\VBoxHardening.log'.

Result Code: | E_FAIL (0x80004005)
-- | --
Component: | MachineWrap
Interface: | IMachine {5047460a-265d-4538-b23e-ddba5fb84976}


```
[VBoxHardening.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/3566539/VBoxHardening.log)

Also, your `vvv-custom.yml` would be super handy -->

---

```
# IMPORTANT !!!!!!!!!
# Copy this file to vvv-custom.yml so your changes don't get overwritten when you update


# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

#
# IMPORTANT, if you change this file, you have to reprovision,  no exceptions
# vagrant reload --provision
#

# These are your websites, and their names map on to the folders they're
# located in. See the docs for how to define these, and what all the keys
# and options are
sites:
  # The wordpress-default configuration provides an installation of the
  # latest version of WordPress.
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - local.wordpress.test

  # The wordpress-develop configuration is useful for contributing to WordPress.
  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - src.wordpress-develop.test
      - build.wordpress-develop.test

  # The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://my-example-site.dev.
  # Remember, whitespace is significant! Tabs and spaces mean different things

  #example-site:
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    - my-example-site.test

  # The following commented out site configuration will create a environment useful
  # for contributions to the WordPress meta team:
  
  #wordpress-meta-environment:
  #  repo: https://github.com/WordPress/meta-environment.git


# Utilities are system level items rather than sites, that install tools or packages
# the core utilities install tools such as phpmyadmin
utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind
    - trusted-hosts
    - tls-ca

# vm_config controls how Vagrant provisions the virtual machine, and can be used to
# increase the memory given to VVV and the number of CPU cores. For WP core development
# we recommend at least 2GB ( 2048 )
# It can also be used to override the default provider being used within Vagrant.
# Due to a limitation within Vagrant, the specified provider is only respected on a clean `vagrant up`
# as Vagrant currently restricts you to one provider per machine
# https://www.vagrantup.com/docs/providers/basic_usage.html#vagrant-up
vm_config:
  memory: 2048
  cores: 1
  # provider: vmware_workstation)

```

## Possible Solution

No clue, but I have had a similar error with VirtualBox recently when using Local by Flywheel. See this thread: 
[https://localbyflywheel.com/community/t/local-machine-wont-start-various-errors/13778](https://localbyflywheel.com/community/t/local-machine-wont-start-various-errors/13778)

## Steps to Reproduce (for bugs)

See above.

## Your Environment

Operating System: Windows 10 64-bit
8 GB RAM
VirtualBox 6.0.1.0
Vagrant 2.2.5
