### ISSUE TITLE
NET::ERR_CERT_REVOKED on newly created vagrant

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/VVV#1979]
## Expected Behavior
I should be able to log into my site

## Current Behavior
I cannot log into my site

## Steps to Reproduce (for bugs)
Destroy the vagrant and recreate new one.
Add certificates into the keychain Access
Try to go to your custom site
Get `NET::ERR_CERT_REVOKED` error 

```bash
Issuer: VVV INTERNAL CA
Expires on: 21 Oct 2029
Current date: 24 Oct 2019
PEM encoded chain:
```

The certificates have trust all enabled in keychain access.

## Your Environment
```
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.1.1-git::develop

Platform: platform-darwin13.4.0 shell:/bin/zsh vagrant-hostsupdater shared_db_folder_disabled , VVV Path: "/Users/infinum-denis/vagrant-local"
Vagrant: v2.2.5, VirtualBox: vN/A
```
MacOS: Catalina 10.15 (19A602)
Virtualbox: 6.0.14

The site works on `http` on firefox (with a notice about security). 

This all started when I updated to Catalina...

**Comment by Mte90** [comment]
Are you sure that the `tls-ca` is present in your `vvv-config` https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/vvv-config.yml#L94

**Comment by dingo-d** [comment]
Yup, my `custom.yml` looks like this:

```yml
# Utilities are system level items rather than sites, that install tools or packages
# the core utilities install tools such as phpmyadmin
utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind
    - trusted-hosts
    - tls-ca
    - php73
  browscap:
    - browscap
  redis:
    - redis
utility-sources:
  browscap: https://github.com/dingo-d/browscap-vvv-utility
  redis: https://github.com/dingo-d/redis-vvv-utility

general:
  db_share_type: false

vm_config:
  cores: 4
  memory: 2048
```
