### ISSUE TITLE
https://vvv.test Working on FIrefox but not working in Chrome

### ISSUE THREAD

**Issue by debabratakarfa** [Varying-Vagrant-Vagrants/VVV#2013]
https://vvv.test - When I try to access from Google chrome this error,

> Your connection is not private
Attackers might be trying to steal your information from vvv.test (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_REVOKED

> Help improve Chrome security by sending URLs of some pages that you visit, limited system information and some page content to Google. Privacy Policy
vvv.test normally uses encryption to protect your information. When Google Chrome tried to connect to vvv.test this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be vvv.test, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

> You cannot visit vvv.test right now because its certificate has been revoked. Network errors and attacks are usually temporary, so this page will probably work later.

But it working fine with Firefox.

I follow instructions from this https://varyingvagrantvagrants.org/docs/en-US/references/https/trusting-ca/

**Comment by debabratakarfa** [comment]
Same behavior in Microsoft Edge too, I think any browser using Keychain certificates not working.

**Comment by Mte90** [comment]
Seems a problems with certificates, did you followed the instructions for windows 10?

**Comment by tomjn** [comment]
Didn’t we have an issue recently with this exact issue that got resolved? I
don’t know how you managed to revoke the certificate as that isn’t VVV
itself would do, but destroy the certificates folder, reprovision, and
re-follow the steps

**Comment by tomjn** [comment]
I believe this is the cause:

https://stackoverflow.com/questions/34364459/neterr-cert-revoked-in-chrome-when-the-certificate-is-not-actually-revoked

> The first part of the question has been answered below. The reason why the site stopped working recently is b/c Google decided to distrust the “Class 3 Public Primary CA” root certificate, as explained here: https://googleonlinesecurity.blogspot.ca/2015/12/proactive-measures-in-digital.html

> 
> and here: https://code.google.com/p/chromium/issues/detail?id=570892
> 
> Since the decision was reversed for now, the problem can be fixed by getting the latest CRLSet in chrome://components/


the fix:

> First, the good news is the change has been temporarily reverted, and you should find access restored. You can force an update by going to chrome://components and under CRLSet, clicking "Update". You should have version 2698 or later to fix this issue.

**Comment by debabratakarfa** [comment]
https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2013#issuecomment-560368460

I did but not worked.

**Comment by debabratakarfa** [comment]
<img width="858" alt="Screenshot 2019-12-05 13 54 53" src="https://user-images.githubusercontent.com/2614495/70217331-f4d62780-1766-11ea-9fbc-addd51fb9937.png">

I wish if the ticket reopens again.

**Comment by debabratakarfa** [comment]
config
```
  wordpress-two:
    skip_provisioning: false
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      locale: it_IT
      delete_default_plugins: true
      install_plugins:
        - query-monitor
    hosts:
      - two.wordpress.test
```

It choosing name rather than the hosts
