### ISSUE TITLE
Hyper-V and hosts... only adds ip and vvv (neither test nor wordpress)

### ISSUE THREAD

**Issue by Suzamax** [Varying-Vagrant-Vagrants/VVV#2026]
The expected behavior is to add lines such as:
```
172.17.253.30 vvv.test
172.17.253.30 two.wordpress.test
172.17.253.30 one.wordpress.test
```

But the Vagrant host writes only this:
```
172.17.253.30	vvv	# VAGRANT: 011921ab163d6f804df72b570e7734eb (default) / 42256961-c544-49ab-b2c6-25ed0094720a
```

Have I done something wrong or is it a bug?

**Comment by tomjn** [comment]
Hello! Can we see a copy of your config file? It's impossible to debug this without it, a copy of the provisioner output would also save a lot of time ( it avoids me asking you 10-20 questions if i can just see what it says in the terminal/console )

**Comment by Suzamax** [comment]
Of course! It's almost default.

Also, I had trouble while starting the VVV for the first time (`vagrant up --provider hyperv` and `vagrant up --provision`), I'm going to try another time with another VVV, and see if the problem persists.

Config file below:

```yaml
---
sites:
  wordpress-one:
    skip_provisioning: false
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - one.wordpress.test
    custom:
      wpconfig_constants:
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true # To disable in WP 5.2 the FER mode

  wordpress-two:
    skip_provisioning: false
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      delete_default_plugins: true
      install_plugins:
        - query-monitor
    hosts:
      - two.wordpress.test

  wordpress-trunk:
    skip_provisioning: true # provisioning this one takes longer, so it's disabled by default
    description: "An svn based WP Core trunk dev setup, useful for contributor days, Trac tickets, patches"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - trunk.wordpress.test

  wordpress-meta-environment:
    skip_provisioning: true # disabled by default, this takes a long time to provision
    description: "An environment useful for contributions to the WordPress meta team."
    repo: https://github.com/WordPress/meta-environment.git
    hosts:
      - wp-meta.test
    custom:
      provision_site:
        "buddypressorg.test": true
        "jobs.wordpressnet.test": true
        "wordcamp.test": true
        "wordpressorg.test": true
        "wordpresstv.test": true

utilities:
  core: # The core VVV utility
    - tls-ca # HTTPS SSL/TLS certificates
    - phpmyadmin # Web based database client

vm_config:
  memory: 2048
  # CPU cores:
  cores: 2
  provider: hyperv

general:
  db_backup: true
  db_restore: true
  db_share_type: false

vagrant-plugins:
  disksize: 10GB # requires the disk size vagrant plugin

```
