### ISSUE TITLE
db_share_type true doesn't work

### ISSUE THREAD

**Issue by janw-me** [Varying-Vagrant-Vagrants/VVV#2032]
## Expected Behavior
I have a lot of big DB's so I want to have them on a shared drive. Or else vvv will run out of disk space.

## Steps to Reproduce (for bugs)
Only value I toggle is `db_share_type`
When it is true it givens an error on mysl.

 1. `vagrant halt && destroy -f `
 2. Put `db_share_type` to `true`
 3. `vagrant up`

## Your Environment

```
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.2.0-git::HEAD

Platform: platform-linux-gnu shell:/bin/bash systemd vagrant-hostsupdater CaseSensitiveFS shared_db_folder_enabled , VVV Path: "/home/janw/Webdev/vagrant-local"
Vagrant: v2.2.4, VirtualBox: v6.0.6
```
The host is Ubuntu 19.04

## Logs

Attached out put of running  [vagrant UP.txt](https://github.com/Varying-Vagrant-Vagrants/VVV/files/3966781/vagrant.UP.txt) with `db_share_type: true`

config.yml
```
sites:

  janw:
    # repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template
    hosts:
      - janw.test
      - www.janw.test
utilities:
  core: # The core VVV utility
    - memcached-admin # Object cache management
    - opcache-status # opcache management
    - phpmyadmin # Web based database client
    - webgrind # PHP Debugging
    - trusted-hosts # GitHub etc
    - tls-ca # SSL/TLS certificates
    - mongodb # needed for Tideways/XHGui
    - tideways # PHP profiling tool, also installs xhgui
    - php56
    - php72
    - php73


vm_config:
  memory: 4096
  cores: 2

general:
  db_backup: true
  db_restore: false
  db_share_type: true
```
