### ISSUE TITLE
Failed Reprovisioning Errors in nginx.conf and git not found

### ISSUE THREAD

**Issue by cogdog** [Varying-Vagrant-Vagrants/VVV#2044]
Have used VVV for years on OSX, but now my environment is hosed! 

## What was The Command Used To Provision

First time I tried

```shell
vagrant reload --provision
```

that ultimately failed with

```
 nginx: [emerg] unexpected "{" in /etc/nginx/custom-sites/vvv-auto-wordpress-default-provision-43ccb1d415c7a942e55797dff3e109bd.conf:17
```
(full log below)

Failing to find a fix for this error I opted for the *Starting From Fresh* instructions here, all went ok until the final

```shell
vagrant up --provision
```

With the second log below of more errors than before. I'm pretty lost on this, and don't mind starting completely over.

## What Kind of VVV Provision Was This

This was a reprovision of an already working VVV

## Logs/What Broke

Provision Log Fail (1) https://gist.github.com/cogdog/107a02f6dac2e15b2e4e1306d7e17d94
Provision Log Fail (2) https://gist.github.com/cogdog/ab8117cf21d9fbe57c8df6336ac63c26

```yaml
---

# IMPORTANT !!!!!!!!!
# Copy this file to vvv-custom.yml so your changes don't get overwritten when you update


# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

#
# IMPORTANT, if you change this file, you have to reprovision,  no exceptions
# vagrant reload --provision
#

# These are your websites, and their names map on to the folders they're
# located in. See the docs for how to define these, and what all the keys
# and options are
sites:
  # The wordpress-default configuration provides an installation of the
  # latest version of WordPress.
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - local.wordpress.test

  # The wordpress-develop configuration is useful for contributing to WordPress.
  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
    hosts:
      - src.wordpress-develop.test
      - build.wordpress-develop.test

  # The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://my-example-site.dev.
  # Remember, whitespace is significant! Tabs and spaces mean different things

  splot:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - splot.test

  bank:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - bank.test

  toolkit:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - toolkit.test
      

#  corrleader:
#    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
#    hosts:
#      - corrleader.test

 #  constellation:
 #   repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
 #   hosts:
 #     - constellation.test
      
 # twu:
 #   repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
 #   hosts:
 #     - twu.test

  # The following commented out site configuration will create a environment useful
  # for contributions to the WordPress meta team:
  
  #wordpress-meta-environment:
  #  repo: https://github.com/WordPress/meta-environment.git


# Utilities are system level items rather than sites, that install tools or packages
# the core utilities install tools such as phpmyadmin
utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind
    - trusted-hosts
    - tls-ca

# vm_config controls how Vagrant provisions the virtual machine, and can be used to
# increase the memory given to VVV and the number of CPU cores. For WP core development
# we recommend at least 2GB ( 2048 )
# It can also be used to override the default provider being used within Vagrant.
# Due to a limitation within Vagrant, the specified provider is only respected on a clean `vagrant up`
# as Vagrant currently restricts you to one provider per machine
# https://www.vagrantup.com/docs/providers/basic_usage.html#vagrant-up
vm_config:
  memory: 2048
  cores: 1
  # provider: vmware_workstation

```

## Your Environment

```
  __     ___     ___     __  ____    
  \ \   / \ \   / \ \   / / |___ \   
   \ \ / / \ \ / / \ \ / /    __) |  
    \ V /   \ V /   \ V /    / __/   
     \_/     \_/     \_/    |_____|  

  Varying Vagrant Vagrants v2.1.0-master
  Docs:       https://varyingvagrantvagrants.org/
  Contribute: https://github.com/varying-vagrant-vagrants/vvv
  Dashboard:  http://vvv.test
```
