### ISSUE TITLE
Delayed 502 Gateway Error 

### ISSUE THREAD

**Issue by shanebp** [Varying-Vagrant-Vagrants/VVV#2062]
## What was The Command Used To Provision
vagrant reload --provision

```vagrant up --provision
```

## What Kind of VVV Provision Was This

This was a reprovision of an already working VVV

## Logs/What Broke

Provision Log
https://gist.github.com/shanebp/4156dcf2a0fe64d0a9bb456e762b1698

Things have been working great for months. 
I have started and stopped Vagrant many times.
But today I had to reboot my laptop...
Then I restarted vagrant vagrant up --provision. 

Then, I can browse to the localhost dashboard vvv.test and then to a local WordPress site. 
But I start getting 502 Bad Gateway errors after about 10 seconds.

I've tried starting and stopping vagrant. 
Also tried destroying the `default` machine and rebuilding it. 
The result is always the same, in any browser:  
The 502 Bad Gateway error starts appearing after about 10 seconds. 

This problem just started. Any suggestions welcomed.

```yaml

    new-wcvsite:
  # repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    description: "WC Vendors"
    skip_provisioning: false
    hosts:
      - woowcv.test

  wordpress-default:
  # repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
    description: "WP Test - BuddyPress"
    skip_provisioning: false
    hosts:
      - local.wordpress.test


# Utilities are system level items rather than sites, that install tools or packages
# the core utilities install tools such as phpmyadmin
utilities:
  core: # The core VVV utility
    - memcached-admin # Object cache management
    - opcache-status # opcache management
    - phpmyadmin # Web based database client
    - webgrind # PHP Debugging
    - trusted-hosts # GitHub etc
    - tls-ca # SSL/TLS certificates
    #- php56
    #- php70
    #- php71
    #- php72
    #- php73

# vm_config controls how Vagrant provisions the virtual machine, and can be used to
# increase the memory given to VVV and the number of CPU cores. For WP core development
# we recommend at least 2GB ( 2048 )
# It can also be used to override the default provider being used within Vagrant.
# Due to a limitation within Vagrant, the specified provider is only respected on a clean `vagrant up`
# as Vagrant currently restricts you to one provider per machine
# https://www.vagrantup.com/docs/providers/basic_usage.html#vagrant-up
vm_config:
  memory: 2048
  cores: 2
  # provider: vmware_workstation

# General VVV options
general:
  # Backup the databases to the database/backups subfolder on halt/suspend/destroy, set to false to disable
  db_backup: true
  # Import the databases if they're missing from backups
  db_restore: true

```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

https://gist.github.com/shanebp/4156dcf2a0fe64d0a9bb456e762b1698

## Your Environment

Operating System: Windows 10 64 bit using current versions of Virtual Box and Vagrant
