### ISSUE TITLE
Error with git and branch

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#2087]
This config:

```
  wordpress-trunk:
    branch:  mte90/2033
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - trunk.wordpress.test
```

That generate this log

```
default:  * Running provisioner for site wordpress-trunk
    default:  * Updating wordpress-trunk in /srv/www/wordpress-trunk...
    default: fatal: ambiguous argument 'origin/mte90/2033': unknown revision or path not in the working tree.
    default: Use '--' to separate paths from revisions, like this:
    default: 'git <command> [<revision>...] -- [<file>...]'
    default:  * Searching for a site template provisioner, vvv-init.sh
```

As I can see the switch is happening anyway but maybe https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision-site.sh#L116 we can add a `git fetch --all` so all the branches are stored locally and the error should not happen again.
