### ISSUE TITLE
VVV slow locally but powerful machine

### ISSUE THREAD

**Issue by SimonMayerhofer** [Varying-Vagrant-Vagrants/VVV#2089]
Hey,

I'm having trouble with the speed since I use VVV. It takes 4s to load the exact same WordPress dashboard on my local machine with VVV and 1s on our staging and production server. So locally it's about 4x slower than on the server. That slows down my develop time a lot.

<details>
 <summary>config.yml</summary>

```

---
sites:
  example:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    nginx_upstream: php73
    hosts:
      - example.test
      - www.example.test
    custom:
      wpconfig_constants:
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DEBUG_DISPLAY: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true
        DISALLOW_FILE_EDIT: true
        FORCE_SSL_ADMIN: true
        CORE_UPGRADE_SKIP_NEW_BUNDLED: true
        WP_AUTO_UPDATE_CORE: 'minor'
        FP_ACF_SAVE_JSON: true

# Utilities are system level items rather than sites, that install tools or packages
# the core utilities install tools such as phpmyadmin
utilities:
  core: # The core VVV utility
    - memcached-admin # Object cache management
    - opcache-status # opcache management
    - phpmyadmin # Web based database client
    - webgrind # PHP Debugging
    - trusted-hosts # GitHub etc
    - tls-ca # SSL
    - php # Install all the php utilities available automatically
    #- php56
    #- php70
    #- php71
    # - php72
    # - php73
    #- php74

# vm_config controls how Vagrant provisions the virtual machine, and can be used to
# increase the memory given to VVV and the number of CPU cores. For WP core development
# we recommend at least 2GB ( 2048 )
# It can also be used to override the default provider being used within Vagrant.
# Due to a limitation within Vagrant, the specified provider is only respected on a clean `vagrant up`
# as Vagrant currently restricts you to one provider per machine
# https://www.vagrantup.com/docs/providers/basic_usage.html#vagrant-up
vm_config:
  memory: 8192
  cores: 3
  # provider: vmware_workstation


```
</details>

I'm working on a MacBook Pro (16-inch, 2019) w/ 2,6 GHz 6-Core Intel Core i7, 32 GB 2667 MHz DDR4, AMD Radeon Pro 5500M 8 GB.

```
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.3.0-git::develop

Platform: platform-darwin13.4.0 shell:/bin/zsh vagrant-hostsupdater shared_db_folder_disabled , VVV Path: "/Users/simon/vvv"
Vagrant: v2.2.6, VirtualBox: v6.0.14r133895
```

Do you have an idea what's the reason and how to fix that? Thanks for any help.
