### ISSUE TITLE
Issue with Connecting to Herrbischoff.com Apt Mirror

### ISSUE THREAD

**Issue by debabratakarfa** [Varying-Vagrant-Vagrants/VVV#2092]
```
default:   Could not connect to mirror.herrbischoff.com:443 (84.46.26.196), connection timed out
    default: Err:23 https://mirror.herrbischoff.com/mariadb/repo/10.3/ubuntu bionic/main amd64 mariadb-server all 1:10.3.22+maria~bionic
    default:   Unable to connect to mirror.herrbischoff.com:https:
    default: Err:24 https://mirror.herrbischoff.com/mariadb/repo/10.3/ubuntu bionic/main amd64 libmariadb3 amd64 1:10.3.22+maria~bionic
    default:   Unable to connect to mirror.herrbischoff.com:https:
    default: Err:25 https://mirror.herrbischoff.com/mariadb/repo/10.3/ubuntu bionic/main amd64 mariadb-client-core-10.3 amd64 1:10.3.22+maria~bionic
    default:   Unable to connect to mirror.herrbischoff.com:https:
    default: Err:26 https://mirror.herrbischoff.com/mariadb/repo/10.3/ubuntu bionic/main amd64 mariadb-client-10.3 amd64 1:10.3.22+maria~bionic
    default:   Unable to connect to mirror.herrbischoff.com:https:
    default: Err:27 https://mirror.herrbischoff.com/mariadb/repo/10.3/ubuntu bionic/main amd64 mariadb-server-core-10.3 amd64 1:10.3.22+maria~bionic
    default:   Unable to connect to mirror.herrbischoff.com:https:
    default: Err:28 https://mirror.herrbischoff.com/mariadb/repo/10.3/ubuntu bionic/main amd64 mariadb-server-10.3 amd64 1:10.3.22+maria~bionic
    default:   Unable to connect to mirror.herrbischoff.com:https:
    default: Fetched 14.3 MB in 30s (473 kB/s)
    default: Unable to correct missing packages.
    default: E: Failed to fetch https://mirror.herrbischoff.com/mariadb/repo/10.3/ubuntu/pool/main/m/mariadb-10.3/mariadb-common_10.3.22+maria~bionic_all.deb  Could not connect to mirror.herrbischoff.com:443 (84.46.26.196), connection timed out
    default: E: Failed to fetch https://mirror.herrbischoff.com/mariadb/repo/10.3/ubuntu/pool/main/m/mariadb-10.3/mariadb-server_10.3.22+maria~bionic_all.deb  Unable to connect to mirror.herrbischoff.com:https:
    default: E: Failed to fetch https://mirror.herrbischoff.com/mariadb/repo/10.3/ubuntu/pool/main/m/mariadb-10.3/libmariadb3_10.3.22+maria~bionic_amd64.deb  Unable to connect to mirror.herrbischoff.com:https:
    default: E: Failed to fetch https://mirror.herrbischoff.com/mariadb/repo/10.3/ubuntu/pool/main/m/mariadb-10.3/mariadb-client-core-10.3_10.3.22+maria~bionic_amd64.deb  Unable to connect to mirror.herrbischoff.com:https:
    default: E: Failed to fetch https://mirror.herrbischoff.com/mariadb/repo/10.3/ubuntu/pool/main/m/mariadb-10.3/mariadb-client-10.3_10.3.22+maria~bionic_amd64.deb  Unable to connect to mirror.herrbischoff.com:https:
    default: E: Failed to fetch https://mirror.herrbischoff.com/mariadb/repo/10.3/ubuntu/pool/main/m/mariadb-10.3/mariadb-server-core-10.3_10.3.22+maria~bionic_amd64.deb  Unable to connect to mirror.herrbischoff.com:https:
    default: E: Failed to fetch https://mirror.herrbischoff.com/mariadb/repo/10.3/ubuntu/pool/main/m/mariadb-10.3/mariadb-server-10.3_10.3.22+maria~bionic_amd64.deb  Unable to connect to mirror.herrbischoff.com:https:
    default: E: Aborting install.
    default:  * Installing apt-get packages returned a failure code, cleaning up apt caches then exiting
```

## What was The Command Used To Provision

```shell
vagrant up --provision
```

## What Kind of VVV Provision Was This

No Fresh Install, it was running

## Logs/What Broke

```yaml
---
# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

#
# IMPORTANT, if you change this file, you have to reprovision,  no exceptions
# Do this by running either this command:
# vagrant reload --provision

# Or, if your machine is already turned on:
# vagrant provision
#

# These are your websites, and their names map on to the folders they're
# located in. See the docs for how to define these, and what all the keys
# and options are
sites:
  # latest version of WordPress, can be used for client work and testing
  # Check the readme at https://github.com/Varying-Vagrant-Vagrants/custom-site-template
  wordpress-one:
    skip_provisioning: false
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - one.wordpress.test
    custom:
      wpconfig_constants:
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true # To disable in WP 5.2 the FER mode

  wordpress-two:
    skip_provisioning: false
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      # locale: it_IT
      delete_default_plugins: true
      install_plugins:
        - query-monitor
    hosts:
      - two.wordpress.test

  # The wordpress-develop configuration is useful for contributing to WordPress Core.
  # It uses the built WP to serve the site
  wordpress-trunk:
    skip_provisioning: true # provisioning this one takes longer, so it's disabled by default
    description: "An svn based WP Core trunk dev setup, useful for contributor days, Trac tickets, patches"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - trunk.wordpress.test

  # The following commented out site configuration will create a environment useful
  # for contributions to the WordPress meta team, .e.g WordCamps, .org, etc:
  wordpress-meta-environment:
    skip_provisioning: true # disabled by default, this takes a long time to provision
    description: "An environment useful for contributions to the WordPress meta team."
    repo: https://github.com/WordPress/meta-environment.git
    hosts:
      - wp-meta.test
    custom:
      provision_site:
        "buddypressorg.test": true
        "jobs.wordpressnet.test": true
        "wordcamp.test": true
        "wordpressorg.test": true
        "wordpresstv.test": true

  # The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://my-example-site.test.
  # Remember, whitespace is significant! Tabs and spaces mean different things
  #example-site:
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    - my-example-site.test

# Utilities https://varyingvagrantvagrants.org/docs/en-US/utilities/
# are system level items that aren't websites, that install tools or packages
# the core utilities install tools such as phpmyadmin
utilities:
  core: # The core VVV utility
    - tls-ca # HTTPS SSL/TLS certificates
    - phpmyadmin # Web based database client
    - memcached-admin # Object cache management
    - opcache-status # opcache management
    - webgrind # PHP Debugging
    - mongodb # needed for Tideways/XHGui
    - tideways # PHP profiling tool, also installs xhgui check https://varyingvagrantvagrants.org/docs/en-US/references/tideways-xhgui/
    #- php56
    #- php70
    #- php71
    - php72
    - php73
    - php74

# vm_config controls how Vagrant provisions the virtual machine, and can be used to
# increase the memory given to VVV and the number of CPU cores.
# It can also be used to override the default provider being used within Vagrant.

vm_config:
  # For WP core development we recommend at least 2GB ( 2048 ),
  # If you have 4GB of RAM, lower this to 768MB or you may encounter issues
  memory: 2048
  # CPU cores:
  cores: 2

  # this tells VVV to use the prebuilt box copied from the USB drive at contributor days
  # once set to false, do not change back to true, and reprovision
  # wordcamp_contributor_day_box: false
  # Due to a limitation within Vagrant, the specified provider is only respected on a clean `vagrant up`
  # as Vagrant currently restricts you to one provider per machine
  # https://www.vagrantup.com/docs/providers/basic_usage.html#vagrant-up
  # provider: vmware_workstation

# General VVV options
general:
  # Backup the databases to the database/backups subfolder on halt/suspend/destroy, set to false to disable
  db_backup: true
  # Import the databases if they're missing from backups
  db_restore: true
  # set to true to use a synced shared folder for MariaDB database storage
  db_share_type: false
  # GitHub token to use from composer
  #github_token: xxxxxx

# Settings for the vagrant plugins supported by VVV
vagrant-plugins:
  disksize: 10GB # requires the disk size vagrant plugin

utility-sources:
  core:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-utilities.git
    branch: tls-ca-fixes

```

## Steps to Reproduce (for bugs)

1. simple step

## Your Environment
Vagrant 2.2.7
MacOs Catalina 10.15.3
