### ISSUE TITLE
wordpress-trunk provisioning had some issues

### ISSUE THREAD

**Issue by debabratakarfa** [Varying-Vagrant-Vagrants/VVV#2095]
```
    default:  * Updating wordpress-trunk in /srv/www/wordpress-trunk...
    default:  * Searching for a site template provisioner, vvv-init.sh
    default:  * Found vvv-init.sh at /srv/www/wordpress-trunk/provision/vvv-init.sh
    default:  * Script output will be logged to: log/provisioners/2020.04.04_13-30-59/provisioner-site-wordpress-trunk.log
    default: ---------------------------------------------
    default:
    default: ! Site provisioner failed! Check the full log for more details
    default:
    default: ---------------------------------------------
    default:  * Adding domains to the virtual machine's /etc/hosts file...
    default:  * Adding hosts from the VVV config entry
    default:    - Added trunk.wordpress.test from /vagrant/config.yml
    default:  * Reloading Nginx
    default:  ! wordpress-trunk provisioning had some issues, check the log as the site may not function correctly, provisioning took 3 seconds
==> default: Running action triggers after reload ...
==> default: Running trigger: VVV Post-Reload...
```

## What was The Command Used To Provision

```shell
vagrant up --provision
```

## Logs/What Broke

```yaml
  # The wordpress-develop configuration is useful for contributing to WordPress Core.
  # It uses the built WP to serve the site
  wordpress-trunk:
    skip_provisioning: false # provisioning this one takes longer, so it's disabled by default
    description: "An svn based WP Core trunk dev setup, useful for contributor days, Trac tickets, patches"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - trunk.wordpress.test
```

Trunk site log

```
[38;5;2m * Running provisioner for site wordpress-trunk[0m
 * Updating wordpress-trunk in /srv/www/wordpress-trunk...
 * Searching for a site template provisioner, vvv-init.sh
 * Found vvv-init.sh at /srv/www/wordpress-trunk/provision/vvv-init.sh
 * Script output will be logged to: log/provisioners/2020.04.04_13-30-59/provisioner-site-wordpress-trunk.log
 * Custom Site Template Develop Provisioner
   - This template is great for contributing to WordPress Core!
   - Not so much for building themes and plugins, or agency/client work
   - For client/theme/plugin work, use the custom-site-template instead
 * Creating database 'wordpresstrunk' (if it's not already there)
 * Granting the wp user priviledges to the 'wordpresstrunk' database
 * DB operations done.
 * Setting up the log subfolder for Nginx logs
 * Creating public_html folder if it doesn't exist already
 * Copying the sites Nginx config template
 * Using the default vvv-nginx-default.conf, to customize, create a vvv-nginx-custom.conf
 * Checking for WordPress Installs
 * Running npm install after svn up/git pull
up to date in 1.429s
found 0 vulnerabilities
 * Checking npm install result
 * Finished running npm install
 * Running grunt
 * Check the Grunt/Webpack output for Trunk Build at VVV/log/provisioners/2020.04.04_13-30-59/provisioner-wordpress-trunk-grunt.log
[38;5;9m---------------------------------------------[0m
[38;5;9m! Site provisioner failed! Check the full log for more details[0m
[38;5;9m---------------------------------------------[0m
 * Adding domains to the virtual machine's /etc/hosts file...
 * Adding hosts from the VVV config entry
   - Added trunk.wordpress.test from /vagrant/config.yml
 * Reloading Nginx
[38;5;9m ! wordpress-trunk provisioning had some issues, check the log as the site may not function correctly, provisioning took 3 seconds[0m
```

Grunt Log

```
grunt-cli: The grunt command line interface (v1.2.0)
Fatal error: Unable to find local grunt.
If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:
http://gruntjs.com/getting-started
```

## Your Environment
Vagrant 2.2.7
