### ISSUE TITLE
Can't seem to set trunk's svn to git in config.yml

### ISSUE THREAD

**Issue by ecotechie** [Varying-Vagrant-Vagrants/VVV#2120]
I'm pretty sure it's just not in the right place, but added `vcs: "git"` and it looks like svn is still being used...

```
  wordpress-trunk:
    vcs: "git"
    skip_provisioning: false # provisioning this one takes longer, so it's disabled by default
    description: "An svn based WP Core trunk dev setup, useful for contributor days, Trac tickets, patches"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - trunk.wordpress.test
```

<img width="157" alt="image" src="https://user-images.githubusercontent.com/11607383/79280013-2fae4180-7e64-11ea-8d11-57d455080ee9.png">

**Comment by ecotechie** [comment]
Please ignore... needed to move the option to  `custom:`

```
  wordpress-trunk:
    skip_provisioning: false # provisioning this one takes longer, so it's disabled by default
    description: "An svn based WP Core trunk dev setup, useful for contributor days, Trac tickets, patches"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    custom:
      vcs: "git"
    hosts:
      - trunk.wordpress.test
```
