### ISSUE TITLE
Extend 'skip_provisioning' setting to cover shared folders and databases

### ISSUE THREAD

**Issue by shoreline-chrism** [Varying-Vagrant-Vagrants/VVV#2131]
**Is your feature request related to a problem? Please describe.**

Sometimes, I'll use one VVV folder to house a few custom sites in one config.  When I use 'skip_provisioning', I will still see databases imported and folders for sites that I would like to skip.

When I use the 'skip_provisioning' setting in the custom VVV config file, I expect that nothing of that site will be provisioned to the VM.  The nginx rules, hosts and site provisioner are a great start, but is there a limitation with the shared folders and database imports?

**Describe the solution you'd like**

In order to save resources, it would be great if 'skip_provisioning' can also skip sharing the folders and importing the database into the VM. 

**Describe alternatives you've considered**

I usually customize my sites via the vvv-init.sh file but since that's not being run, I can't remove DBs and/or shared folders through that.

**Comment by Mte90** [comment]
This already happens about nginx https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision-site.sh#L225

The issues is for the db import but I did a pr that fix this https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2142

About the sharing as the whole www folder is shared I don't think that we can fix it because is how works the project. In this way has just few folders to share instead of every. We did that change few months ago to speed up and simplify the booting process.

**Comment by shoreline-chrism** [comment]
Thank you for looking into this.  It's fine that this addresses just the database imports because I believe that is the biggest offender in terms of taking up resources on the VM when you have multiple sites on one VVV instance. 

I will test this branch out shortly but I am not a qualified tester so I won't be running any unit tests or anything. I'm a user of VVV with basic scripting knowledge.

**Comment by shoreline-chrism** [comment]
![skip_provision_works](https://user-images.githubusercontent.com/9121766/81094225-32cfa700-8ed1-11ea-82d3-395dc38dd208.PNG)

I see the warning notes about skipping the import, however the sites were still in my phpmyadmin when I ran `vagrant up --provision`. Here's a screeshot:

![skip_provisioning_still_imported](https://user-images.githubusercontent.com/9121766/81094663-d620bc00-8ed1-11ea-9367-f474cc5c00b0.PNG)

Is there some other place in the provisioning that imports all of the files in the `database/sql/backups` folder? Might the settings `db_backup` and `db_restore` be interfering here?  Both of mine are set to `true`:

```yml
# General VVV options
general:
  # Backup the databases to the database/backups subfolder on halt/suspend/destroy, set to false to disable
  db_backup: true
  # Import the databases if they're missing from backups
  db_restore: true
  # set to true to use a synced shared folder for MariaDB database storage
  db_share_type: false
  # GitHub token to use from composer
  #github_token: xxxxxx

```
