### ISSUE TITLE
Installing Packages via config.yml

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2135]
To save the writing of utilities for things provided by package managers, perhaps we can support ruby/npm/composer packages out of the box, with something like this:

```yaml
packages:
  composer:
    humanmade/coding-standards: *
  gems:
    - wordmove
  npm:
    - sass
```

Related to #2129
