### ISSUE TITLE
An nginx config was not found at .vvv/vvv-nginx.conf provision/vvv-nginx.conf or vvv-nginx.conf

### ISSUE THREAD

**Issue by derekmizak** [Varying-Vagrant-Vagrants/VVV#2163]
## What was The Command Used To Provision

```shell
vagrant up --provision
```

## What Kind of VVV Provision Was This

This was a fresh install

## Logs/What Broke

Provisioning of either site one or two didnt work with the same result as below. vvv.test working OK.

```
[38;5;2m * Running provisioner for site wordpress-one[0m
 * Updating wordpress-one in /srv/www/wordpress-one...
 * Searching for a site template provisioner, vvv-init.sh
 * Found vvv-init.sh at /srv/www/wordpress-one/provision/vvv-init.sh
 * Script output will be logged to: log/provisioners/20200524-005849/provisioner-site-wordpress-one.log
 * Custom site template provisioner wordpress-one - downloads and installs a copy of WP stable for testing, building client sites, etc
 * Creating database 'wordpress-one' (if it's not already there)
 * Granting the wp user priviledges to the 'wordpress-one' database
 * DB operations done.
 * Setting up the log subfolder for Nginx logs
 * Creating public_html folder if it doesn't exist already
 * Install type is 'single'
 * Downloading WordPress version 'latest' locale: 'en_US'
PHP Fatal error:  Uncaught PharException: phar "/usr/local/bin/wp" SHA1 signature could not be verified: broken signature in /usr/local/bin/wp:3
Stack trace:
#0 /usr/local/bin/wp(3): Phar::mapPhar()
#1 {main}
  thrown in /usr/local/bin/wp on line 3
[38;5;9m---------------------------------------------[0m

[38;5;9m! Site provisioner failed! Check the full log for more details[0m

[38;5;9m---------------------------------------------[0m
 * Warning: An nginx config was not found at .vvv/vvv-nginx.conf provision/vvv-nginx.conf or vvv-nginx.conf, searching 3 folders down, please be patient...
[38;5;9m ! Warning: No nginx config was found, VVV will not know how to serve this site[0m
 * Adding domains to the virtual machine's /etc/hosts file...
 * Adding hosts from the VVV config entry
   - Added one.wordpress.test from /vagrant/config.yml
 * Reloading Nginx
[38;5;9m ! wordpress-one provisioning had some issues, check the log as the site may not function correctly, provisioning took 4 seconds[0m
```

```yaml
---


sites:

  
  wordpress-one:
    skip_provisioning: false
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - one.wordpress.test
    custom:
      wpconfig_constants:
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true # To disable in WP 5.2 the FER mode

  wordpress-two:
    skip_provisioning: false
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      # locale: it_IT
      delete_default_plugins: true
      install_plugins:
        - query-monitor
    hosts:
      - two.wordpress.test

  
  wordpress-trunk:
    skip_provisioning: true # provisioning this one takes longer, so it's disabled by default
    description: "An svn based WP Core trunk dev setup, useful for contributor days, Trac tickets, patches"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - trunk.wordpress.test

  
  wordpress-meta-environment:
    skip_provisioning: true # disabled by default, this takes a long time to provision
    description: "An environment useful for contributions to the WordPress meta team."
    repo: https://github.com/WordPress/meta-environment.git
    hosts:
      - wp-meta.test
    custom:
      provision_site:
        "buddypressorg.test": true
        "jobs.wordpressnet.test": true
        "wordcamp.test": true
        "wordpressorg.test": true
        "wordpresstv.test": true

  
utilities:
  core: # The core VVV utility
    - tls-ca # HTTPS SSL/TLS certificates
    - phpmyadmin # Web based database client
    #- memcached-admin # Object cache management
    #- opcache-status # opcache management
    #- webgrind # PHP Debugging
    #- mongodb # needed for Tideways/XHGui
    #- tideways # PHP profiling tool, also installs xhgui check https://varyingvagrantvagrants.org/docs/en-US/references/tideways-xhgui/
    #- php56
    #- php70
    #- php71
    #- php72
    #- php73
    #- php74

# 

vm_config:
  
  memory: 2048
  cores: 2

  
general:
  # Backup the databases to the database/backups subfolder on halt/suspend/destroy, set to false to disable
  db_backup: true
  # Import the databases if they're missing from backups
  db_restore: true
  # set to true to use a synced shared folder for MariaDB database storage
  db_share_type: false
  # GitHub token to use from composer
  #github_token: xxxxxx

# Settings for the vagrant plugins supported by VVV
vagrant-plugins:
  disksize: 10GB # requires the disk size vagrant plugin

```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

Operating System: Windows 10, Vagrant: v2.2.9, VirtualBox: v6.1.8r137981
