### ISSUE TITLE
Sites: Git clone list

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2195]
Related to https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2188 a user should be able to declare a number of git repositories to clone into their site, e.g.:

```yaml
  wordpress-four:
    provisioner_repo: git@github.com:Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      install_plugins:
        - query-monitor
    hosts:
      - four.wordpress.test
    git:
      "public_html": git@github.com:tomjn/toms-site.git
```

It shouldn't be necessary to put the provisioner in a WP site git repo, or to fork the custom site template. This should greatly simplify the setup process for sites on hosts such as WP Engiine or VIP
