### ISSUE TITLE
Main Provisioning Error - DPKG was Interrupted

### ISSUE THREAD

**Issue by kenalvares** [Varying-Vagrant-Vagrants/VVV#2210]
Was facing several issues earlier today. I should mention I've used VVV for a while to develop WP sites locally, but still consider myself a noob as I only know the absolute basics and use it following the docs. I wasnt working on any new projects for a while and didn't use VVV as I edited code on the live sites directly. Recently, I needed to take one of my old VVV projects online, after several months of not working on it or in VVV. It took me many days to fix various issues - failed to start nginx & mysql, mirror.herrbischoff.com wasn't working, then I couldn't do a git pull because of an .lock file I couldn't find, etc etc. 

Finally, I manage to update everything but now I'm unsure of the problem - "dpkg was interrupted". Googling the error statement takes me to ubuntu troubleshooting threads - which are of zero help and just flew over my head. I need to access this site urgently, how can I fix my VVV or, is there anyway (since I have backups enabled) that I could use database backups & the files in "/www/" to migrate the site onto a live server? Need the quickest and most painless solution possible!

## What was The Command Used To Provision

```shell
vagrant up --provision
```

## What Kind of VVV Provision Was This

This was an attempt to upgrade to a new version of VVV so that I could reprovision and existing VVV WordPress site to take online

## Logs/What Broke
My main provision log file 
```
[38;5;2m ▷ Running the 'main' provisioner...[0m
 * Bash profile setup and directories.
 * Setting ownership of files in /home/vagrant to vagrant
 * Copying /srv/config/bash_profile                      to /home/vagrant/.bash_profile
 * Copying /srv/config/bash_aliases                      to /home/vagrant/.bash_aliases
 * Copying /srv/config/bash_aliases                      to /root/.bash_aliases
 * Copying /srv/config/vimrc                             to /home/vagrant/.vimrc
 * Copying /srv/config/subversion-servers                to /home/vagrant/.subversion/servers
 * Copying /srv/config/subversion-config                 to /home/vagrant/.subversion/config
 * Copying /srv/config/ssh_known_hosts                   to /etc/ssh/ssh_known_hosts
cp: cannot stat '/srv/config/ssh_known_hosts': No such file or directory
 * Copying /srv/config/sshd_config                       to /etc/ssh/sshd_config
 * Reloading SSH Daemon
 * Testing network connection to https://ppa.launchpad.net
[38;5;2m * Successful Network connection to https://ppa.launchpad.net detected[0m
 * Testing network connection to https://wordpress.org
[38;5;2m * Successful Network connection to https://wordpress.org detected[0m
 * Testing network connection to https://github.com
[38;5;2m * Successful Network connection to https://github.com detected[0m
 * Testing network connection to https://raw.githubusercontent.com
[38;5;2m * Successful Network connection to https://raw.githubusercontent.com detected[0m
 * Testing network connection to https://getcomposer.org
[38;5;2m * Successful Network connection to https://getcomposer.org detected[0m
 * Testing network connection to http://ams2.mirrors.digitalocean.com
[38;5;2m * Successful Network connection to http://ams2.mirrors.digitalocean.com detected[0m
[38;5;2m * Network checks succeeded[0m
 
 * Main packages check and install.
 * git-core/ppa already present, skipping

 * Setting up MySQL configuration file links...
 * mysql group exists
 * mysql user present and has uid 9001
 * Copying /srv/config/mysql-config/vvv-core.cnf to /etc/mysql/conf.d/vvv-core.cnf
 * Copying custom apt sources
 * Checking Apt Keys
 * Cleaning up dpkg lock file
 * Running apt-get update...
Hit:1 http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic InRelease
Hit:2 http://mirrors.ukfast.co.uk/sites/mariadb/repo/10.4/ubuntu bionic InRelease
Hit:3 http://ams2.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic InRelease
Hit:4 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease
Hit:5 http://mirrors.piconets.webwerks.in/mariadb-mirror/repo/10.4/ubuntu bionic InRelease
Hit:7 http://ppa.launchpad.net/varying-vagrant-vagrants/php/ubuntu bionic InRelease
Hit:8 http://sgp1.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic InRelease
Hit:9 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:10 https://deb.nodesource.com/node_10.x bionic InRelease
Hit:11 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:12 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:13 http://ftp.yz.yamagata-u.ac.jp/pub/dbms/mariadb/repo/10.4/ubuntu bionic InRelease
Hit:14 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:15 https://nginx.org/packages/mainline/ubuntu bionic InRelease
Hit:6 https://packagecloud.io/github/git-lfs/ubuntu bionic InRelease
Reading package lists...
 * Installing apt-get packages...
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
 * Installing apt-get packages returned a failure code, cleaning up apt caches then exiting
[38;5;9m ! Main packages check and install failed, halting provision[0m
[38;5;9m ! The 'main' provisioner ran into problems, check the full log for more details! It completed in 21 seconds.[0m
```
My config
```yaml
---
# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

#
# IMPORTANT, if you change this file, you have to reprovision,  no exceptions
# Do this by running either this command:
# vagrant reload --provision
#
# Or, if your machine is already turned on:
# vagrant provision
#

# These are your websites, and their names map on to the folders they're
# located in. See the docs for how to define these, and what all the keys
# and options are
sites:
  # latest version of WordPress, can be used for client work and testing
  # Check the readme at https://github.com/Varying-Vagrant-Vagrants/custom-site-template
  wordpress-one:
    skip_provisioning: true
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - one.wordpress.test
    custom:
      wpconfig_constants:
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true # To disable in WP 5.2 the FER mode

  wordpress-two:
    skip_provisioning: true
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      locale: it_IT
      delete_default_plugins: true
      install_plugins:
        - query-monitor
    hosts:
      - two.wordpress.test

  goa-tinto:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - goatinto.test

  renzmarketinggoa:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - renzgoa.com

  pippip:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - pippipmedia.test

  jumpcutgoa:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - jumpcutgoa.test

  studiodeconstruct:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - studiodeconstruct.test
  # The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://mysite.test.
  # Remember, whitespace is significant! Tabs and spaces mean different things
  #mysite:
  #  description: "My website"
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    - mysite.test

  # The wordpress-develop configuration is useful for contributing to WordPress Core.
  # It uses the built WP to serve the site
  wordpress-trunk:
    skip_provisioning: true # provisioning this one takes longer, so it's disabled by default
    description: "An svn based WP Core trunk dev setup, useful for contributor days, Trac tickets, patches"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - trunk.wordpress.test

  # The following commented out site configuration will create a environment useful
  # for contributions to the WordPress meta team, .e.g WordCamps, .org, etc:
  wordpress-meta-environment:
    skip_provisioning: true # disabled by default, this takes a long time to provision
    repo: https://github.com/WordPress/meta-environment.git

  # The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://my-example-site.test.
  # Remember, whitespace is significant! Tabs and spaces mean different things
  #example-site:
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    - my-example-site.test

# Utilities https://varyingvagrantvagrants.org/docs/en-US/utilities/
# are system level items that aren't websites, that install tools or packages
# the core utilities install tools such as phpmyadmin
utilities:
  core: # The core VVV utility
    - tls-ca # HTTPS SSL/TLS certificates
    - phpmyadmin # Web based database client
    #- memcached-admin # Object cache management
    #- opcache-status # opcache management
    #- webgrind # PHP Debugging
    #- mongodb # needed for Tideways/XHGui
    #- tideways # PHP profiling tool, also installs xhgui check https://varyingvagrantvagrants.org/docs/en-US/references/tideways-xhgui/
    #- php56
    #- php70
    #- php71
    #- php72
    #- php73

# vm_config controls how Vagrant provisions the virtual machine, and can be used to
# increase the memory given to VVV and the number of CPU cores.
# It can also be used to override the default provider being used within Vagrant.

vm_config:
  # For WP core development we recommend at least 2GB ( 2048 ),
  # If you have 4GB of RAM, lower this to 768MB or you may encounter issues
  memory: 2048
  # CPU cores:
  cores: 2

  # this tells VVV to use the prebuilt box copied from the USB drive at contributor days
  # once set to false, do not change back to true, and reprovision
  # wordcamp_contributor_day_box: false
  # Due to a limitation within Vagrant, the specified provider is only respected on a clean `vagrant up`
  # as Vagrant currently restricts you to one provider per machine
  # https://www.vagrantup.com/docs/providers/basic_usage.html#vagrant-up
  # provider: vmware_workstation

# General VVV options
general:
  # Backup the databases to the database/backups subfolder on halt/suspend/destroy, set to false to disable
  db_backup: true
  # Import the databases if they're missing from backups
  db_restore: true
  # set to true to use a synced shared folder for MariaDB database storage
  db_share_type: false
  # GitHub token to use from composer
  #github_token: xxxxxx
```

## Your Environment
Operating System: Windows 10
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.4.1-git::master
Platform: platform-mingw32 windows  HasWinAdminPriv  vagrant-hostsupdater NoColour shared_db_folder_disabled, VVV Path: "C:/Softwares/VVV/~/vagrant-local"
Vagrant: v2.2.5, VirtualBox: v6.0.22r137980
