### ISSUE TITLE
Extended DB Backup Options

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2225]
Originally, DB backups and restores were added so that if you destroyed the VM you could create it again without data loss. Options were added

At the moment you can back up databases to SQL files, or not back up. All or nothing:

```yaml
general:
  db_backup: true
  db_restore: true
```

t's time we give people finger control over DB backup behaviours. Here's a proposed schema:

```yaml
general:
  db_backup:
    # Compress usiing gzip, db.sql becomes db.sql.gz when true
    gzip: true

    # When do we run backups?
    on:
      halt: false
      destroy: true

    # Always back up these databases
    include:
      - firstdb
      - second

    # Never back up these databases
    exclude:
      - fourth
      - fifth

    # If a database doesn't appear in the above lists, do we back it up?
    other: true

  db_restore:
    # when do we restore?
    on:
      provision: true

    # Always restore these:
    include:
      - firstdb
      - second

    # Never restore these:
    exclude:
      - fourth
      - fifth

    # Default for databases not mentioned above
    other: true
```

I don't expect all of these to be implemented at once. So this will act as the umbrella ticket for:

 - backup include list
 - backup exclude list
 - backup default
 - restore include list
 - restore exclude list
 - restore default
 - backup gzip compression
 - backup trigger controls
