### ISSUE TITLE
"The following SSH command responded with a non-zero exit status." at batch_action.rb

### ISSUE THREAD

**Issue by MiquelAdell** [Varying-Vagrant-Vagrants/VVV#2244]
## What was The Command Used To Provision

```shell
vagrant up --provision --debug
```

## What Kind of VVV Provision Was This

This was an attempt to upgrade to a new version of VVV

## Logs/What Broke

```yaml
sites:
  // some sites that look like these
  sitename:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - sitename.test
    skip_provisioning: false
    custom:
      delete_default_plugins: true

  test:
    hosts:
      - test.test
    skip_provisioning: true

  wordpress-default:
    hosts:
      - local.wordpress
    repo: "https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git"
    skip_provisioning: true

  wordpress-develop:
    hosts:
      - src.wordpress-develop
      - build.wordpress-develop
    repo: "https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git"
    skip_provisioning: true

  vvv:
    hosts:
      - vvv.test
    skip_provisioning: true

utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind
    - tls-ca

vm_config:
  cores: 1
  memory: 2048

```

## Steps to Reproduce (for bugs)

1. I opened **virtualbox** it said I had to update. I did, to **6.1**
2. After trying to vagrant up something failed so I pulled from dev 
3. vagrant-goodhosts  failed but I've seen at the github page that there was some command to run
4. ran ```vagrant plugin install vagrant-goodhosts --local```
5. ```vagrant up``` or ```vagrant up --provision``` keep failing

Full log from here https://gist.github.com/MiquelAdell/0856c3594dee6628d42c21719ac928e4

The last lines of it are:
```shell
/opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/runner.rb:89:in `run'
/opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:240:in `action_raw'
/opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:212:in `block in action'
/opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/environment.rb:613:in `lock'
/opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:198:in `call'
/opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:198:in `action'
/opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
 INFO interface: error: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

echo; printf $SSH_AUTH_SOCK

Stdout from the command:

Stderr from the command:

printf: usage: printf [-v var] format [arguments]
```

## Your Environment

Varying Vagrant Vagrants: v3.5.0-git::develop
Vagrant: v2.2.9, 
VirtualBox: v6.1.14r140239

Platform: platform-darwin19.2.0 shell:/bin/zsh vagrant-hostmanager vagrant-hostsupdater vagrant-goodhosts vagrant-vbguest shared_db_folder_disabled, VVV Path: "/Users/miqueladell/code/VVV"

Thanks a lot!
