### ISSUE TITLE
Confused with docs on how I can add a new site in www

### ISSUE THREAD

**Issue by owenfar** [Varying-Vagrant-Vagrants/VVV#2254]
Hi everyone, I'm trying to add a new site inside www when I follow the documentation found here: https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/

But I get this when I reprovision:

```
default: ‘/srv/www/newsite’
default: : No such file or directory
```
But everything else works. Just the newsite is not being created.

According to the docs I have to modify config.yml and I did like so:

```
sites:

  newsite:
    skip_provisioning: false
    description: "Newsite Local Development"
    nginx_upstream: php73
    hosts:
      - newsite.test
    custom:
      delete_default_plugins: true
      wpconfig_constants:
        WP_DEBUG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true # To disable in WP 5.2 the FER mode
```

The reason I'm confused is because inside http://vvv.test/ in Adding a New Site section is says: 'Modify vvv-custom.yml under the sites section to add a site'. Why is this different from the docs online? And where is vvv-custom.yml? I cannot find that anywhere. I cloned the latest VVV and installed the latest VirtualBox.

I appreciate your time to help me figure this out. Thanks in advance
