### ISSUE TITLE
--provision-with doesn't work with hyphen separated site names

### ISSUE THREAD

**Issue by LucasDemea** [Varying-Vagrant-Vagrants/VVV#2301]
## What was The Command Used To Provision

```shell
vagrant provision --provision-with=site-site-with-hyphens
```

## What Kind of VVV Provision Was This

This was a reprovision of an already working VVV

## Logs/What Broke

Similar to [1145](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1145), but with --provision-with flag.

First time I'm trying to provision a single site with the --provision-with flag. The database setup didn't work.

I Got the error : ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-with-hyphens' at line 1

The same install without hyphens in the sitename is working fine.

see full log here : https://gist.github.com/LucasDemea/d5958444ec79f0abb2459fa16d9adec5

```yaml
 site-with-hyphens:
    repo: https://github.com/custom/repo
    hosts:
      - site-with-hyphens.test
    nginx_upstream: php74
```
