### ISSUE TITLE
Allow sites to declare utility dependencies

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2302]
**Is your feature request related to a problem? Please describe.**

A site might require a piece of software to function, but if the user has not added the relevant utility it might fail

**Describe the solution you'd like**

The ability to declare a utility as a dependency in a sites `config/config.yml` entry, e.g.

```yaml
  phpeight:
    nginx_upstream: php80
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - phpeight.test
    requires:
      - core/php80
```

The `php80` provisioner in the core utility would be added to the list of utilities to run as a result.

**Additional context**

This would simplify the use and documentation of extra PHP versions, as well as other things. E.g. we could move memcached to a utility and it would only be installed if a site requires it
