### ISSUE TITLE
Backup database exclusion list

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2340]
Allow the definition off databases that should never be backed up, e.g.:

```yaml
general:
  db_backup:
    # Never back up these databases
    exclude:
      - fourth
      - fifth
```

Related to https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2225
