### ISSUE TITLE
GZip backups

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2342]
The ability to use compressed `.sql.gz` backups instead, e.g.

```yaml
general:
  db_backup:
    # Compress using gzip, db.sql becomes db.sql.gz when true
    gzip: true
```

`db_backup` and the  restore  script will need adjusting

Related to #2225
