### ISSUE TITLE
502 Bad Gateway: WooCommerce and VVV

### ISSUE THREAD

**Issue by dashkevych** [Varying-Vagrant-Vagrants/VVV#2347]
Hello,

Has anyone experienced **502 Bad Gateway** issue in your WordPress installation when WooCommerce is active?

I've just install a new copy of VVV (v3.5.1) and I am getting this weird 502 Bad Gateway issue. I am using VVV for a long time and I've not seen this issue before. Here is an error from _nginx-error.log_:

`2021/01/27 19:44:28 [error] 9793#9793: *11 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.50.1, server: wporg.test, request: "GET /wp-admin/admin.php?page=wc-admin HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.3-fpm.sock:", host: "wporg.test", referrer: "http://wporg.test/wp-admin/"
2021/01/27 19:47:57 [error] 9793#9793: *33 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.50.1, server: wporg.test, request: "GET /wp-admin/post.php?post=703&action=edit HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.3-fpm.sock:", host: "wporg.test", referrer: "http://wporg.test/wp-admin/edit.php?post_type=page"`

If I deactivate the WooCommerce plugin then WordPress starts working fine.

Here is a config of the site:

```
  wporg:
    skip_provisioning: false
    description: "WP Dev website"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - wporg.test
    custom:
      wp_version: nightly
      delete_default_plugins: true
      install_plugins:
        - query-monitor
        - jetpack
        - woocommerce
        - rtl-tester
        - gutenberg
        - classic-editor
      wpconfig_constants:
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true # To disable in WP 5.2 the FER mode
        JETPACK_DEV_DEBUG: true
```

Here is info from _php7.3-fpm.log_

```
[27-Jan-2021 20:50:25] WARNING: [pool www] child 5938 said into stderr: ""
[27-Jan-2021 20:50:25] WARNING: [pool www] child 5938 said into stderr: "Fatal error: Maximum execution time of 30+2 seconds exceeded (terminated) in /srv/www/wporg/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/Onboarding.php on line 585"
[27-Jan-2021 20:50:25] WARNING: [pool www] child 5938 exited with code 124 after 412.580476 seconds from start
[27-Jan-2021 20:50:25] NOTICE: [pool www] child 9887 started
```

Is it something wrong with my VVV setup? Or is it a WooCommerce issue?

Thank you very much for your time!
