### ISSUE TITLE
VVV Provisioned with Node but without NPM

### ISSUE THREAD

**Issue by Gen-fr** [Varying-Vagrant-Vagrants/VVV#2349]
Unable to provisioning with error: ! The 'main' provisioner ran into problems, check the full log for more details! It completed in 105 seconds. The SSH command responded with a non-zero exit status...

## What was The Command Used To Provision

```
vagrant up --provision
```

## What Kind of VVV Provision Was This

This was a reprovision of an already working VVV

## Logs/What Broke

 - [ubuntu-bionic-18.04-cloudimg-console.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5920537/ubuntu-bionic-18.04-cloudimg-console.log)
 - [provisioner-main.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/5920539/provisioner-main.log)

terminal output:

```
    default: /srv/provision/core/grunt/provision.sh: line 16: /usr/bin/npm: No such file or directory
    default:  ! The 'main' provisioner ran into problems, check the full log for more details! It completed in 105 seconds.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
---

```yaml
sites:

  # latest version of WordPress, can be used for client work and testing
  # Check the readme at https://github.com/Varying-Vagrant-Vagrants/custom-site-template
  wordpress-one:
    skip_provisioning: false
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - one.wordpress.test
    custom:
      wpconfig_constants:
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true # To disable in WP 5.2 the FER mode

  wordpress-two:
    skip_provisioning: false
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      # locale: it_IT
      delete_default_plugins: true
      install_plugins:
        - query-monitor
    hosts:
      - two.wordpress.test


  wordpress-trunk:
    skip_provisioning: true # provisioning this one takes longer, so it's disabled by default
    description: "An svn based WP Core trunk dev setup, useful for contributor days, Trac tickets, patches"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - trunk.wordpress.test

 
  wordpress-meta-environment:
    skip_provisioning: true # disabled by default, this takes a long time to provision
    description: "An environment useful for contributions to the WordPress meta team."
    repo: https://github.com/WordPress/meta-environment.git
    hosts:
      - wp-meta.test
    custom:
      provision_site:
        "buddypressorg.test": true
        "jobs.wordpressnet.test": true
        "wordcamp.test": true
        "wordpressorg.test": true
        "wordpresstv.test": true

utilities:
  core: # The core VVV utility
    - tls-ca # HTTPS SSL/TLS certificates
    - phpmyadmin # Web based database client


vm_config:
  
  memory: 2048
  cores: 2


general:
  # Backup the databases to the database/backups subfolder on halt/suspend/destroy, set to false to disable
  db_backup: true
  # Import the databases if they're missing from backups
  db_restore: true
  # set to true to use a synced shared folder for MariaDB database storage
  db_share_type: false

vagrant-plugins:
  disksize: 10GB # requires the disk size vagrant plugin
```

## Steps to Reproduce (for bugs)

1. Fresh install
2. It works with  "vagrant up"
3. When I try "vagrant up --provision" got the log above
4.

## Your Environment

host - Debian 10
```
 V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.6.0-git::develop

Platform: platform-linux-gnu shell:/bin/bash systemd  vagrant-goodhosts vagrant-vbguest CaseSensitiveFS shared_db_folder_disabled, VVV Path: "/home/gen/VVV

Vagrant: v2.2.14, VirtualBox: v6.1.18r142142
```
