### ISSUE TITLE
Run command in site folders via config

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2387]
Currently you can specify folders for a site and tell VVV to clone git repos, install composer packages, npm packages

Wouldn't it be great if you can tell it to execute a script in that folder?

Right now this will git clone VIP folders into place:

```yaml
  vipone:
    skip_provisioning: true
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - vipone.test
    folders:
      public_html/wp-content/:
        git:
          repo: https://github.com/Automattic/vip-go-skeleton.git
          overwrite_on_clone: true
      public_html/wp-content/mu-plugins:
        git:
          repo: https://github.com/Automattic/vip-go-mu-plugins.git
          overwrite_on_clone: true
          hard_reset: true
          pull: true
```
Wouldn't it be nice to do something like this?

```yaml
  mysite:
    repo: ...
    hosts:
      - mysite.test
    folders:
      public_html/wp-content:
        git:
          repo: https://github.com/example/example-wp-content.git
        exec: >
          composer install
          ./setup.sh
```

Then it would clone that repo into `wp-content` and run the commands in that folder
