### ISSUE TITLE
Investigate Box Changing Behaviour on non-VB providers

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2411]
Related to #2410, we don't know if changing the box in the vagrant file breaks or recreates existing VMs under the non-VirtualBox providers, or if the behaviour is the same across all providers.

We need a thumbs up for:

 - Hyper-V users
 - Parallels users
 - VMWare users

To do this:

1. spin up the `develop` branch to get yourself a fresh VVV instance running Ubuntu 18
2. make a change e.g a post on the wordpress-one site so you can identify this instance
3. `vagrant halt`
4. modify `config.yml` and change the `box:` under `vm_config` section, change it to a different box, e.g `generic/ubuntu2004`
5. run `vagrant up`, no provision flag, just `vagrant up`
6. is it a new VM or the old one? Were there errors? Check for the post you created in step 2
7. bonus points if you copy paste the terminal output of the vagrant commands to a gist for us to see!

config example:

```yml
vm_config:
  # For WP core development we recommend at least 2GB ( 2048 ),
  # If you have 4GB of RAM, lower this to 768MB or you may encounter issues
  memory: 2048
  # CPU cores:
  cores: 2
  box: generic/ubuntu2004
```
