### ISSUE TITLE
Add custom variable in the custom block

### ISSUE THREAD

**Issue by david-nubee** [Varying-Vagrant-Vagrants/VVV#2447]
Hello,

I made my custom provisioner, but I need to add custom config value to it.

I try like that :

My config.yml
```
test123:
    repo: url-to-my-private-repo
    description: "Test 123"
    hosts:
      - test-123.test
    custom:
      site_title: "Test 123"
      server_pass: "A password to copie a file from my server"
      db_name: "wp_test123"
      db_user: "wp"
      db_pass: "wp"
      acf_pro_key: "My private key to get acf pro"
```

My vvv-init.sh, where I try to retrieve ma config value : 
```
set -eo pipefail

DOMAIN=$(get_primary_host "${VVV_SITE_NAME}".test)
SITE_TITLE=$(get_config_value 'site_title' "${DOMAIN}")

WP_VERSION=$(get_config_value 'wp_version' 'latest')
WP_LOCALE=$(get_config_value 'wp_locale' "fr_FR")

DB_NAME=$(get_config_value 'db_name' wp_"${VVV_SITE_NAME}")
DB_USER=$(get_config_value 'db_user' '')
DB_PASS=$(get_config_value 'db_pass' '')
DB_NAME=${DB_NAME//[\\\/\.\<\>\:\"\'\|\?\!\*-]/}

SERVER_PASS=$(get_config_value 'server_pass' '')
ACF_PRO_KEY=$(get_config_value 'acf_pro_key' '')
```

SERVER_PASS, ACF_PRO_KEY, DB_USER and DB_PASS are empty. 

Is it possible to pass custom variable ?
What  did I do wrong ?

I don't know if I include enough details, feel free to tell me if not.

Thanks.

**Comment by david-nubee** [comment]
Hello,

OS : Mac OS 11.2.3
Vagrant : 2.2.15
VVV : 3.6.2

All last version

**Comment by tomjn** [comment]
How are you testing that they're empty? The lines in the code blocks you provided are correct as far as I can see, the mistake is not in the `vvv-init.sh` code that you shared

**Comment by tomjn** [comment]
I did notice however, that your sites name is not indented, implying this:

```yaml
sites:
test123:
```

Which would be invalid. Clearly this is not the case though, and you have re-indented the YAML section to be helpful. Can you undo that? It's unhelpful

**Comment by david-nubee** [comment]
Oh yeah, I do not copy this part and the indentation has been flush in the copy/paste in github.

The provisioning "work" has intended, the only part that doesn’t work is caused by my empty value.

I try to copy a base database that I use to start my project :


```
if [ "$IS_INSTALL" = true ]; then
  wget --user="nubee" --password="${SERVER_PASS}" http://mydevserver.domain.com/devstart/wpstart-daily-dump.sql

  if [ -s "wpstart-daily-dump.sql" ]; then
    echo "Copy default nubee Wordpress DB ..."

    noroot mysql -u "${DB_USER}" --password="${DB_PASS}" --database="${DB_NAME}" < wpstart-daily-dump.sql
  else
    echo "Installing WordPress Stable..."

    noroot wp core install --url="${DOMAIN}" --title="${SITE_TITLE}" --admin_name=admin --admin_email="admin@local.test" --admin_password="password"
  fi

  rm wpstart-daily-dump.sql

  echo "Operations done."
fi
```
But, since SERVER_PASS is empty, it doesn't work.

```
Resolving utils.nubee.ca (mydevserver.domain.com)... XXX.XXX.XXX.XXX
Connecting to utils.nubee.ca (mydevserver.domain.com)|XXX.XXX.XXX.XXX.. connected.
HTTP request sent, awaiting response... 401 Unauthorized
Authentication selected: Basic realm="Acces client"
Reusing existing connection to mydevserver.domain.com.
HTTP request sent, awaiting response... 401 Unauthorized
```

**Comment by tomjn** [comment]
I'd recommend directly observing the value rather than drawing conclusions. It could be that it is not empty, but holds an unexpected value.

It's also possible that the `custom:` section is indented incorrectly, e.g. a mixture of tabs and spaces, or tabs in a documented indented with spaces

**Comment by tomjn** [comment]
you could also avoid needing the server_pass variable and use SSH agent forwarding. By relying on your host having the SSH keys configured, you can SSH into the server and grab the SQL file, or use rsync, or use an ssh URL, or `scp`, or even SFTP

This would be more secure than putting secrets in `config.yml`

**Comment by tomjn** [comment]
Should `wget` with basic auth not use `--http-password` and `--http-user`?

**Comment by david-nubee** [comment]
Hello,

Thanks for your answer.

I try to "echo" the variables to what they contain and they are empty.

```
echo -e "\nServer pass : '${SERVER_PASS}'\n"
echo -e "ACF_PRO_KEY : '${ACF_PRO_KEY}'\n"
```

Return : 
```
Server pass : ''

ACF_PRO_KEY : ''
```

I can probably bypass the need for the password, but it's only one example of custom variables I need. I just don't understand why the value is not passed to the provisioning script.

For example, I absolutely need the ACF_PRO_KEY var, since it’s a premium plugin, I need to pass the key to install it via composer. I don't want to put my key in a file on my repo.

Thanks

**Comment by tomjn** [comment]
and you’re absolutely sure that white space formatting and tabs vs spaces
is not the issue? And you’ve manually inspected to double and triple check?

I ask because the custom site template uses an identical method to do what
you’re trying to do and succeeds. YAML formatting and structure is the
biggest suspect right now

**Comment by david-nubee** [comment]
I have a YAML linter in my Sublime Text, but here the complete file : 

```
---

# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

#
# IMPORTANT, if you change this file, you have to reprovision,  no exceptions
# Do this by running either this command:
# vagrant reload --provision

# Or, if your machine is already turned on:
# vagrant provision
#

# These are your websites, and their names map on to the folders they're
# located in. See the docs for how to define these, and what all the keys
# and options are
sites:

  test123:
    repo: https://nubee-davidmenard:6ntsk79X@gitlab.com/nubee-inc/wp-start.git
    branch: dev-david-2021
    description: "Test 123"
    hosts:
      - Test-123.test
    skip_provisioning: false
    custom:
      site_title: "Test 123"
      server_pass: HvdCeGcw3j]XtTWH]nZ[8tGK2,BjCm2J7=BL
      db_name: wp_test123
      db_user: wp
      db_pass: wp
      acf_pro_key: b3JkZXJfaWQ9NDEyNzF8dHlwZT1kZXZlbG9wZXJ8ZGF0ZT0yMDE0LTEwLTAzIDE3OjQ5OjEx
      live_url: test.google.ca

# Utilities https://varyingvagrantvagrants.org/docs/en-US/utilities/
# are system level items that aren't websites, that install tools or packages
# the core utilities install tools such as phpmyadmin
utilities:
  core: # The core VVV utility
    - tls-ca # HTTPS SSL/TLS certificates
    - phpmyadmin # Web based database client
    #- memcached-admin # Object cache management
    #- opcache-status # opcache management
    #- webgrind # PHP Debugging
    #- mongodb # needed for Tideways/XHGui
    #- tideways # PHP profiling tool, also installs xhgui check https://varyingvagrantvagrants.org/docs/en-US/references/tideways-xhgui/
    #- nvm # Node Version Manager
    #- php56
    #- php70
    #- php71
    #- php72
    #- php73
    - php74
    - yarn

# vm_config controls how Vagrant provisions the virtual machine, and can be used to
# increase the memory given to VVV and the number of CPU cores.
# It can also be used to override the default provider being used within Vagrant.

vm_config:
  # For WP core development we recommend at least 2GB ( 2048 ),
  # If you have 4GB of RAM, lower this to 768MB or you may encounter issues
  memory: 4096
  # CPU cores:
  cores: 2

  # this tells VVV to use the prebuilt box copied from the USB drive at contributor days
  # once set to false, do not change back to true, and reprovision
  # wordcamp_contributor_day_box: false

  # Due to a limitation within Vagrant, the specified provider is only respected on a clean `vagrant up`
  # as Vagrant currently restricts you to one provider per machine
  # https://www.vagrantup.com/docs/providers/basic_usage.html#vagrant-up
  # provider: virtualbox
  # provider: hyperv
  # provider: parallels
  # provider: vmware_desktop

# General VVV options
general:
  # Backup the databases to the database/backups subfolder on halt/suspend/destroy, set to false to disable
  db_backup: true
  # Import the databases if they're missing from backups
  db_restore: true
  # set to true to use a synced shared folder for MariaDB database storage
  db_share_type: false
  # GitHub token to use from composer
  #github_token: xxxxxx

# Settings for the vagrant plugins supported by VVV
vagrant-plugins:
  disksize: 50GB # requires the disk size vagrant plugin

```
