### ISSUE TITLE
Vagrant Up Fails MacOS Big Sur 11.4 ntupdate: command not found | install ntpdate manually, now Vagrant Provision errors

### ISSUE THREAD

**Issue by harrisonfm** [Varying-Vagrant-Vagrants/VVV#2482]
## What was The Command Used To Provision

`vagrant provision`

## What Kind of VVV Provision Was This

This was a reprovision of an already working VVV
then...
This was an attempt to upgrade to a new version of VVV

## Logs/What Broke

Update MacOS to Big Sur 11.4, Vagrant no longer works. I update VirtualBox, VVV, get `command ntpdate  not found` errors on vagrant up.

SSH into vagrant box, install ntpdate, vagrant up passes. Vagrant provision then fails.

```vagrant provision``` https://drive.google.com/file/d/1-aoh2kzwoWSkTbHax_20i2f_Y2vQcSSQ/view?usp=sharing

```yaml
hfm-2020:
    skip_provisioning: false
    description: ""
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - hfm.test
    custom:
      install_test_content: true
      delete_default_plugins: true
```

## Your Environment

```
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.6.2-git::master(cabaa3a)

Platform: platform-darwin19.2.0 shell:/bin/zsh vagrant-hostsupdater vagrant-goodhosts shared_db_folder_disabled, VVV Path: "/Users/harrisonjune/vvv"
Vagrant: v2.2.13, VirtualBox: v6.1.22r144080
```

Thanks for any help!
