### ISSUE TITLE
Q: multisite with subdirectories 404 on subsite wp-includes folder

### ISSUE THREAD

**Issue by pdewouters** [Varying-Vagrant-Vagrants/VVV#2569]
I have setup a new site with VVV, with the following config
```
  my-site:
    skip_provisioning: false
    description: "My Site"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - mysite.test
    custom:
      public_dir: site/public
      wp_type: none
```

I followed these steps:
- first copied the "wordpress-one" config and provisioned to have a default working WP install
- modified the config to the above, created the `site` directory and git cloned my existing repo into it. This contains a custom `content` and `wp` folders under a `public` directory. It uses an `.env` file for the WP constants such as `WP_HOME`, `WP_SITEURL`...
-  update the database values for home and siteurl and blogs table urls.

So I'm able to view the main site and visit the admin, but the network admin is a 404 - it is missing the `/wp/` part - if I add that manually I can access the network admin. And the other issue is that when I load a subsite, the path to `wp-includes` is a 404 too. e.g. `http://mysite.test/subsite/wp-includes/js/dist/wordcount.js?ver=83b86052fd3fc408a609e60d52164115`

The generated nginx config:
```
server {
    listen       80;
    listen       443 ssl http2;
    server_name  {vvv_hosts};
    root         "{vvv_path_to_site}/site/public";

    # Nginx logs
    error_log    "{vvv_path_to_site}/log/nginx-error.log";
    access_log   "{vvv_path_to_site}/log/nginx-access.log";

    # This is needed to set the PHP being used
    set          $upstream {upstream};

    # Enable server push if SSL/HTTP2 is being used for link preload headers
    http2_push_preload on;

    {vvv_tls_cert}
    {vvv_tls_key}

    # Nginx rules for WordPress, rewrite rules, permalinks, etc
    include      /etc/nginx/nginx-wp-common.conf;



    location ~* \.(css|eot|gif|ico|jpeg|jpg|js|png|svg|tiff|tiff|ttf|webp|woff|woff2)$ {
        expires 100d;
    }
}

```

Thanks!
