### ISSUE TITLE
Ability to specify/choose branch on sub-folder repositories.

### ISSUE THREAD

**Issue by karrycreativ** [Varying-Vagrant-Vagrants/VVV#2570]
I'd like to be able to specify the branch for sub-folder git repos.

**For example:**

```
my-site:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - mysite-test
    folders:
      public_html/wp-content/:
        git:
          repo: https://github.com/Automattic/vip-go-skeleton.git
          branch: develop
          overwrite_on_clone: true
```

While I could do this manually I feel as though it defeats the purpose of the feature especially since the top level repo can have a branch selected.
