### ISSUE TITLE
Lock CustomFile and custom main provisioners behind a flag

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2571]
**Describe alternatives you've considered**

We should follow composers lead and lock these features behind a `config.yml` flag so that they have to be explicitly turned on to work. Specifically, legacy features to replace the main provisioner or add custom hooks on triggers such as `CustomFile`, `provision-custom.sh` in the main `provision` folder, `pre-provision.sh`, files such as `vagrant_up_custom` etc in the `homebin` folder.

**Additional context**

Support for these features is only present for legacy reasons and because people are still using them. Removing them would require a VVV 4.0, but until then this should be dissuaded.

Ideally, VVV would notice these files exist, and show a clear warning message indicating that it found the file but will not use the file because permission has not been given, and that support is deprecated and going away in a future major version.

**Comment by tomjn** [comment]
Perhaps something like this:

```yaml
deprecated:
  enable_customfile: false
  enable_vagrant_custom: false
  enable_pre_provision: false
  enable_provision_custom: false
```
