### ISSUE TITLE
Issue: Problems Provisioning on Linux (php-pear : Depends: php-archive-tar (>= 1.4.9) but it is not installable)

### ISSUE THREAD

**Issue by GuiSCI** [Varying-Vagrant-Vagrants/VVV#2587]
Trying a clean install I found something's broken concerning dependencies. 
Tried it 3 times, twice with stable and once with development branch. Same result.

Hope this can be fixed :-)
Thanks,
Gui

```
Last part of provisioning:
    default: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: Some packages could not be installed. This may mean that you have
    default: requested an impossible situation or if you are using the unstable
    default: distribution that some required packages have not yet been created
    default: or been moved out of Incoming.
    default: The following information may help to resolve the situation:
    default: 
    default: The following packages have unmet dependencies:
    default:  php-pear : Depends: php-archive-tar (>= 1.4.9) but it is not installable
    default: E: Unable to correct problems, you have held broken packages.
    default:  * Installing apt-get packages returned a failure code, cleaning up apt caches then exiting
    default:  ! Main packages check and install failed, halting provision
    default:  ! The 'main' provisioner ran into problems, the full log is available at '/var/log/provisioners/2022.03.22_11-06-37/provisioner-main.log'. It completed in 193 seconds.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
 ```
