### ISSUE TITLE
vagrant provision fails - /root/.local/share/composer does not exist and could not be created

### ISSUE THREAD

**Issue by toddhalfpenny** [Varying-Vagrant-Vagrants/VVV#2589]
## What was The Command Used To Provision

```shell
vagrant up --provision
```

## What Kind of VVV Provision Was This

This was a fresh install

## Logs/What Broke

During fresh install and provision I get the following error

```==> default: Running provisioner: tools (shell)...
    default: Running: /tmp/vagrant-shell20220331-10209-fkqxg7.sh
    default:  ▷ Running the 'tools' provisioner...
    default:  ▷ Running tools_pre_setup hook
    default:  * [Composer]: Turning off PHP debug mods to avoid Composer performance issues
    default:  * Restarting PHP FPM services so that the change takes effect
    default:  ✔ All PHP Debug mods are now turned off.
    default:  ✔ Finished tools_pre_setup hook in 0s
    default:  ▷ Running tools_setup hook
    default:  * [Composer]: Checking if Composer is installed
    default:  * [Composer]: Running Composer Installer...
    default:  * [Composer]: Setting ownership and executable bit of composer...
    default:  * [Composer]: Moving composer into place...
    default:  * [Composer]: Installed to /usr/local/bin
    default:  * [Composer]: Making sure the Composer cache is not owned by root
    default:  * [Composer]: Checking for GitHub tokens
    default:  * [Composer]: Checking for Composer updates
    default:  * [Composer]: Updating Composer...
    default: 
    default: In Filesystem.php line 268:
    default: 
    default:   /root/.local/share/composer does not exist and could not be created.
    default: 
    default: 
    default: global <command-name> [<args>...]
    default: 
    default:  ! The 'tools' provisioner ran into problems, the full log is available at '/var/log/provisioners/2022.03.31_08-23-46/provisioner-tools.log'. It completed in 1 seconds.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

```yaml
sites:

  # latest version of WordPress, can be used for client work and testing
  # Check the readme at https://github.com/Varying-Vagrant-Vagrants/custom-site-template
  wordpress-one:
    skip_provisioning: false
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - one.wordpress.test
    custom:
      wpconfig_constants:
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true # To disable in WP 5.2 the FER mode

  wordpress-two:
    skip_provisioning: false
    description: "A standard WP install, useful for building plugins, testing things, etc"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      # locale: it_IT
      delete_default_plugins: true
      install_plugins:
        - query-monitor
    hosts:
      - two.wordpress.test

  # The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://mysite.test.
  # Remember, whitespace is significant! Tabs and spaces mean different things
  #mysite:
  #  description: "My website"
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    - mysite.test

  # The wordpress-develop configuration is useful for contributing to WordPress Core.
  # It uses the built WP to serve the site
  wordpress-trunk:
    skip_provisioning: true # provisioning this one takes longer, so it's disabled by default
    description: "An svn based WP Core trunk dev setup, useful for contributor days, Trac tickets, patches"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - trunk.wordpress.test

  # The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://my-example-site.test.
  # Remember, whitespace is significant! Tabs and spaces mean different things
  #example-site:
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    - my-example-site.test

# Extensions https://varyingvagrantvagrants.org/docs/en-US/utilities/
# are system level items that aren't websites, that install tools or packages
# the core extensions install tools such as phpmyadmin or new PHP versions
#
# these used to be called utilities but people kept requesting
# extensions not realising so it was renamed
extensions:
  core: # The core VVV extensions
    - tls-ca # HTTPS SSL/TLS certificates
    - phpmyadmin # Web based database client
    #- memcached-admin # Object cache management
    #- opcache-status # opcache management
    #- webgrind # PHP Debugging
    #- mongodb # needed for Tideways/XHGui
    #- tideways # PHP profiling tool, also installs xhgui check https://varyingvagrantvagrants.org/docs/en-US/references/tideways-xhgui/
    #- nvm # Node Version Manager
    #- php56
    #- php70
    #- php71
    #- php72
    #- php73
    #- php74
    #- php80

# vm_config controls how Vagrant provisions the virtual machine, and can be used to
# increase the memory given to VVV and the number of CPU cores.
# It can also be used to override the default provider being used within Vagrant.

vm_config:
  # For WP core development we recommend at least 2GB ( 2048 ),
  # If you have 4GB of RAM, lower this to 768MB or you may encounter issues
  #
  # For theme or plugin development 2GB is more than enough for page loads,
  # if you need more for web requests consider reducing your memory footprint.
  #
  # More memory won't speed things up.
  memory: 2048

  # How many virtual CPU cores, does not apply to Docker. Additional CPU cores
  # will only have a performance impact if you have those cores to spare and are
  # running heavy CLI tasks
  cores: 2

  # this tells VVV to use the prebuilt box copied from the USB drive at contributor days
  # once set to false, do not change back to true, and reprovision
  # wordcamp_contributor_day_box: false

  # Due to a limitation within Vagrant, the specified provider is only respected on a clean `vagrant up`
  # as Vagrant currently restricts you to one provider per machine
  # https://www.vagrantup.com/docs/providers/basic_usage.html#vagrant-up
  # provider: virtualbox
  # provider: hyperv
  # provider: parallels
  # provider: vmware_desktop

# General VVV options
general:

  # Back up Options
  # You can always backup/restore manually using vagrant ssh -c "db_backup" or vagrant ssh -c "db_restore"

  # Backup the databases to the database/backups subfolder on halt/suspend/destroy, set to false to disable
  db_backup:
      enable: false
      gzip: true
      #exclude:
      #  - wordpress-trunk

  # Import the databases if they're missing from backups
  db_restore: false

  # set to true to use a synced shared folder for MariaDB database storage
  db_share_type: false

  # GitHub token to use from composer
  #github_token: xxxxxx

# Settings for the vagrant plugins supported by VVV
vagrant-plugins:
  disksize: 10GB # requires the disk size vagrant plugin

```

## Steps to Reproduce (for bugs)
1. Just a fresh clone, and run up

[Full log gist here](https://gist.github.com/toddhalfpenny/9f05422b8fffe9a9e06f8b1a7611feda).

## Notes
- provision had previously failed as I needed to enable virtualization in the BIOS.
- Doing a `vagrant ssh` takes me in and I can see `/root/` but not a `/root/.local` directory

## Your Environment

- Ubuntu 20.04 (x86_64)
- Vagrant 2.2.19
- VirtualBox 6.1.32_Ubuntu r149290

**Comment by Mte90** [comment]
Did you tried `vagrant destroy && vagrant up`?

**Comment by toddhalfpenny** [comment]
Update: the removal and fresh install failed with the same error.
```
 * [Composer]: Updating Composer...
    default: 
    default: In Filesystem.php line 268:
    default: 
    default:   /root/.local/share/composer does not exist and could not be created.
```

**Comment by toddhalfpenny** [comment]
I have now done another run up but this time using VVV v3.8.1.
This says it has completed successfully, though I see the same error lines in the output;

```
▷ Running the 'tools' provisioner...
    default:  * Running tools_install
    default:  ▷ Running tools_setup hook
    default:    - Starting subhook composer_setup with priority 10
    default:    - Starting subhook grunt_setup with priority 10
    default:  * Turning off XDebug to avoid Composer performance issues
    default:    - Starting subhook wp_cli_setup with priority 10
    default:  * Installing/updating WP-CLI
    default:  * Downloading wp-cli nightly, see http://wp-cli.org
    default:  * Installing Grunt CLI
    default:  * Restarting PHP FPM services so that the change takes effect
    default:  ✔ All PHP Debug mods are now turned off.
    default:  * Checking if Composer is installed
    default:  * Installing Composer...
    default:  * Composer installer steps completed
    default:  * Making sure the Composer cache is not owned by root
    default:  * Checking for GitHub tokens
    default:  * Checking for Composer updates
    default:  * Updating Composer...
    default: 
    default: In Filesystem.php line 268:
    default: 
    default:   /root/.local/share/composer does not exist and could not be created.
    default: 
    default: 
    default: global <command-name> [<args>...]
    default: 
    default:  * WP CLI Nightly Installed

```

this time the install appears to continue though and I get 
```
31 Mar 09:46:15 ntpdate[70546]: adjust time server 91.189.89.198 offset 0.002386 sec
    default:  * clocks synced
    default: 
    default:    ✧ ✔ Success!       ✧    ✔              ✧    ✔ 
    default:  ✔ ▄▀▀▀▄▄▄▄▄▄▄▀▀▀▄ ✧           ✧       ✧         
    default:   ✧█▒▒░░░░░░░░░▒▒█  ✔    ✧           ✔       ✧   
    default: ✧   █░░█░░░░░█░░█ ✧        ✔      ✧      ✧       
    default:  ▄▄  █░░░▀█▀░░░█  ▄▄✧ ✔ Provisioning has finished!
    default: █░░█ ▀▄░░░░░░░▄▀ █░░█   Visit http://vvv.test
    default: 
==> default: Running action triggers after up ...
==> default: Running trigger: VVV Post-Up...
    default: Running: inline script
    default:  * Restarting Nginx
    default:  * Restarting MariaDB
    default:  * Syncing clocks
    default: 31 Mar 09:46:23 ntpdate[70780]: adjust time server 91.189.89.199 offset 0.000541 sec
    default:  * clocks synced
    default: 
    default:   ✧ ▄▀▀▀▄▄▄▄▄▄▄▀▀▀▄ ✧  Thanks for  __ __ __ __
    default:    ✧█▒▒░░░░░░░░░▒▒█    using       \ V\ V\ V /
    default:  ✧   █░░█░░░░░█░░█ ✧                \_/\_/\_/
    default:   ▄▄  █░░░▀█▀░░░█  ▄▄✧ 
    default:  █░░█ ▀▄░░░░░░░▄▀ █░░█ Vagrant Up has finished! Visit http://vvv.test
    default: ──────────────────────────────────────────────────────────────────────
```

Going now to http://vvv.test/ works just fine... so looks initially like it's OK.

Apologies if I was meant to have checked out 3.8.1 in the first place.

**Comment by tomjn** [comment]
is this the stable or develop branch?

**Comment by toddhalfpenny** [comment]
An initial clone of the repo takes you to `develop` by default, and that was the one that was failing.

I tried again on the `3.8.1` branch and that seems to work (though the logs still show the same initial compose error).

If I should have initially not run on the `develop` branch perhaps an additional line could be added to the install instructions to note that a checkout of the stable branch could be added?

**Comment by tomjn** [comment]
I actually use `develop` myself and we were considering a release of it to stable very soon

**Comment by toddhalfpenny** [comment]
Oh OK. 
If you want ,I'd be happy to try and help looking further into this? Though pretty sure I'd need assistance/direction as I'm not very familiar with composer or the provisioning.

**Comment by tomjn** [comment]
My two points of suspicion are either composers 2.3 release recently, or we
just need a mkdir-p adding

**Comment by toddhalfpenny** [comment]
Is there a way I can hard set a version of composer to be used? If so I'm happy to give this a whirl.

I thought about manually creating that directory, so went in with `vagrant ssh`, and it turns out the dir actually exists :/

```
vagrant@vvv:/$ sudo ls -la /root/.local/share/composer
total 16
drwxr-xr-x 3 vagrant www-data 4096 Mar 31 12:46 .
drwxr-xr-x 3 root    root     4096 Mar 31 12:46 ..
drwxr-xr-x 2 vagrant www-data 4096 Mar 31 12:46 cache
-rw-r--r-- 1 vagrant www-data   13 Mar 31 12:46 .htaccess
```

**Comment by toddhalfpenny** [comment]
Looks like it's [this function](https://github.com/composer/composer/blob/147c6a2f7eaba86daefbd2cff2e111168ffa1187/src/Composer/Util/Filesystem.php#L259) that's throwing the initial error.

Not sure why as the directory does seem to exist.
```
vagrant@vvv:~$ sudo ls -la /root/.local/share
total 12
drwxr-xr-x 3 root    root     4096 Mar 31 12:46 .
drwxr-xr-x 3 root    root     4096 Mar 31 12:46 ..
drwxr-xr-x 3 vagrant www-data 4096 Mar 31 12:46 composer
```
Wonder if it's an access-issue to that directory (e.g. is something not being run as root when it should)?

Be interesting to know if other also see the following logs in what look like to be successful provisions;
```
    default: IIn Filesystem.php line 268:
    default: 
    default:   /root/.local/share/composer does not exist and could not be created.
    default: 
    default: 
    default: global <command-name> [<args>...]
```
