### ISSUE TITLE
Bug: Connecctivity issue on ubuntu repositories

### ISSUE THREAD

**Issue by andreacomplus** [Varying-Vagrant-Vagrants/VVV#2654]
## What was The Command Used To Provision

```shell
vagrant up --provision
```

## What Kind of VVV Provision Was This

This was a fresh install

## Logs/What Broke
Cannot complete provision, some packages cannot be downloaded by the virtual machine.
```
 default: Get:173 http://in.archive.ubuntu.com/ubuntu focal-updates/universe amd64 webp amd64 0.6.1-2ubuntu0.20.04.1 [78.7 kB]
    default: Err:95 https://mirror.rackspace.com/mariadb/repo/10.5/ubuntu focal/main amd64 mariadb-client-core-10.5 amd64 1:10.5.18+maria~ubu2004
    default:   Connection timed out [IP: 72.4.120.219 443]
    default: Get:174 https://mirror.rackspace.com/mariadb/repo/10.5/ubuntu focal/main amd64 mariadb-client-10.5 amd64 1:10.5.18+maria~ubu2004 [1,602 kB]
    default: Get:175 https://mirror.rackspace.com/mariadb/repo/10.5/ubuntu focal/main amd64 mariadb-server-core-10.5 amd64 1:10.5.18+maria~ubu2004 [7,173 kB]
    default: Get:176 https://mirror.rackspace.com/mariadb/repo/10.5/ubuntu focal/main amd64 mariadb-server-10.5 amd64 1:10.5.18+maria~ubu2004 [4,532 kB]
    default: Get:177 https://mirror.rackspace.com/mariadb/repo/10.5/ubuntu focal/main amd64 mariadb-server all 1:10.5.18+maria~ubu2004 [3,224 B]
    default: Fetched 115 MB in 53s (2,162 kB/s)
    default: Unable to correct missing packages.
    default: E: Failed to fetch https://mirror.rackspace.com/mariadb/repo/10.5/ubuntu/pool/main/m/mariadb-10.5/mariadb-client-core-10.5_10.5.18+maria~ubu2004_amd64.deb  Connection timed out [IP: 72.4.120.219 443]
    default: E: Failed to fetch https://ppa.launchpadcontent.net/ondrej/php/ubuntu/pool/main/p/php7.4/php7.4-fpm_7.4.33-3+ubuntu20.04.1+deb.sury.org+1_amd64.deb  Undetermined Error [IP: 185.125.190.52 443]
    default: E: Failed to fetch https://ppa.launchpadcontent.net/ondrej/php/ubuntu/pool/main/x/xdebug/php7.4-xdebug_3.2.0+3.1.6+2.9.8+2.8.1+2.5.5-2+ubuntu20.04.1+deb.sury.org+1_amd64.deb  Undetermined Error [IP: 185.125.190.52 443]
    default: E: Aborting install.
    default:  * Installing apt-get packages returned a failure code, cleaning up apt caches then exiting
    default:  ! Main packages check and install failed, halting provision
    default:  ! The 'main' provisioner ran into problems, the full log is available at '/var/log/provisioners/2023.01.26_15-55-24/provisioner-main.log'. It completed in 79 seconds.
    default:  * Restoring the default PHP CLI version ( 7.4 )
    default: update-alternatives: error: no alternatives for php
    default: update-alternatives: error: no alternatives for phar
    default: update-alternatives: error: no alternatives for phar.phar
    default: update-alternatives: error: no alternatives for phpize
    default: update-alternatives: error: no alternatives for php-config
    default:  * Restoration complete
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

```yaml
---

# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

#
# IMPORTANT, if you change this file, you have to reprovision,  no exceptions
# Do this by running either this command:
# vagrant up --provision

# Or, if your machine is already turned on:
# vagrant provision
#

# These are your websites, and their names map on to the folders they're
# located in. See the docs for how to define these, and what all the keys
# and options are
sites:

  # latest version of WordPress, can be used for client work and testing
  # Check the readme at https://github.com/Varying-Vagrant-Vagrants/custom-site-template
  #  wordpress-one:
  #    skip_provisioning: false
  #    description: "A standard WP install, useful for building plugins, testing things, etc"
  #    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #    hosts:
  #      - one.wordpress.test
  #    custom:
  #      wpconfig_constants:
  #        WP_DEBUG: true
  #        WP_DEBUG_LOG: true
  #        WP_DISABLE_FATAL_ERROR_HANDLER: true # To disable in WP 5.2 the FER mode
  #
  #  wordpress-two:
  #    skip_provisioning: false
  #    description: "A standard WP install, useful for building plugins, testing things, etc"
  #    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #    custom:
  #      # locale: fr_FR
  #      delete_default_plugins: true
  #      install_plugins:
  #        - query-monitor
  #    hosts:
  #      - two.wordpress.test

  # The following commented out site configuration will create a standard WordPress
  # site in www/example-site/ available at http://mysite.test.
  # Remember, whitespace is significant! Tabs and spaces mean different things
  #mysite:
  #  description: "My website"
  #  repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #  hosts:
  #    - mysite.test

  mysite:
    description: "mysite"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    php: 8.1
    nginx_upstream: php81
    hosts:
      - mysite.test
    custom:
      delete_default_plugins: true
      locale: en_US
    skip_provisioning: true

# Extensions https://varyingvagrantvagrants.org/docs/en-US/utilities/
# are system level items that aren't websites, that install tools or packages
# the core extensions install tools such as phpmyadmin or new PHP versions
#
# these used to be called utilities but people kept requesting
# extensions not realising so it was renamed
extensions:
  core: # The core VVV extensions
    - tls-ca # HTTPS SSL/TLS certificates
    - phpmyadmin # Web based database client
    - php80
    - php81
    #- memcached-admin # Object cache management
    #- opcache-status # opcache management
    #- webgrind # PHP Debugging
    #- mongodb # needed for Tideways/XHGui
    #- tideways # PHP profiling tool, also installs xhgui check https://varyingvagrantvagrants.org/docs/en-US/references/tideways-xhgui/
    #- nvm # Node Version Manager
    #- php56
    #- php70
    - php71
    #- php72
    #- php73
    - php74

# vm_config controls how Vagrant provisions the virtual machine, and can be used to
# increase the memory given to VVV and the number of CPU cores.
# It can also be used to override the default provider being used within Vagrant.

vm_config:
  # For WP core development we recommend at least 2GB ( 2048 ),
  # If you have 4GB of RAM, lower this to 768MB or you may encounter issues
  #
  # For theme or plugin development 2GB is more than enough for page loads,
  # if you need more for web requests consider reducing your memory footprint.
  #
  # More memory won't speed things up.
  memory: 2048

  # How many virtual CPU cores, does not apply to Docker. Additional CPU cores
  # will only have a performance impact if you have those cores to spare and are
  # running heavy CLI tasks
  cores: 2

  # this tells VVV to use the prebuilt box copied from the USB drive at contributor days
  # once set to false, do not change back to true, and reprovision
  # wordcamp_contributor_day_box: false

  # Due to a limitation within Vagrant, the specified provider is only respected on a clean `vagrant up`
  # as Vagrant currently restricts you to one provider per machine
  # https://www.vagrantup.com/docs/providers/basic_usage.html#vagrant-up
  # provider: virtualbox
  # provider: hyperv
  # provider: parallels
  # provider: vmware_desktop

# General VVV options
general:

  # Back up Options
  # You can always backup/restore manually using vagrant ssh -c "db_backup" or vagrant ssh -c "db_restore"

  # Backup the databases to the database/backups subfolder on halt/suspend/destroy, set to false to disable
  db_backup:
    enable: false
    gzip: true
    #exclude:
    #  - wordpress-trunk

  # Import the databases if they're missing from backups
  db_restore: false

  # set to true to use a synced shared folder for MariaDB database storage
  db_share_type: false

  # GitHub token to use from composer
  #github_token: xxxxxx

# Settings for the vagrant plugins supported by VVV
vagrant-plugins:
  disksize: 10GB # requires the disk size vagrant plugin


# config.vm.box_check_update = false
config:
  vm:
    box_check_update: false

```

## Steps to Reproduce (for bugs)

1. Clone repository
2. Switch to develop or stable branch, both will fail
3. Run vagrant up --provision

## Your Environment

Operating System: Windows

```
$ vagrant up --provision
__ __ __ __
\ V\ V\ V / v3.11 Ruby:2.7.6, Path:"D:/dev/vvv-local"
 \_/\_/\_/  git::develop(fb684b5d)

Platform: mingw32 windows  missingWinAdminPriv  vagrant-goodhosts monochrome-terminal shared_db_folder_disabled
Vagrant: v2.3.3,
```
