### ISSUE TITLE
Bug:  core dev site template failing

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2671]
### Are you using the latest stable or develop branch version of VVV?

Yes (develop)

### Is it a new VVV, or an existing VVV that used to work?

Existing, worked but now broken

### Did you use a CustomFile?

No (default)

### Whats the problem?

Provisioning a fresh core dev site template fails with a 403 forbidden, and shows this error in the provisioner log:

```
    default: vvv-init.sh: line 191: try_grunt_build: command not found
```

### How do we reproduce it?

```
  trunky:
    skip_provisioning: false # provisioning this one takes longer, so it's disabled by default
    description: "An svn based WP Core trunk dev setup, useful for contributor days, Trac tickets, patches"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - trunky.test
 ```

### What is the output of `vagrant status`

```shell
❯ vagrant status
__ __ __ __
\ V\ V\ V / v3.11.3 Ruby:3.1.4, Path:"/Users/tomjn/vvv-local"
 \_/\_/\_/  git::develop(d7b96f67)

Platform: darwin shell:/bin/zsh vagrant-goodhosts shared_db_folder_disabled
Vagrant: v2.3.6, parallels: v18.2.0

Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Current machine states:

default                   running (parallels)

The VM is running. To stop this VM, you can run `vagrant halt` to
shut it down forcefully, or you can run `vagrant suspend` to simply
suspend the virtual machine. In either case, to restart it again,
simply run `vagrant up`.
```

### Which Operating System are you using?

Apple MacOS (Arm64/Apple Silicon)

### Which provider are you using?

Parallels (Apple Silicon/Arm)
