### ISSUE TITLE
Bug: Windows: Network connection issues found. Unable to reach 

### ISSUE THREAD

**Issue by adamo** [Varying-Vagrant-Vagrants/VVV#2707]
## What was The Command Used To Provision

```shell
vagrant up --provision
```

## What Kind of VVV Provision Was This
This was a reprovision of an already working VVV

## Logs/What Broke

I've tried to add a new site and provision but got errors connecting to hosts. 

```
[0;38;5;2m ▷ Running the [0m[1m[0;38;5;5m'main'[21m[0;38;5;2m provisioner...[0m[0m[0m
[0m[39m[2m ▷ Running [0m[1m[0;38;5;5minit[21m[0m[39m[2m hook[21m[0m
[0m[39m[2m * Bash profile setup and directories.[21m[0m
[0m[39m[2m * Reloading SSH Daemon[21m[0m
[0m[39m[2m * checking Ubuntu version[21m[0m
[0;38;5;2m ✔ Finished [0m[1m[0;38;5;5minit[21m[0;38;5;2m hook in [0m[0m[1m[0;38;5;5m19s[21m[0m[0m
[0m[39m[2m * Testing network connection to [0m[4;38;5;3mhttps://ppa.launchpadcontent.net[0m with wget -q --spider --timeout=5 --tries=3 https://ppa.launchpadcontent.net[21m[0m
[0;38;5;9m ! Network connection issues found. Unable to reach [0m[4;38;5;3mhttps://ppa.launchpadcontent.net[0m[0m[0m
[0m[39m[2m * Testing network connection to [0m[4;38;5;3mhttps://wordpress.org[0m with wget -q --spider --timeout=5 --tries=3 https://wordpress.org[21m[0m
[0;38;5;9m ! Network connection issues found. Unable to reach [0m[4;38;5;3mhttps://wordpress.org[0m[0m[0m
[0m[39m[2m * Testing network connection to [0m[4;38;5;3mhttps://github.com[0m with wget -q --spider --timeout=5 --tries=3 https://github.com[21m[0m
[0;38;5;9m ! Network connection issues found. Unable to reach [0m[4;38;5;3mhttps://github.com[0m[0m[0m
[0m[39m[2m * Testing network connection to [0m[4;38;5;3mhttps://raw.githubusercontent.com[0m with wget -q --spider --timeout=5 --tries=3 https://raw.githubusercontent.com[21m[0m
[0;38;5;9m ! Network connection issues found. Unable to reach [0m[4;38;5;3mhttps://raw.githubusercontent.com[0m[0m[0m
[0m[39m[2m * Testing network connection to [0m[4;38;5;3mhttps://getcomposer.org[0m with wget -q --spider --timeout=5 --tries=3 https://getcomposer.org[21m[0m
[0;38;5;9m ! Network connection issues found. Unable to reach [0m[4;38;5;3mhttps://getcomposer.org[0m[0m[0m
[0m[39m[2m * Testing network connection to [0m[4;38;5;3mhttps://deb.nodesource.com[0m with wget -q --spider --timeout=5 --tries=3 https://deb.nodesource.com[21m[0m
[0;38;5;9m ! Network connection issues found. Unable to reach [0m[4;38;5;3mhttps://deb.nodesource.com[0m[0m[0m
[0m[39m[2m * Testing network connection to [0m[4;38;5;3mhttps://mirror.rackspace.com[0m with wget -q --spider --timeout=5 --tries=3 https://mirror.rackspace.com[21m[0m
[0;38;5;9m ! Network connection issues found. Unable to reach [0m[4;38;5;3mhttps://mirror.rackspace.com[0m[0m[0m
[0;38;5;9m#################################################################[0m[0m
[0;38;5;9m [0m[0m
[0;38;5;9m! Warning! Network Problems:[0m[0m
[0;38;5;9m [0m[0m
[0;38;5;9mVVV tried to check several domains it needs for provisioning but 7 of 7 failed:[0m[0m
[0;38;5;9m [0m[0m
[0m [[0;38;5;9mx[0m] https://ppa.launchpadcontent.net[0;38;5;9m|
[0m [[0;38;5;9mx[0m] https://wordpress.org[0;38;5;9m|
[0m [[0;38;5;9mx[0m] https://github.com[0;38;5;9m|
[0m [[0;38;5;9mx[0m] https://raw.githubusercontent.com[0;38;5;9m|
[0m [[0;38;5;9mx[0m] https://getcomposer.org[0;38;5;9m|
[0m [[0;38;5;9mx[0m] https://deb.nodesource.com[0;38;5;9m|
[0m [[0;38;5;9mx[0m] https://mirror.rackspace.com[0;38;5;9m|
[0;38;5;9m [0m[0m
[0;38;5;9mMake sure you have a working internet connection, that you [0m[0m
[0;38;5;9mrestarted after installing VirtualBox/Parallels/Vagrant, and that [0m[0m
[0;38;5;9mthey aren't blocked by a firewall or security software.[0m[0m
[0;38;5;9mIf you can load the address in your browser, then VVV should[0m[0m
[0;38;5;9mbe able to connect.[0m[0m
[0;38;5;9m [0m[0m
[0;38;5;9mAlso note that some users have reported issues when combined[0m[0m
[0;38;5;9mwith VPNs, disable your VPN and reprovision to see if this is[0m[0m
[0;38;5;9mthe cause.[0m[0m
[0;38;5;9m [0m[0m
[0;38;5;9mAdditionally, if you're at a contributor day event, be kind,[0m[0m
[0;38;5;9mprovisioning involves downloading things, a full provision may [0m[0m
[0;38;5;9mruin the wifi for everybody else :([0m[0m
[0;38;5;9m [0m[0m
[0;38;5;9mNetwork ifconfig output:[0m[0m
[0;38;5;9m [0m[0m
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::a00:27ff:feb1:285d  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:b1:28:5d  txqueuelen 1000  (Ethernet)
        RX packets 3049  bytes 356876 (356.8 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2258  bytes 391211 (391.2 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.56.4  netmask 255.255.255.0  broadcast 192.168.56.255
        inet6 fe80::a00:27ff:fe92:a226  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:92:a2:26  txqueuelen 1000  (Ethernet)
        RX packets 13  bytes 2734 (2.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 51  bytes 6764 (6.7 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 128  bytes 10544 (10.5 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 128  bytes 10544 (10.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[0;38;5;9m [0m[0m
[0;38;5;9mTry provisioning again once network connectivity is restored.[0m[0m
[0;38;5;9mIf that doesn't work, and you're sure you have no VPNs and a strong [0m[0m
[0;38;5;9minternet connection, open an issue on GitHub, and include the [0m[0m
[0;38;5;9moutput above so that the problem can be debugged[0m[0m
[0;38;5;9m [0m[0m
[0;38;5;9mvagrant halt[0m[0m
[0;38;5;9mvagrant up --provision[0m[0m
[0;38;5;9m [0m[0m
[0;38;5;9m[0m[4;38;5;3mhttps://github.com/Varying-Vagrant-Vagrants/VVV/issues[0m[0m[0m
[0;38;5;9m [0m[0m
[0;38;5;9m#################################################################[0m[0m
[0;38;5;3m ==================================================================================================[0m[0m
[0;38;5;3m ! If this check fails despite succeeding in the browser, contact us in Slack or GitHub immediately[0m[0m
[0;38;5;3m ==================================================================================================[0m[0m
[0m[39m[2m * Apt package install pre-checks[21m[0m
[0m[39m[2m ▷ Running [0m[1m[0;38;5;5mbefore_packages[21m[0m[39m[2m hook[21m[0m
[0m[39m[2m * Setting up MySQL configuration file links...[21m[0m
[0m[39m[2m * mysql group exists[21m[0m
[0m[39m[2m * mysql user present and has uid 9001[21m[0m
[0m[39m[2m * Copying /srv/provision/core/mariadb/config/vvv-core.cnf to /etc/mysql/conf.d/vvv-core.cnf[21m[0m
[0m[39m[2m * Copying PHP configs[21m[0m
[0m[39m[2m * Checking supplementary PHP configs[21m[0m
[0;38;5;2m ✔ Finished [0m[1m[0;38;5;5mbefore_packages[21m[0;38;5;2m hook in [0m[0m[1m[0;38;5;5m0s[21m[0m[0m
[0m[39m[2m * Registering apt keys[21m[0m
[0m[39m[2m ▷ Running [0m[1m[0;38;5;5mregister_apt_keys[21m[0m[39m[2m hook[21m[0m
[0;38;5;2m ✔ Finished [0m[1m[0;38;5;5mregister_apt_keys[21m[0;38;5;2m hook in [0m[0m[1m[0;38;5;5m1s[21m[0m[0m
[0m[39m[2m * Registering apt sources[21m[0m
[0m[39m[2m ▷ Running [0m[1m[0;38;5;5mregister_apt_sources[21m[0m[39m[2m hook[21m[0m
[0m[39m[2m * git-core/ppa already present, skipping[21m[0m
[0m[39m[2m * installing MariaDB apt sources[21m[0m
[0;38;5;2m ✔ Finished [0m[1m[0;38;5;5mregister_apt_sources[21m[0;38;5;2m hook in [0m[0m[1m[0;38;5;5m0s[21m[0m[0m
[0m[39m[2m * Upgrading apt packages[21m[0m
[0m[39m[2m * Updating apt keys[21m[0m
gpg: key 3B4FE6ACC0B21F32: 3 signatures not checked due to missing keys
gpg: key 3B4FE6ACC0B21F32: "Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>" not changed
gpg: key D94AA3F0EFE21092: 3 signatures not checked due to missing keys
gpg: key D94AA3F0EFE21092: "Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>" not changed
gpg: key 871920D1991BC93C: 1 signature not checked due to a missing key
gpg: key 871920D1991BC93C: "Ubuntu Archive Automatic Signing Key (2018) <ftpmaster@ubuntu.com>" not changed
gpg: Total number processed: 3
gpg:              unchanged: 3
[0m[39m[2m * Running apt-get update...[21m[0m
Err:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
  Temporary failure resolving 'us.archive.ubuntu.com'
Err:2 http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease
  Temporary failure resolving 'ppa.launchpad.net'
Err:3 https://mirror.rackspace.com/mariadb/repo/10.5/ubuntu focal InRelease
  Temporary failure resolving 'mirror.rackspace.com'
Err:4 https://nginx.org/packages/mainline/ubuntu focal InRelease
  Temporary failure resolving 'nginx.org'
Err:5 https://ppa.launchpadcontent.net/ondrej/php/ubuntu focal InRelease
  Temporary failure resolving 'ppa.launchpadcontent.net'
Err:6 https://packagecloud.io/github/git-lfs/ubuntu focal InRelease
  Temporary failure resolving 'packagecloud.io'
Err:7 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease
  Temporary failure resolving 'us.archive.ubuntu.com'
Err:8 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease
  Temporary failure resolving 'us.archive.ubuntu.com'
Err:9 http://us.archive.ubuntu.com/ubuntu focal-security InRelease
  Temporary failure resolving 'us.archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'us.archive.ubuntu.com'
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'us.archive.ubuntu.com'
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Temporary failure resolving 'us.archive.ubuntu.com'
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'us.archive.ubuntu.com'
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/focal/InRelease  Temporary failure resolving 'ppa.launchpad.net'
W: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/focal/InRelease  Temporary failure resolving 'packagecloud.io'
W: Failed to fetch https://mirror.rackspace.com/mariadb/repo/10.5/ubuntu/dists/focal/InRelease  Temporary failure resolving 'mirror.rackspace.com'
W: Failed to fetch https://nginx.org/packages/mainline/ubuntu/dists/focal/InRelease  Temporary failure resolving 'nginx.org'
W: Failed to fetch https://ppa.launchpadcontent.net/ondrej/php/ubuntu/dists/focal/InRelease  Temporary failure resolving 'ppa.launchpadcontent.net'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[0m[39m[2m * Registering apt packages to install[21m[0m
[0m[39m[2m ▷ Running [0m[1m[0;38;5;5mregister_apt_packages[21m[0m[39m[2m hook[21m[0m
[0;38;5;2m ✔ Finished [0m[1m[0;38;5;5mregister_apt_packages[21m[0;38;5;2m hook in [0m[0m[1m[0;38;5;5m0s[21m[0m[0m
[0m[39m[2m * Main packages check and install.[21m[0m
[0m[39m[2m * Checking for apt packages to remove.[21m[0m
[0m[39m[2m * No apt packages to remove[21m[0m
[0m[39m[2m * Checking for apt packages to install.[21m[0m
[0m[39m[2m * No apt packages to install[21m[0m
[0m[39m[2m * Running after_packages[21m[0m
[0m[39m[2m ▷ Running [0m[1m[0;38;5;5mafter_packages[21m[0m[39m[2m hook[21m[0m
false
false
[0m[39m[2m * Adding Mailhog service file[21m[0m
[0m[39m[2m * Enabling MailHog Service[21m[0m
[0m[39m[2m * Starting MailHog Service[21m[0m
[0m[39m[2m * Started MailHog Service[21m[0m
[0m[39m[2m * Checking for NVM[21m[0m
[0;38;5;2m ✓ NVM is already installed, checking for updates[0m[0m
fatal: unable to access 'https://github.com/nvm-sh/nvm.git/': Could not resolve host: github.com
[0;38;5;9m ! The [0m[1m[0;38;5;5m'main'[21m[0;38;5;9m provisioner ran into problems, the full log is available at [0m[1m[0;38;5;5m'/var/log/provisioners/2024.06.11_13-49-05/provisioner-main.log'[21m[0;38;5;9m. It completed in [0m[1m[0;38;5;5m161[21m[0;38;5;9m seconds.[0m[0m
```

```yaml
---
sites:
  # latest version of WordPress, can be used for client work and testing
  # Check the readme at https://github.com/Varying-Vagrant-Vagrants/custom-site-template
  # wordpress-one:
  #   skip_provisioning: false
  #   description: "A standard WP install, useful for building plugins, testing things, etc"
  #   repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
  #   hosts:
  #     - one.wordpress.test
  #   custom:
  #     wpconfig_constants:
  #       WP_DEBUG: true
  #       WP_DEBUG_LOG: true
  #       WP_DISABLE_FATAL_ERROR_HANDLER: true # To disable in WP 5.2 the FER mode

  piwnicasmakow:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - piwnicasmakow.test
    custom:
      wp_type: none
    nginx_upstream: php83

  brixani:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - brixani.test
    nginx_upstream: php80

  excitingpoland:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - excitingpoland.test
    nginx_upstream: php80

  greenfox:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - greenfox.test
    nginx_upstream: php80

  amtrener:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - amtrener.test
    nginx_upstream: php80

  base:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - base.test
    custom:
      wp_type: none
    nginx_upstream: php83

  cedo:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - cedo.test
    custom:
      wp_type: none
    nginx_upstream: php83

  paluchruda:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - paluchruda.test
    custom:
      wp_type: none
    nginx_upstream: php83

  inspiracje:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - inspiracje.test
    custom:
      wp_type: none
    nginx_upstream: php80

  depcoreagency:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - depcoreagency.test
    custom:
      wp_type: none
    nginx_upstream: php83

  depcore:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - depcore.test
    custom:
      wp_type: none
    nginx_upstream: php83

  gfp:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - gfp.test
    custom:
      wp_type: none
    nginx_upstream: php83

  vidocq:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - vidocq.test
    custom:
      wp_type: none
    nginx_upstream: php83

  opinia:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - opinia.test
    custom:
      wp_type: none
    nginx_upstream: php83

  pickpocket:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - pickpocket.test
    custom:
      wp_type: none
    nginx_upstream: php83

  prodoo:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - prodoo.test
    custom:
      wp_type: none
    nginx_upstream: php83

  tias:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - tias.test
    custom:
      wp_type: none
    nginx_upstream: php83

  paclan:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - paclan.test
    custom:
      wp_type: none
    nginx_upstream: php83

extensions:
  core: # The core VVV extensions
    - tls-ca # HTTPS SSL/TLS certificates
    - phpmyadmin # Web based database client
    #- memcached-admin # Object cache management
    #- opcache-status # opcache management
    #- webgrind # PHP Debugging
    #- mongodb # needed for Tideways/XHGui
    #- tideways # PHP profiling tool, also installs xhgui check https://varyingvagrantvagrants.org/docs/en-US/references/tideways-xhgui/
    - nvm # Node Version Manager
    #- php74
    - php80
    - php81
    - php83

# vm_config controls how Vagrant provisions the virtual machine, and can be used to
# increase the memory given to VVV and the number of CPU cores.
# It can also be used to override the default provider being used within Vagrant.

vm_config:
  memory: 2048
  cores: 2
  # as Vagrant currently restricts you to one provider per machine
  # https://www.vagrantup.com/docs/providers/basic_usage.html#vagrant-up
  # provider: virtualbox
  # provider: hyperv
  # provider: parallels
  # provider: vmware_desktop
  # provider: docker

# General VVV options
general:
  db_backup:
    enable: false
    gzip: true
    #exclude:
    #  - wordpress-trunk

  db_restore: false
  db_share_type: false
  #github_token: xxxxxx

vagrant-plugins:
  disksize: 10GB # requires the disk size vagrant plugin

```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

Operating System: Windows

__ __ __ __
\ V\ V\ V / v3.13 Ruby:3.1.4, Path:"C:/strony/sites"
 \_/\_/\_/  git::develop(c4250187)

Platform: mingw32 windows  missingWinAdminPriv  vagrant-hostsupdater vagrant-goodhosts vagrant-vbguest monochrome-terminal shared_db_folder_disabled
Vagrant: v2.4.1, virtualbox: v7.0.18
