### ISSUE TITLE
Bug: Fresh install leads to Nginx 404 error due to wrong path in default site template

### ISSUE THREAD

**Issue by tlartaud** [Varying-Vagrant-Vagrants/VVV#2729]
### Are you using the latest stable or develop branch version of VVV?

No

### Is it a new VVV, or an existing VVV that used to work?

Existing, worked but now broken

### Did you use a CustomFile?

No (default)

### Whats the problem?

I'm using a VVV instance for years, which has always worked, and I needed to destroy it to move from VMware to vBox.
I did not change anything, but after I provisionned the VM, I got a Nginx 404 error (with a brand new design I never saw btw ^^).

To fix that, I had to fix a wrong path in `public_html/vvv-nginx-default.conf`, which is generated from the [official VVV's template](https://github.com/Varying-Vagrant-Vagrants/custom-site-template/blob/master/provision/vvv-nginx-default.conf) and restart Nginx.

The generated template includes this line:
```
root         "{vvv_path_to_site}{vvv_public_dir}";
```

while, I guess, it should be:
```
root         "{vvv_path_to_site}/{vvv_public_dir}";
```

> Notice the missing `/` character.
> The resulting path on the VM looks like `wordpress-localpublic_html` which is wrong.

After I modified this path, Nginx stopped complaining.

However, what I can't get out of my mind is the following:
How is that possible that this template, including this typo, worked for years and somehow now stopped working?
The only issue I faced while I re-provisionned again is about the new nginx signing key that expired last month. I fixed that from one of the VVV's latest commit, but is there an issue with an older Nginx version? How Nginx was actually able to reach out the correct path and display the site while the root path was incorrect and missing a `/`? This mystery is actually making me losing my mind ^^

### How do we reproduce it?

Just provision a new VVV instance by using the default site template in `config.yml` I guess ?
```
repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
```

### What is the output of `vagrant status`

```shell
.
```

### Which Operating System are you using?

Microsoft Windows

### Which provider are you using?

VirtualBox 7

**Comment by tomjn** [comment]
> The only issue I faced while I re-provisionned again is about the new nginx signing key that expired last month. I fixed that from one of the VVV's latest commit, but is there an issue with an older Nginx version? How Nginx was actually able to reach out the correct path and display the site while the root path was incorrect and missing a /? This mystery is actually making me losing my mind ^^

This is perplexing though it's possible you had an out of date site template repo, e.g. if you'd made changes and `git` considered it to have working directory changes. A lot of the provisioner assumes `vvv_path_to_site` has no trailing slash

This is the commit that removed the slash: https://github.com/Varying-Vagrant-Vagrants/custom-site-template/commit/cf7c0c30d9a68709c8d28071f8cc6cb48210c688

**Comment by tomjn** [comment]
Does the site in question use a custom public directory?

**Comment by tlartaud** [comment]
Thank you for your really fast answer, this is appreciated.

> it's possible you had an out of date site template repo
I'm not sure, this VVV instance has been initiated years ago, but my `config.yml` file is just a standard one, using the default template from your git repository:
```
  wordpress-local:
    skip_provisioning: false
    allow_customfile: true
    description: "The default WPCA build environment - local.wordpress.test"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    hosts:
      - local.wordpress.test
    custom:
      locale: fr_FR
      delete_default_plugins: true
      install_plugins:
        - query-monitor
        - disable-emails
        - log-emails
      wpconfig_constants:
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true # To disable in WP 5.2 the FER mode
        WP_ENV: development
        SAVEQUERIES: true
        WP_DEBUG_DISPLAY: true
        SCRIPT_DEBUG: true
```

> This is the commit that removed the slash
This is interesting. If you removed the slash, you actually assume, I guess, that `vvv_public_dir`  includes a slash as its first character, right? So it should be `/public_html`, and not just `public_html`, right?

Because if I look at the other paths from the template file, they include a slash:
```
error_log    "{vvv_path_to_site}/log/nginx-error.log";
```

The problem is that the resulting output, for me, in the conf file generated on the guest, while I today destroyed and re-provisioned, was including `wordpress-localpublic_html` instead of `wordpress-local/public_html`.

> Does the site in question use a custom public directory?
The thing is, I did not modified the default structure. My default Wordpress installation path is simply `vagrant/www/wordpress-local/public_html` (`vagrant/` folder from the host ofc, else `srv/` from the guest).

I am still confused I must admit.
