### ISSUE TITLE
Q: `custom:` list of parameters in config.yml does not produce results

### ISSUE THREAD

**Issue by cleantext** [Varying-Vagrant-Vagrants/VVV#2752]
Hi,

I added a new website to my config.yml and needed to specify a bunch of custom parameters I got from the GitHub page for the custom site template. The config.yml snippet and `vagrant status` are pasted below.

Notes: 
* I've commented out the problematic lines. 
* The order of all parameters is preserved from the original file.
* Spaces and text formatting is as expected from a yaml file.

Thanks!

**config.yml snippet**

```
  coolsite:
    description: "Website description."
    skip_provisioning: false
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    php: 8.0
    custom: # All custom properties at: https://github.com/Varying-Vagrant-Vagrants/custom-site-template
      wp_type: none
      delete_default_plugins: true
      locale: bg_BG
      install_plugins:
        - wps-hide-login
        - query-monitor
      #  wpconfig_constants: <!-- these do not work START
      #  WP_DEBUG: true
      #  WP_DEBUG_LOG: true
      #  WP_DISABLE_FATAL_ERROR_HANDLER: true
      #  FORCE_SSL_ADMIN: true
      #  WP_AUTO_UPDATE_CORE: minor
      #  TABLE_PREFIX: uoia_
      #db_prefix: uoia_
      #admin_user: wordmin <!-- these do not work END
      wp_version: 5.8.10
    hosts:
      - coolsite.test
```

**`vagrant status` output**

```
__ __ __ __
\ V\ V\ V / v3.13.1 Ruby:3.3.6, Path:"/home/himynameis/vvv-local"
 \_/\_/\_/  git::stable(f3ef893a)

Platform: linux shell:/bin/bash systemd  vagrant-goodhosts CaseSensitiveFS shared_db_folder_disabled
Vagrant: v2.4.3, virtualbox: v7.0.20
```

**Comment by tomjn** [comment]
There's a few updates you should get, cute but stable should be 3.14 not 3.13.

As for the parameters, when you added them did the site already exist? Those parameters won't modify a site, they're for the initial creation

**Comment by tomjn** [comment]
Also you've specified your wp_type as none which indicates that you don't want it to do anything, and that you'll be managing it yourself

**Comment by cleantext** [comment]
Ah, I knew I'd screw something up with my reporting :-)

This is my current working config you're looking at. I tried with `custom`, it didn't work with either `vagrant provision` or `vagrant provision --with-site site-coolsite`. I tried deleting and recreating the site multiple times. During this time there was no `wp_type` in the config.

I don't use config.yml to modify existing websites.

Once I gave up on using `custom`, I moved to `wp-cli` for a more scripted approach to trying different configurations of WP. That's when I added `wp_type: none`.

I'm not sure I'll be doing any updates soon, though. Which is kind of stupid to say out loud given the topic. I only update when I have time to (eventually) debug... Isn't `custom` supposed to work in 3.13 as well?

And thanks for the quick reply.

**Comment by tomjn** [comment]
> I'm not sure I'll be doing any updates soon, though. Which is kind of stupid to say out loud given the topic. I only update when I have time to (eventually) debug... Isn't custom supposed to work in 3.13 as well?

Mainly because 3.14 has important fixes for the main provisioner, I would not expect a `vagrant up --provision` under 3.13 to be reliably successful, most likely failing to fetch MariaDB packages from the mirror it uses that was replaced.

> This is my current working config you're looking at. I tried with custom, it didn't work with either vagrant provision or vagrant provision --with-site site-coolsite. I tried deleting and recreating the site multiple times. During this time there was no wp_type in the config.

When you say deleting are you just removing the folder then reprovisioning?

Looking at your original issue and the commented out section it's not clear what the indentation of the uncommented version is. A naive removal of the `#` implies a mistake in indenting, can you undo the commenting out and share the actual indentation you used? As well as the log from the site provisioner?

**Comment by tomjn** [comment]
For context, VVV itself does nothing with the contents of `custom:`, that's entirely up to the site provisioner to work with, aka https://github.com/Varying-Vagrant-Vagrants/custom-site-template/blob/master/provision/vvv-init.sh, it's also why the documentation for those parameters are on that repo, and those parameters only work for that repo.

<blockquote><img src="https://opengraph.githubassets.com/4ab87bfaed34a402a4848c08819709b9d5ac5abf6d9f75125db3f4efe852e23a/Varying-Vagrant-Vagrants/custom-site-template" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Varying-Vagrant-Vagrants/custom-site-template/blob/master/provision/vvv-init.sh">custom-site-template/provision/vvv-init.sh at master · Varying-Vagrant-Vagrants/custom-site-template</a></strong></div><div>A site provisioner for VVV. Contribute to Varying-Vagrant-Vagrants/custom-site-template development by creating an account on GitHub.</div></blockquote>

**Comment by tomjn** [comment]
This bash function specifically is responsible for handling wp config constants:

https://github.com/Varying-Vagrant-Vagrants/custom-site-template/blob/master/provision/vvv-init.sh#L158

If I remove the comments, it heavily implies that your `wpconfig_constants` has the same indentation as the `install_plugins`, and that we're seeing a YAML syntax issue here:

```yaml
  coolsite:
    description: "Website description."
    skip_provisioning: false
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    php: 8.0
    custom: # All custom properties at: https://github.com/Varying-Vagrant-Vagrants/custom-site-template
      wp_type: none
      delete_default_plugins: true
      locale: bg_BG
      install_plugins:
        - wps-hide-login
        - query-monitor
        wpconfig_constants: <!-- these do not work START
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true
        FORCE_SSL_ADMIN: true
        WP_AUTO_UPDATE_CORE: minor
        TABLE_PREFIX: uoia_
      db_prefix: uoia_
      admin_user: wordmin <!-- these do not work END
      wp_version: 5.8.10
    hosts:
      - coolsite.test
```

I would also expect to see lines such as ` * Adding constant 'FORCE_SSL_ADMIN' with value 'true' to wp-config.php`, though without the output of the site provisioner I can't tell.

Instead I would expect to see something like this:
```yaml
      install_plugins:
        - wps-hide-login
        - query-monitor
      wpconfig_constants:
        WP_DEBUG: true
        WP_DEBUG_LOG: true
```

<blockquote><img src="https://opengraph.githubassets.com/4ab87bfaed34a402a4848c08819709b9d5ac5abf6d9f75125db3f4efe852e23a/Varying-Vagrant-Vagrants/custom-site-template" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Varying-Vagrant-Vagrants/custom-site-template/blob/master/provision/vvv-init.sh">custom-site-template/provision/vvv-init.sh at master · Varying-Vagrant-Vagrants/custom-site-template</a></strong></div><div>A site provisioner for VVV. Contribute to Varying-Vagrant-Vagrants/custom-site-template development by creating an account on GitHub.</div></blockquote>

**Comment by cleantext** [comment]
Edit: Please excuse any typos (if any). It's late here and I'm posting last minute, before going afk.

Thank you for the comments very much. 

My jaw dropped when I saw the indentations of my config file.

Here's what I did:

1. Fixed the indentations (snippet below)
2. Updated VVV to 3.14.1 as per the docs: 
     * `git pull`  
     * `vagrant plugin update --local`  
     * `vagrant up --provision`
3. I removed the `wp_type: none` from the project's block in config.yml (oops!)
4. Removed the website as per the docs:  
     * Removed the appropriate section from the config.yml  
     * `vagrant reload --provision`  
     * Deleted the project's root folder: `rm -drfv /vvv-local/www/website`  
     * Dropped the project's database via PHPmyAdmin  
5. Moved the project back to the config file. Tried to provision with `vagrant provision --provision-with site-website_name` which led to a successful provisioning excluding two warnings (sorry it's super-late here and that's the best I can do). When I run WordPress it throws a bunch of `deprecated`, ending with `error: headers already sent` and quits loading the page. Basically, whitescreen of death with the mentioned error output. Again, sorry, no logs.
    * edit: This could be caused by the db prefix issue described below, so maybe disregard.
7. Next, I did a full provision: `vagrant reload --provision`
8. Everything is there and I got my custom parameters for `wp-config`, although the booleans look kinda odd:
```
define( 'SCRIPT_DEBUG', true );
define( 'WP_DEBUG_LOG', True );
define( 'WP_DISABLE_FATAL_ERROR_HANDLER', True );
define( 'FORCE_SSL_ADMIN', True );
define( 'WP_AUTO_UPDATE_CORE', 'minor' );
define( 'TABLE_PREFIX', 'uoia_' );
```

And this is the project's block from the config:
(i'm adding a # comment on each line that's confirmed not working)

```
  coolsite:
    description: "Website description."
    skip_provisioning: false
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    php: 8.0
    custom: # All custom properties at: https://github.com/Varying-Vagrant-Vagrants/custom-site-template
      wp_type: single
      delete_default_plugins: true  # not working, plugins/ has akismet and hello dolly
      locale: bg_BG
      install_plugins:  # none of the plugins are installed
        - wps-hide-login
        - query-monitor
      wpconfig_constants:
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true
        FORCE_SSL_ADMIN: true
        WP_AUTO_UPDATE_CORE: minor
        TABLE_PREFIX: uoia_
      db_prefix: uoia_
      admin_user: wordmin
      wp_version: 5.8.10
    hosts:
      - coolsite.test
```

Since I don't want to waste your time anymore than that, an important question:

I made a `.sh` script before all the troubleshooting tonight, intended for running after `vagrant ssh`. It runs a sequence of `wp cli` commands successfully. I had overlooked, however, adding an underscore to the table prefix. Now, wether I install WordPress with the `.sh` script or by doing a provision, I get the same erroneus prefix in the database. For example: `wp_posts` is `uoiaposts` instead of `uoia_posts`. 

The right prefix is specified in, both, the script and the config.yml, yet the they both keep populating the database with tables that have been prefixed without an underscore.

Would you know what mechanism, perhaps, caches this? Any thoughts welcome. I already did `wp cache flush` to no avail.

Many thanks once again. I referenced your comments multiple times while troubleshooting.

**Comment by tomjn** [comment]
> Would you know what mechanism, perhaps, caches this? Any thoughts welcome. I already did wp cache flush to no avail.

No caching, `wp cache flush` would clear out object cache but unless you're explicitly making an attempt to fetch a prefix from object cache this won't be the case ( and would be super weird so I expect you'd have spotted it ). It's more likely somethign in your script, if you shared it I could take a look?


> Removed the website as per the docs:

The order doesn't seem right here, a `vagrant reload --provision` would have ran the site provisioner but if the folder and DB hadn't been dropped then it wouldn't have created a fresh install

> although the booleans look kinda odd:

Most likely an artefact of YAML, it shouldn't break things but it would be nice to change it

It would be good to see the terminal output of that site, and I'd use `vagrant up --provision` rather than `reload` as reload doesn't trigger all the things that `up` does, and `--provision-with=` might not generate a TLS certificate if one hasn't already been created.

**Comment by cleantext** [comment]
> The order doesn't seem right here, a vagrant reload --provision would have ran the site provisioner but if the folder and DB hadn't been dropped then it wouldn't have created a fresh install

That's what I thought but decided to follow the docs blindly for a change:  https://varyingvagrantvagrants.org/docs/en-US/references/removing-sites/

> Removing A Site Completely
>
> There are multiple steps to doing this:
>
> Remove the site from config/config.yml and save
Reprovision
Delete its folder
Delete its database
>
> Reprovisioning will remove host entries and Nginx config files

I'll further update in 2-3 hours. I just updated my `config.yml` which throws an error that I cannot see, so it's time to take a break. Also, I provisioned properly (halt && up --provision) and want to see if the issues persist before posting further. Thank you for all the help.

Edit: 

> --provision-with= might not generate a TLS certificate if one hasn't already been created.

Just FYI, I created couple of projects this way and had no issues.


<blockquote><img src="https://varyingvagrantvagrants.org/images/vvv.png" width="48" align="right"><div><img src="/images/vvv.png" height="14"> VVV</div><div><strong><a href="https://varyingvagrantvagrants.org/docs/en-US/references/removing-sites/">Removing Sites</a></strong></div><div>There are several ways to remove a site in VVV.</div></blockquote>

**Comment by tomjn** [comment]
The provisioners get logged to files in the log folder that have more output than the terminal does, as long as you don't mind all the colour codes still there

**Comment by cleantext** [comment]
Edit: This came out long, but it's a mess after all. I suggest you read-through, before digging into the logs. A lot of things (but not all) are summarized at the end of this comment.

Here's the log for the site that I 'broke' with my wp-cli script. It continues to throw the same error (prefix mismatch) no matter that everything else is provisioning flawlessly:

[provisioner-site-utopia.log](https://github.com/user-attachments/files/19402740/provisioner-site-utopia.log)

That's the config.yml block for the site. All indentations consist of two spaces:

```
  utopia:
    description: "Internet platform."
    skip_provisioning: false
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    php: 8.0
    custom: # All custom properties at: https://github.com/Varying-Vagrant-Vagrants/custom-site-template
      delete_default_plugins: true
      locale: bg_BG
      install_plugins:
        - wps-hide-login
        - query-monitor
      wpconfig_constants:
        WP_DEBUG: true
        WP_DEBUG_LOG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true
        FORCE_SSL_ADMIN: true
        WP_AUTO_UPDATE_CORE: minor
        TABLE_PREFIX: uoia_
      db_prefix: uoia_
      admin_user: wordmin
      wp_version: 5.8.10
    hosts:
      - utopia.test
```

So, I've got the wp-config and the config.yml with the right prefixes (uoia_). However, the prefix for the tables in the db is without an underscore (uoia). 

But that's not the crazy part. Since I've had several recreations of the project (provision, delete folder + db, reprovision) it populates the database with the default tables alongside several others of the theme that was meant to run. When I check `current_theme` in the `options` table, it gives me the name of that theme, although it's not present in the `themes/`. Meanwhilte `themes/` contains the three default themes, nothing more. Also, I am 100% sure I haven't touched any of the settings because, upon accessing the `.test` address, I am redirected to the 5-min Install, because the db prefixes mismatch.

Here's the original shellscript that broke the project's "space."

[_install-wordpress.v1.txt](https://github.com/user-attachments/files/19402821/_install-wordpress.v1.txt)

Note: I renamed the .sh to .txt in order to upload it here.

Where the issue was (at least according to my tests):

```
wp config set WP_AUTO_UPDATE_CORE 'minor' --raw \
```
instead of:
```
wp config set WP_AUTO_UPDATE_CORE minor \
```

I've set the `--raw` flag, but also quoted `'minor'` because I thought it makes sense to pass it as a string alongside `--raw`, so that `wp config create` would add it to `wp-config.php` without additional process, e.g. adding quotes, etc. Then, I ran my install script. From that point on, `/usr/local/bin/wp` would throw an error complaining about `minor`. I don't have it on log, though. Took me awhile to notice that `minor` was the issue. Fixing the script did make the install go through, up to a functioning WP site, but left `wp` broken. For example, using `wp core install` would complete the install but display at least a couple `deprecated` or `warning` message about files in `wp-includes`. And similar weird stuff like that. `wp db` utilities would throw other `notice` level messages when executing. Or was it `deprecated`...

To confirm the issue is localized to a single folder/project, I duplicated the `utopia` `config.yml` block and only renamed the first line and the `host` line to be `utopia-zero`. Then I provisioned with `vagrant halt && vagrant up --provision-with site-utopia-zero` which gave me this:

```
==> default: Running provisioner: site-utopia-zero (shell)...
    default: Running: /tmp/vagrant-shell20250322-425659-r0sj6c.sh
    default:  ▷ Running the 'site-utopia-zero' provisioner...
    default:  * Pulling down the master branch of https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git
    default:  * Downloading utopia-zero provisioner, git cloning from https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git into /srv/www/utopia-zero
    default: Cloning into '/srv/www/utopia-zero'...
    default:  * utopia-zero provisioner clone successful
    default: PHP Warning:  Undefined array key "HTTP_HOST" in /srv/www/utopia-zero/public_html/wp-includes/functions.php on line 6327
    default: Warning: Undefined array key "HTTP_HOST" in /srv/www/utopia-zero/public_html/wp-includes/functions.php on line 6327
    default: error sending mail
    default: 2025/03/22 12:38:17 dial tcp 127.0.0.1:1025: getsockopt: connection refused
    default:  * sourcing of vvv-init.sh reported success
    default:  * VVV is adding an Nginx config from /srv/www/utopia-zero/provision/vvv-nginx.conf
    default: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
    default: nginx: configuration file /etc/nginx/nginx.conf test is successful
    default:  * Installed vvv-utopia-zero-1818f3b6.conf
    default:  ✔ The 'site-utopia-zero' provisioner completed in 0m 6s 280ms.
==> default: Running action triggers after up ...
==> default: Running trigger: VVV Post-Up...
    default: Running: inline script
    default:  * Updatin Guest VM /etc/hosts
    default:  * Checking PHP-FPM Services
    default:  * Restarting Mailhog
    default:  * Syncing clocks
    default: 22 Mar 12:38:27 ntpdate[4246]: adjust time server 185.125.190.58 offset 0.000891 sec
    default:  * clocks synced
```

I also confirmed, none of the `custom` directives have been followed by the provisioner for that project. Database looks fine. Although with a `wp_` prefix. `wp` is broken, did a test with `wp db columns`:

[utopia-zero_wp-db-columns_output.txt](https://github.com/user-attachments/files/19403217/utopia-zero_wp-db-columns_output.txt)

* I just learned how to capture stdout and stderr output in a file.

(Note: I'll explain some testing, but add a summary below it.)

Then I duplicated the block and renamed to: `utopia-dev` (first line and `host` line) and did `vagrant halt && vagrant up --provision`. And it provisioned as expected with all the requested edits to the `wp-config.php` file. Hooray :)

[provisioner-site-utopia-dev.log](https://github.com/user-attachments/files/19403176/provisioner-site-utopia-dev.log)

Meanwhile, however, the previously provisioned `utopia-zero` attempted what seems like an update and went crazy. I am referring to the part after the file removals:

[provisioner-site-utopia-zero.log](https://github.com/user-attachments/files/19403182/provisioner-site-utopia-zero.log)

Going full circle to the original `utopia`, after all the updating and (re)provisioning, `wp` is still broken there:

[utopia_wp-db-columns_output.txt](https://github.com/user-attachments/files/19403226/utopia_wp-db-columns_output.txt)

No specific reason to be testing with `wp db`.

Okay, it seems I've broken `wp` across the virtual machine for (only) the newly provisioned projects. The others are configured to skip provisioning. Navigating to `utopia-dev`, the newest project, and doing `wp db columns` or `wp db prefix` throws the same messages as in the previous example:

[utopia-dev_wp-db-columns_output.txt](https://github.com/user-attachments/files/19403262/utopia-dev_wp-db-columns_output.txt)

**Okay, to summarize and add final notes:**

1. utopia
* accessing the site: redirects to 5-min install
* PHP version change: 8.0.30, in accordance with `config.yml`
* `wp db columns` throws a bunch of `deprecated` before executing: [utopia_wp-db-columns_output.txt](https://github.com/user-attachments/files/19403226/utopia_wp-db-columns_output.txt)
* wp-config: processed in accordance with `config.yml`
* db: has the wrong prefix (`uoia` instead of `uoia_`) and includes tables from previous installations (and dropped databases)
* [/wp-content/debug.log](https://github.com/user-attachments/files/19403338/debug.log)

2. utopia-zero
* accessing the site: throws a fatal error [utopia-zero_front-end-error.txt](https://github.com/user-attachments/files/19403319/utopia-zero_front-end-error.txt)
* PHP version change: 8.0.30, in accordance with `config.yml`
* `wp db columns` throws a bunch of `deprecated` before executing: [utopia-zero_wp-db-columns_output.txt](https://github.com/user-attachments/files/19403320/utopia-zero_wp-db-columns_output.txt)
* wp-config: reflects the `custom` section from `config.yml` but has a `wp_` prefix regardless.
* db: has "clean install" structure with `wp_` prefix
* [/wp-content/debug.log](https://github.com/user-attachments/files/19403331/debug.log)

3. utopia-dev
* accessing the site: works as expected
* PHP version change: 8.0.30, in accordance with `config.yml`
* `wp db columns` throws a bunch of `deprecated` before executing: [utopia-dev_wp-db-columns_output.txt](https://github.com/user-attachments/files/19403262/utopia-dev_wp-db-columns_output.txt)
* wp-config: reflects the `custom` section from `config.yml` including the custom prefix
* db: has "clean install" structure with `uoia_` prefix
* [/wp-content/debug.log](https://github.com/user-attachments/files/19403341/debug.log)

Ironically, the reason I am avoidant of `vagrant halt && vagrant up --provision` is that it sometimes updates something and breaks things, sending me on a wild goose chase. And usually this wastes my whole workday. I am super thankful for the amazing project you people have put together. Just stating my reasons. 

Outside of "what the heck did I do with `minor` to break `wp` so bad", here are two questions that are big for me:

1. So, ultimately, to fully utilize the `config.yml` features, I cannot go for any form of per-project or "short-form" provisioning, is that the case?
2. What could've gone wrong with `wp` in `utopia`, theoretically, at least? +bonus: How do I fix it? Reinstall `wp` through `ssh`?
